### ISSUE TITLE
I got this issue when I tried to git push:  REMOTE HOST IDENTIFICATION HAS CHANGED! 

### ISSUE THREAD

**Issue by maxmiranda** [intitni/CopilotForXcode#107]
`@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is`

Is this due to adding Copilot for XCode? Is this normal?

**Comment by intitni** [comment]
No, it has nothing to do with Copilot for Xcode.

**Comment by shanecowherd** [comment]
This is because Github changed one of their keys, details here: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
