### ISSUE TITLE
Server unavailable, please make sure you have installed Node.

### ISSUE THREAD

**Issue by csweeney285** [intitni/CopilotForXcode#111]
I have node installed and set the path. But this error never disappears.

<img width="881" alt="Screenshot 2023-03-29 at 9 40 26 PM" src="https://user-images.githubusercontent.com/13783715/228705997-c0483324-fea3-4a82-aa29-f1ead2fa8cdb.png">

**Comment by intitni** [comment]
Did you check FAQ?

**Comment by kobe1081** [comment]
I have same error

**Comment by eccentricyan** [comment]
i have same error too

**Comment by kobe1081** [comment]
> 

Thank u.

**Comment by adiRandom** [comment]
> ~i have same error too~
> 
> download node here, restart app, then it works https://nodejs.org/en

This worked for me too. Not sure why the version from nvm / brew did not work, but whatever. Thanks a lot

**Comment by artem888** [comment]
same thing

<img width="887" alt="Screenshot 2023-04-17 at 18 26 52" src="https://user-images.githubusercontent.com/961175/232550196-33226833-337b-4aea-8458-abf9c3c1577d.png">

**Comment by intitni** [comment]
> same thing
> 
> <img alt="Screenshot 2023-04-17 at 18 26 52" width="887" src="https://user-images.githubusercontent.com/961175/232550196-33226833-337b-4aea-8458-abf9c3c1577d.png">

Your node version is just too old

**Comment by artem888** [comment]
@intitni switched to 19.2.0 works fine now. Thank you! 🙏

**Comment by H4MST3R3N3RGYBALL** [comment]
I am having this issue with latest node and my path to node is /usr/local/bin/node which is the my path

**Comment by escakot** [comment]
I'm getting some issues here. Does CopilotForXcode not work for organizations? I can't get past the `Not Authorized`..

![image](https://user-images.githubusercontent.com/4576455/232906139-7d1476a4-2f64-4afd-9d32-5ea2fc76f9c1.png)
![image](https://user-images.githubusercontent.com/4576455/232906162-91d346cd-19a7-474f-9f12-0701ac3bd56c.png)

**Comment by intitni** [comment]
@escakot To be honest, I don't know. Please open a new issue about that to see if other users can help.

**Comment by luojiego** [comment]
Must restart Copilot for Xcode after setting 'Path to Node'. Can this setting be fixed? It seems that many people are stuck here.

**Comment by uevs** [comment]
If you installed it with Homebrew you need to specify the path and version eg: `/opt/homebrew/Cellar/node/20.0.0/bin/node`
