### ISSUE TITLE
Can't use chat: Internal error

### ISSUE THREAD

**Issue by ivanscorral** [intitni/CopilotForXcode#119]
I set up all parameters in copilot but i get internal server error, api key shows as never used on openai.com

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/17148950/229139882-c78d21b9-aad1-446d-aea5-f2d8f957dcdc.png">

**Comment by intitni** [comment]
Sorry, I don't understand what you mean. What did you do? What happened after that? What did you expect to happen?
