### ISSUE TITLE
The scroll view stutters when launched by launch agent

### ISSUE THREAD

**Issue by intitni** [intitni/CopilotForXcode#122]
The helper app stutters when launched by the launch agent. It's smooth will it's launched by double-clicking the app icon. Anyone knows why?

**Comment by intitni** [comment]
It seem like, if the app is launched by the executable but not the app bundle, the app will be laggy when scrolling.

**Comment by intitni** [comment]
Looks like it will only affect SwiftUI ScrollView when the app is launched via launch agent.

**Comment by klemenkosir** [comment]
> The scrolling become smooth when I swap `ScrollView` with `List`...

I've had a similar issue with ScrollView on older iOS. Felt like a SwiftUI glitch. 🤷🏻‍♂️ Used List in the end - smooth as butter. 👌🏻

**Comment by intitni** [comment]
Released in 0.13.0
