### ISSUE TITLE
Permission not granted to use Accessibility API. Please turn in on in System Settings.app.

### ISSUE THREAD

**Issue by emarashliev** [intitni/CopilotForXcode#125]
Hello, can I have some help here?
I got this error message "Permission not granted to use Accessibility API. Please turn in on in System Settings.app."
<img width="676" alt="Screenshot 2023-04-02 at 12 39 34" src="https://user-images.githubusercontent.com/176615/229345093-02a04271-da9c-457d-9ffd-e3346c11a441.png">
And I don't know what permission is required, I already enabled the Copilot Xcode extension like that
<img width="464" alt="Screenshot 2023-04-02 at 12 44 16" src="https://user-images.githubusercontent.com/176615/229345220-56da684c-a1de-425b-9c8e-479e8ca5e03c.png">

I restarted the Xcode a few times even I restarted the computer and there is no change.

**Comment by intitni** [comment]
Please read README.md for detailed instruction

**Comment by emarashliev** [comment]
Yeah, I forgot the step with granting permission for the accessibility.
