### ISSUE TITLE
Does it support using with github copilot only?

### ISSUE THREAD

**Issue by leon-misfit** [intitni/CopilotForXcode#126]
I have signed in github copilot and remains OpenAI API key empty, but every editor command of the extension show alert that "You didn't provide an API key". Is is necessary to sign in both Github copilot and OpenAI? May it runs with one of those?
![image](https://user-images.githubusercontent.com/20273300/229473346-645428dc-71dd-4ff0-bcf1-deef04f7c80f.png)
![image](https://user-images.githubusercontent.com/20273300/229473896-20518008-4c77-4781-b6d7-cda151f98b1e.png)

![image](https://user-images.githubusercontent.com/20273300/229473854-75b5c15a-c736-4326-b025-7815c314a90a.png)

**Comment by intitni** [comment]
All suggestion features requires a GitHub Copilot account, all chat features require an OpenAI API Key.
