### ISSUE TITLE
Counldn't communicate with a helper application

### ISSUE THREAD

**Issue by bottotl** [intitni/CopilotForXcode#127]
I can't use this today, got a error message "Counldn't communicate with a helper application" 
Apple M1 Max
13.4 Beta版(22F5027f)
Xcode Version 14.3 (14E222b)
Xcode Command line tools 14.3（14E222b）
![image](https://user-images.githubusercontent.com/9837901/229762949-4f5ea745-5954-49ce-9cc5-85b54a42b2f2.png)

**Comment by intitni** [comment]
Please check if the helper app is running. If it's not running, the launch agent is probably not correctly set up. You can try to utilize the buttons in the host app to reinstall and reload the launch agent or refer to the FAQ for further guidance on this matter.

**Comment by bottotl** [comment]
thinks it works for me
