### ISSUE TITLE
The model: gpt-4 does not exist

### ISSUE THREAD

**Issue by ngugg** [intitni/CopilotForXcode#128]
### I have already set up the OpenAI API key, but chatGPT is not able to use it

<img width="454" alt="1" src="https://user-images.githubusercontent.com/21261333/230256126-e00c06e5-4b20-4ac1-b430-e5bf33e8b526.png">

**Comment by hjh920722** [comment]
+1

**Comment by intitni** [comment]
You probably don't have access to gpt-4. Did you signed up the waitlist?

**Comment by ngugg** [comment]
I have indeed not applied yet. Thank you. I just applied to join.
