### ISSUE TITLE
Incorrect floating widget position when disable Displays have separate Spaces option.

### ISSUE THREAD

**Issue by RookieZn** [intitni/CopilotForXcode#129]
**Version**

0.10.0

**Screenshot**
![Screenshot 2023-04-06 at 12 40 34](https://user-images.githubusercontent.com/17445652/230273654-f72da37c-350b-4d00-974f-e4e1166dce24.png)
![Screenshot 2023-04-06 at 12 31 33](https://user-images.githubusercontent.com/17445652/230273504-51831a8c-ab9c-4d9a-9dd0-9cd02b8e4558.png)

**Reproduce steps**
1. You have two displays. Let's say the left one is A, right one is B.
2. Open System Settings -> Desktop & Dock -> Uncheck Displays have separate Spaces.
3. Set A as the main screen (with Dock).
4. Open Xcode, and move its window to B. You will see the widget is pinned to the left edge of B.
5. Type something to trigger floating suggestions. You will see the suggestion window shows up in A, and is overlapped by Dock.

**Comment by intitni** [comment]
Released in 0.11.0
