### ISSUE TITLE
Improved install instructions

### ISSUE THREAD

**Issue by stuartrr** [intitni/CopilotForXcode#13]
Settings.app is now called "System Settings.app". Perhaps change instructions in the README to:

"From the Apple menu located in the top-left corner of your screen click "System Settings". Navigate to "Privacy & Security" then toward the bottom click "Extensions". An entry called "Xcode source Editor" with subtext "copilot" should be there. Click it and tick "Copilot".

**Comment by thyselius** [comment]
Yes, this took some time for me as well.

To get it to work, I needed to:

1
In macOS 12.6 Monteray Extensions is actually ITS OWN icon in System Settings. So You DON'T click "Privacy & Security to get there.
So,  System Settings -> Extensions -> Added extensions -> √ "Xcode Source Editor"

2
Also You need to add "Copilot for XCode" in Security & Privacy -> Privacy tab -> Accessibility

3
Also You need to add "Copilot for XCode" in Security & Privacy -> Privacy tab -> Input Monitoring

**Comment by AndrewSB** [comment]
this was helpful, i was stuck until i found this issue. merging this/putting these instructions into the next release would be great!

**Comment by intitni** [comment]
README.md updated.

**Comment by stuartrr** [comment]
Thanks for putting that language in. However, I think @thyselius's steps (2) and (3) are also necessary.

I actually had given up but will try @thyselius steps when I give it ago again.

**Comment by intitni** [comment]
I have put steps (2) and (3) in the next section "Giving Permissions to the App". But yes the instructions in the app should also be updated. A PR will be great.

**Comment by patiljignesh** [comment]
Question, does this work in Ventura?

**Comment by intitni** [comment]
@patiljignesh Yes it does
