### ISSUE TITLE
Extension sometimes stops registering hotkeys

### ISSUE THREAD

**Issue by alex-reilly-pronto** [intitni/CopilotForXcode#137]
It's unclear what causes it, but sometimes the extension will stop capturing hotkeys, and the default behavior will occur instead. For example if I have option+] bound to "accept suggestion", then ‘ will be typed instead of accepting the suggestion. Accepting the suggestion can still be done by clicking on the button. Restarting Xcode fixes the problem.

**Comment by intitni** [comment]
Are you using the accept suggestion with Accessibility API feature?

**Comment by alex-reilly-pronto** [comment]
Yes

**Comment by intitni** [comment]
My guess is that a tweak I made like 2 versions ago may disable the source extension for some reason. When the hotkeys stop working, you can check if the Copilot menu is grayed out in the menu bar. You can see the pull request #139 for more details. It is already released in 0.11.1. Please let me know if the bug remains.

**Comment by alex-reilly-pronto** [comment]
Alright I'll keep an eye out for that and report back. Thanks!

**Comment by alex-reilly-pronto** [comment]
Just got it again. The menu item isn't greyed out. Also if I disable the accessibility API feature, then the "Accept" button stops doing anything as well.

Probably unrelated, but tapping the "Accept" button causes the editor to scroll the line to the top as well as inserting the suggestion.

**Comment by intitni** [comment]
Can you still accept the suggestion by clicking the menu item?

**Comment by alex-reilly-pronto** [comment]
I'll give that a try next time it comes up 👍

**Comment by intitni** [comment]
I have released 0.11.2 which solves a bug that can prevent the suggestion from being accepted. Please give it a try!

**Comment by intitni** [comment]
> it still appears from time to time. Usually, it happens after updating to the new version. 
> 
> **Version:** 0.15.2

Did you restart Xcode after updating to the new version?

**Comment by ftp27** [comment]
@intitni Yep. But I think I can try to reboot my Mac also. Do you know why it happens?

**Comment by intitni** [comment]
> @intitni Yep. But I think I can try to reboot my Mac also. Do you know why it happens? 

I don't know. Rebooting won’t help. Please clearly describe your issue, and answer the following questions. 

- Did the Copilot menu grey out when you can't use the keyboard shortcuts?
- If not, did you see the keyboard shortcuts listed next to each command name?
- What happened when you use the keyboard shorcuts?

**Comment by ftp27** [comment]
@intitni All start work as supposed to be. I just restarted Xcode more than one time. Thank you
