### ISSUE TITLE
Always loading after Installing, and can't be seen anywhere in Xcode.

### ISSUE THREAD

**Issue by iaendi** [intitni/CopilotForXcode#138]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/130339496/230853306-78ae620a-8315-4089-8807-1f72f2f8f3e4.png">

I provided a new github account (started free trail today), which worked for the first time I installed CopilotForXcode.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/130339496/230854847-f5c9e2d5-b61b-44ae-9033-2de35db1c402.png">

Every time I open CopilotForXcode to check my GitHub Copilot account, it just keeps showing "loading". Even after reinstalling CopilotForXcode three or four times, the same issue persists. Additionally, I cannot see the CopilotForXcode plugin in Xcode.

**Comment by intitni** [comment]
Please check FAQ for instructions to validate the launch agent installed by Copilot for Xcode. 

To enable the editor extension for Xcode, you will need to turn it on in Settings.app. Pleas see README.md for more details.

**Comment by gscalzo** [comment]
mmm this error is suspicious...
<img width="859" alt="Screenshot 2023-04-17 at 17 12 43" src="https://user-images.githubusercontent.com/5433/232546535-b1c59d42-d7ad-468b-89a0-cb9fb7c4df73.png">
