### ISSUE TITLE
Key bindings for most common commands?

### ISSUE THREAD

**Issue by KieranConlon** [intitni/CopilotForXcode#14]
Having just installed and configured the CoPilotForXcode extension all works great but my experience is that I had to always select the menu options to get CoPilot suggestions/actions (maybe I did not setup everything correctly??).

Could creating some default keybindings help with this?
For some, keybindings are a very personal choice as they are often customised but I found these worked pretty well and did not conflict with any existing/standard Xcode keybindings.

CoPilot -> Get Suggestions:  ⌥?
CoPilot -> Accept Suggestion:  ⌥}
CoPilot -> Reject Suggestion:  ⌥{
CoPilot -> Next Suggestion:  ⌥>
CoPilot -> Previous Suggestion:  ⌥<

Essentially using ⌥⇧ as the "access" key combination for all bindings.

![Xcode-CoPilot_KeyBindings_Settings](https://user-images.githubusercontent.com/33759139/213192992-1714b25f-bfc9-46d4-aa7e-b594b2c84092.png)

![Xcode-CoPilot_KeyBindings](https://user-images.githubusercontent.com/33759139/213193013-656ffd36-2c10-45ee-8a62-aad38fda29a4.png)

**Comment by intitni** [comment]
Thanks for sharing, I don't think we can add default key bindings to commands, but will add this recommendation to readme.

**Comment by intitni** [comment]
A key binding section is added to README.md with your recommendation.

**Comment by icezohu** [comment]
<img width="830" alt="Snipaste_2023-03-02_19-09-16" src="https://user-images.githubusercontent.com/3282625/222412505-78c73260-1732-46f0-9857-e92696ccfa19.png">
Suggesting another set of key bindings...

**Comment by WingCH** [comment]
i think add this key bindings is very helpful for me, thanks @KieranConlon and hope can add into README

**Comment by intitni** [comment]
They are now added to readme

**Comment by 13088992520** [comment]
xcode setting  did not show the CoPilot key bindings. Anyone know Why?

**Comment by intitni** [comment]
@13088992520 Please make sure you have enabled the source editor extension [https://github.com/intitni/CopilotForXcode#enable-the-extension](https://github.com/intitni/CopilotForXcode#enable-the-extension)

**Comment by lisbonc1987** [comment]
Hey guys! Just installed copilot for Xcode. I followed the recommended key bindings but whenever I use option + shift + }, it gives me a single quote. I have an external keyboard but it has a Mac toggle if that makes a difference. Thank you for any tips! I am new to the Mac world to learn swift so I am not sure if I am doing something wrong haha. Windows user most of my life.

**Comment by KieranConlon** [comment]
@lisbonc1987 Make sure that you have setup the shortcuts in Xcode's Key Bindings as that will override the default key press.
To be honest, it doesn't matter if you have an external keyboard (I use an external keyboard 99% of the time with my MacBook Pro).

BTW welcome to developing with a Mac.  As they say, once you go Mac you never go back!  
Next thing you will discover Homebrew and get all the command line tools and libraries that you never knew you needed!!!  :)
