### ISSUE TITLE
The extension barely works

### ISSUE THREAD

**Issue by yansigit** [intitni/CopilotForXcode#140]
![Screenshot 2023-04-10 at 5 40 07 AM](https://user-images.githubusercontent.com/44089734/230895061-c6bc4c6f-d76c-4cdd-896a-08a794c5a1be.png)

![Screenshot 2023-04-10 at 5 40 57 AM](https://user-images.githubusercontent.com/44089734/230895073-cd24a011-fb2f-471d-b3b8-cf12674a8c94.png)
![Screenshot 2023-04-10 at 5 41 15 AM](https://user-images.githubusercontent.com/44089734/230895074-55fd9e04-59a8-47e9-b354-65b0b9c8f635.png)

![Screenshot 2023-04-10 at 5 42 47 AM](https://user-images.githubusercontent.com/44089734/230895247-cc29913f-4e63-4cab-859b-003851aa3c31.png)
![Screenshot 2023-04-10 at 5 44 21 AM](https://user-images.githubusercontent.com/44089734/230895421-6ebcb769-f52f-4dbb-a993-ac9e25093184.png)

Although I sometimes see the suggestion widget window, most of the time I don’t get any results even if I use the shortcut keys.
I upload some screenshots of my settings.

**Comment by intitni** [comment]
Your settings look correct to me. You can use Console.app to see what went wrong by setting the filter to process:CopilotForXcodeExtensionService
category:Service

If you see "Prefetch suggestions." when you stop typing and wait for a second, that means real-time suggestion is triggered. If there is an error happening on the GitHub Copilot side, you should see an error there.

**Comment by 15837003633** [comment]
![image](https://user-images.githubusercontent.com/6936198/231932917-e1cb94cc-b1b1-440a-bfad-676fb5e9c6dd.png)

**Comment by intitni** [comment]
When you see a LanguageServerError.ServerError, it usually means the Github Copilot language server failed to generate a suggestion for you. The reason is unknown because they are not documented, and the source code is obfuscated.

**Comment by jscalo** [comment]
I also get 

> LanguageServerProtocol.ServerError error 8.

**Comment by llbartekll** [comment]
I get bunch of this errors in the console and actually no suggestions at all.

**Comment by llbartekll** [comment]
it didn't help
![Screenshot 2023-04-24 at 11 17 21](https://user-images.githubusercontent.com/25840476/233953960-ddac44cb-1353-450c-b619-e17c5ceb7c46.png)

**Comment by llbartekll** [comment]
Ok, the was an issue with my subscription 😅

**Comment by llbartekll** [comment]
but still, it works for only one minute and stops suggesting, also looks like it terminates and is no longer available in the xcode.

**Comment by intitni** [comment]
> but still, it works for only one minute and stops suggesting, also looks like it terminates and is no longer available in the xcode.
> 
> and to make it work again I need to restart the xcode

Please open a new issue about that, show me the crash report if there is any.
