### ISSUE TITLE
Issues with Quick Open (⌘⇧O)

### ISSUE THREAD

**Issue by patteruel-dev** [intitni/CopilotForXcode#145]
Maybe I'm too fast, but when I type something on the IDE, then decided to open another file by using **Quick Open**, it dismisses the Quick Open box, and I accidentally make changes to the file, which I had to erase and do a Quick Open again, only to have it dismiss and for me to accidentally make a change on the file and correct it and reopen Quick Open... I could go on forever.

The only temporary workaround is to... WAIT. After making a change on the file, I have to wait maybe 1 or 2 seconds, then open Quick Type, type a file name and open it.

It's not a big issue right now. But when I do stuff fast, it is an issue that I'd like to be removed. The Xcode Copilot works great, but there are some instances like this that makes me want to not use it.

Here's the current version and settings I'm using.
<img width="1060" alt="Screenshot 2023-04-12 at 9 03 41 AM" src="https://user-images.githubusercontent.com/39513487/231320595-e26d3ea0-bc34-4d21-a486-85cdb947a581.png">

**Comment by intitni** [comment]
You can revert to use version 0.11.0, which newer uses Apple Scripts to get real-time suggestions. I will bring the tweak I disabled in 0.11.1 back in the next release.

**Comment by intitni** [comment]
A new version 0.11.2 is released
