### ISSUE TITLE
Unable to copy ChatGPT's response for certain text formats

### ISSUE THREAD

**Issue by KieranConlon** [intitni/CopilotForXcode#149]
When using the Chat feature, the response generated by ChatGPT can usually be copy-pasted by triple-clicking on the response or using CMD-a to select all the text.

For some responses, triple-clicking or CMD-a will only select a single paragraph of the response.

Can we have a copy function similar to what has already been done for code blocks to copy the entire response from ChatGPT?

Use case...

I am updating some code for a project I was working on some time ago, and I have used ChatGPT to remind me what the function does (yes, I know I should have documented it properly the first time!!!).

I asked ChatGPT to write a DocC comment for the function, which works great, but I cannot copy the DocC comment as a single block of text and I have to write the DocC formatted comment manually.

![image](https://user-images.githubusercontent.com/33759139/231988306-66ed3667-91ab-4b94-99e8-1e24839ae21b.png)

**Comment by KieranConlon** [comment]
Just a follow-up.

I have noticed that when asking ChatGPT to create a DocC comment.
Sometimes it returns the comment in a `/** ... */` block that can not be directly copy-pasted; other times, it returns the comment with each line commented with `///` (as per DocC style guidelines), which can be easily copy-pasted.

Giving ChatGPT the instruction, `Write a DocC comment for this function using proper DocC style guidelines.` always produces the desired response.
But, in any event, it would be nice to be able to cut-paste the entire response from ChatGPT.

**Comment by intitni** [comment]
Released in 0.12.0
