### ISSUE TITLE
Disable Empty copilot suggestion when enable "real-time suggestion"

### ISSUE THREAD

**Issue by MaksimBezdrobnoi** [intitni/CopilotForXcode#15]
Maybe add ability to disable Empty copilot suggestions when enabled "Real-time suggestion"? 
<img width="474" alt="image" src="https://user-images.githubusercontent.com/85101110/213398331-8c5a023e-f4d2-4f7d-a560-0ac865342224.png">

**Comment by AndrewSB** [comment]
adding onto this, i often see the suggestion 

<img width="387" alt="Screenshot 2023-01-20 at 1 02 15 PM" src="https://user-images.githubusercontent.com/3814772/213804674-f4dbe79b-72f5-4218-96ab-8056523737c4.png">

with real-time mode turned on, and i'm not sure why

**Comment by intitni** [comment]
Right, empty suggestions should be ignored

**Comment by intitni** [comment]
Released in 0.6.0
