### ISSUE TITLE
Issue with Github Copilot Account

### ISSUE THREAD

**Issue by marekslk** [intitni/CopilotForXcode#159]
When trying to connect Github Copilot in Accounts section, noting happens and I experience infinite loading.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/31618932/233377932-46ed06a7-1292-4486-8bc9-f5aa20236723.png">

<img width="897" alt="image" src="https://user-images.githubusercontent.com/31618932/233378114-208e1154-59f4-4ec2-ab58-03183ef7e95a.png">

**Comment by intitni** [comment]
Please check FAQ Q2 for details

**Comment by blalger** [comment]
I have also been experiencing this issue for a couple of versions (maybe since upgrading to 11.0? I don't recall the exact version to be honest).  Followed the FAQ, tried reinstalling multiple times from brew and release.  Verified all permission recommendations, no luck.

![Screenshot 2023-04-23 at 9 55 30 AM](https://user-images.githubusercontent.com/8065240/233844056-8d336344-2e6e-4617-8a15-2613be003dbf.png)

**Comment by intitni** [comment]
> I have also been experiencing this issue for a couple of versions (maybe since upgrading to 11.0? I don't recall the exact version to be honest). Followed the FAQ, tried reinstalling multiple times from brew and release. Verified all permission recommendations, no luck.
> 
> ![Screenshot 2023-04-23 at 9 55 30 AM](https://user-images.githubusercontent.com/8065240/233844056-8d336344-2e6e-4617-8a15-2613be003dbf.png)

I don't think you two are experiencing the same issue. The XPC service, aka the CopilotForXcodeEditorExtension is already running on your machine. 

Based on the screenshot you provided, I noticed some `stderr` messages appearing. The app will not access those files, so I guess they are in your `bashrc` or some other bash configurations. These errors could have prevented Node from running. You can try either locate and fix the errors or disable the ﻿`Run node with interactive logged-in bash` option in the host app.

**Comment by blalger** [comment]
Oops, didn't notice the original question was also stuck Loading the service. You're right however, disabling the "Run node with interactive logged-in bash" setting fixed my issue. Thank you!

**Comment by jasonkruit** [comment]
I am also having issues with the copilot account always loading. My xpcservice is running fine. I have node installed fine and can issue commands from the comman line to node. My privacy and scurity settings are all enabled. I have checked all the obvious issues the FAQ on questions 2 & 3. What would you need to help figure out why the copilot auth never loads? I would be happy to provide any details needed.
![Screenshot 2023-04-28 at 12 34 23 PM](https://user-images.githubusercontent.com/95638/235215999-1282a915-5a7a-4bb9-a842-d588c163c0fc.png)

**Comment by intitni** [comment]
> I am also having issues with the copilot account always loading. My xpcservice is running fine. I have node installed fine and can issue commands from the command line to node. My privacy and security settings are all enabled. I have checked all the obvious issues from the FAQ on questions 2 & 3. What would you need to help figure out why the copilot auth never loads? I would be happy to provide any details needed.
> 
> ![Screenshot 2023-04-28 at 12 34 23 PM](https://user-images.githubusercontent.com/95638/235215999-1282a915-5a7a-4bb9-a842-d588c163c0fc.png)
> 
> 

If you have already tried changing  the value of "Run node with", the next things you can try are:

1. Run the language server in terminal to see if it works: `node /Applications/Copilot\ for\ Xcode.app/Contents/Applications/CopilotForXcodeExtensionService.app/Contents/Resources/copilot/dist/agent.js --stdio`
2. Read the logs in Console.app check if there's any `stderr` sending by CopilotForXcodeExtensionService.

**Comment by jasonkruit** [comment]
Here is the output. I didn't see any stderr output. 
<img width="1867" alt="Screenshot 2023-05-01 at 8 30 27 AM" src="https://user-images.githubusercontent.com/95638/235458474-a8f397eb-74d7-4d74-a4a1-0f7dff573d49.png">

**Comment by intitni** [comment]
@jasonkruit please turn this off so logs won't be buried by the window related warnings
<img width="457" alt="Screenshot 2023-05-01 at 21 42 51" src="https://user-images.githubusercontent.com/793147/235460270-852e6895-68da-4ec2-a0e2-38b8658c6829.png">

**Comment by ErlichLiu** [comment]
Hello, I have encountered another issue which may be related to this one. I have enabled Github Copilot and was hoping to log in through it, but ran into this problem.
<img width="916" alt="iShot_2023-05-06_19 59 51" src="https://user-images.githubusercontent.com/25130303/236622864-d6804d12-e619-44ff-b951-43380e63b371.png">

**Comment by intitni** [comment]
@ErlichLiu Are you still experiencing the issue? The problem seems to be occurring inside the language server. It is likely due to the language server receiving HTML instead of JSON as a response when attempting to send a request. This could be caused by a temporary issue or other network issues. If you are using a proxy, please try disabling it. If not, please try enabling it and use enhanced mode, if possible.

**Comment by ErlichLiu** [comment]
> Hi, I still experiencing this issue. I have tried disable the proxy, or use the enhanced mode, but I have not solved this problem. What else can I try to do?”

**Comment by intitni** [comment]
@ErlichLiu You may attempt to MITM the request sent by Node to *.github.com to troubleshoot the issue. Please note that I attempted this but was unsuccessful.

Alternatively, you may try examining the logs. By default, logging is disabled and there is no toggle to turn it on. So you will have to run the extension service target in Xcode in release mode:

1. Clone the source code and initialize the submodule copilot.vim. Stay on the main branch.
2. Go to `GitHubCopilotService.swift`, update the line `localServer.logMessages = false` to `true`.
3. Run the Extension Service target in release mode.
4. Open the installed host app, click remove launch agent and reload launch agent. Keep it open. the source extension should now talk to the Xcode-running extension service.

When you click sign-in, you should see logs like this printed to the debug area. Hopefully you can see some errors there.
```
2023-05-07 16:29:00.460980+0800 CopilotForXcodeExtensionService[92913:1390890] [ProtocolTransport] received: {"jsonrpc":"2.0","id":2,"result":{"status":"PromptUserDeviceFlow","userCode":"","verificationUri":"https://github.com/login/device","expiresIn":899,"interval":5}}
```

**Comment by ErlichLiu** [comment]
> @ErlichLiu You may attempt to MITM the request sent by Node to *.github.com to troubleshoot the issue. Please note that I attempted this but was unsuccessful.
> 
> Alternatively, you may try examining the logs. By default, logging is disabled and there is no toggle to turn it on. So you will have to run the extension service target in Xcode in release mode:
> 
> 1. Clone the source code and initialize the submodule copilot.vim. Stay on the main branch.
> 2. Go to `GitHubCopilotService.swift`, update the line `localServer.logMessages = false` to `true`.
> 3. Run the Extension Service target in release mode.
> 4. Open the installed host app, click remove launch agent and reload launch agent. Keep it open. the source extension should now talk to the Xcode-running extension service.
> 
> When you click sign-in, you should see logs like this printed to the debug area. Hopefully you can see some errors there.
> 
> ```
> 2023-05-07 16:29:00.460980+0800 CopilotForXcodeExtensionService[92913:1390890] [ProtocolTransport] received: {"jsonrpc":"2.0","id":2,"result":{"status":"PromptUserDeviceFlow","userCode":"","verificationUri":"https://github.com/login/device","expiresIn":899,"interval":5}}
> ```
Thanks for your help. I couldn't get the biuld success because of some packet dependency issues, and I couldn't continue with the solution. Is there anything else I can try?
<img width="295" alt="image" src="https://user-images.githubusercontent.com/25130303/236982283-158e2b2f-190d-4d36-bd89-51d5d8b2acf0.png">

**Comment by intitni** [comment]
@ErlichLiu What exactly is the package resolution issue you're experiencing? It's possible that there could be an issue with your connection to GitHub. Have you made any changes to your hosts file related to GitHub?

**Comment by ErlichLiu** [comment]
> @ErlichLiu What exactly is the package resolution issue you're experiencing? It's possible that there could be an issue with your connection to GitHub. Have you made any changes to your hosts file related to GitHub?
@intitni Thank you very much. It was my own issue. I had changed the IP address in my hosts file for GitHub before this happened. However, I have now restored it and everything is working perfectly fine again. Thank you once more.
