### ISSUE TITLE
models max token reached no matter how small amount of code I highlight 

### ISSUE THREAD

**Issue by CirrusThink** [intitni/CopilotForXcode#165]
- [x] I have checked FAQ, and there is no solution to my problem
- [x ] I have searched the existing issues, and there is no existing issue for my problem

**Describe the problem**
This model's maximum context length is 4097 tokens. However, you requested 4496 tokens (400 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.

**Additional information (optional)**
macOS version: Ventura
Copilot for Xcode version: 0.12.0 (90)
Node version: 20.0.0

**Comment by intitni** [comment]
The Max Token settings in the host app is for the `max_token` parameter from the ChatGPT API, which represents the max possible tokens for the reply. So you will want to set it to a lower value, for example, half of the maximum tokens.

A new release is coming later today UTC+8. It will manage the token limit automatically and will change the meaning of the settings.
