### ISSUE TITLE
"You exceeded your current quota, please check your plan and billing details."

### ISSUE THREAD

**Issue by Kayull** [intitni/CopilotForXcode#171]
- [x] I have checked FAQ, and there is no solution to my problem
- [x] I have searched the existing issues, and there is no existing issue for my problem

**Describe the problem**
When trying to chat I using either File or global chat I get the error: You exceeded your current quota, please check your plan and billing details.
![Screenshot 2023-04-24 at 12 01 09](https://user-images.githubusercontent.com/45533484/233978002-85cae064-0387-42c7-b91e-cacff21d4f2e.png)
<img width="451" alt="Screenshot 2023-04-24 at 11 59 03" src="https://user-images.githubusercontent.com/45533484/233978006-616d486a-fd1a-41f5-8536-b1792739a391.png">
<img width="200" alt="Screenshot 2023-04-24 at 11 57 54" src="https://user-images.githubusercontent.com/45533484/233978010-f35a418d-556f-44db-b358-a0c52692667c.png">

**Additional information (optional)**
macOS version: 13.1
Copilot for Xcode version: 0.13.2
Node version: 20.0.0

**Comment by intitni** [comment]
The chat feature is powered by OpenAI ChatGPT, not GitHub Copilot.

**Comment by Ashtronaut09** [comment]
Hi @intitni do you know how this is resolved? I am getting the same error. I have a paid account with ChatGPT and am not using it often, I am well within limits. Not sure why it's erroring.

**Comment by intitni** [comment]
> Hi @intitni do you know how this is resolved? I am getting the same error. I have a paid account with ChatGPT and am not using it often, I am well within limits. Not sure why it's erroring.

You have to generate an API key and paste it into the app.

**Comment by intitni** [comment]
@Ashtronaut09 The message is definitely from OpenAI. You can check your usage here https://platform.openai.com/account/usage

**Comment by Ashtronaut09** [comment]
Thanks @intitni ! I understand that, but what I'm trying to understand why is OpenAI not working with this. Is it on our end or their end?

**Comment by intitni** [comment]
> Thanks @intitni ! I understand that, but what I'm trying to understand why is OpenAI not working with this. Is it on our end or their end?

@Ashtronaut09 it's probably on their end

**Comment by Ashtronaut09** [comment]
@intitni thanks Shx! I just bought you a few coffees, will keep doing so as I use it. Appreciate your help!

**Comment by mikeRozen** [comment]
@intitni IF I want to use only the copilot i.e generating code, is it possible?
(I mean we have the chat GPT for free , why we need to pay extra money for the same chat in Xcode? slightly confused )

**Comment by intitni** [comment]
@mikeRozen you don't have to use the features you don't need, just ignore them.

**Comment by mikeRozen** [comment]
Not sure I follow there  is no way to use copilot in Xcode without paying to openAI for the token base usage, right?
The only way I can think of is to use visual studio code

**Comment by intitni** [comment]
@mikeRozen You can use GitHub Copilot and Codeium for the suggestion feature. If you don't need Prompt to Code and Chat, you don't need an OpenAI API key.

**Comment by mikeRozen** [comment]
I am slightly confused.
 to use copilot in Xcode I must have openAI key for extra money although I already payed for copilot. please share a reference that explains code suggestion in Xcode without open AI key.

**Comment by intitni** [comment]
@mikeRozen I am also confused. 

The app has 3 main features, as mentioned in the readme. The suggestion feature is powered by GitHub Copilot and Codeium, the other two are powered by ChatGPT.

To use the suggestion feature, you need to follow the instructions in the readme, set up the app, download the language server, and sign in to your GitHub account. That’s it. You can find some videos from YouTube posted by other users if you are still confused.

**Comment by mikeRozen** [comment]
I don't know the Codeium is somehow works for code suggestion on Xcode, Unfortunately I couldn't make copilot to have code suggestion on Xcode(maybe paying for openAI would improve it ), in visual studio code it worked (still not that great experience )

**Comment by intitni** [comment]
@mikeRozen I don't want to continue this conversation anymore. Codeium is just another GitHub Copilot like service, and setting up an OpenAI API key won't change anything if you are using the suggestion feature. If the suggestion feature is not working for you, please read FAQ for a solution and open a new issue if you need further help.
