### ISSUE TITLE
For that toggle with Disable suggestion feature globally?

### ISSUE THREAD

**Issue by MaksimBezdrobnoi** [intitni/CopilotForXcode#173]
- [X ] I have checked FAQ, and there is no solution to my problem
- [ X] I have searched the existing issues, and there is no existing issue for my problem

**Describe the problem**
How to use globally suggestion? I added my project, but Copilot also give me strange suggestions.
Or I don't understand something? 
<img width="384" alt="image" src="https://user-images.githubusercontent.com/85101110/234226094-9d9fadda-b18a-420c-afe3-cd2bb1d3f2a3.png">

**Comment by intitni** [comment]
What do you want to achieve with this feature?

**Comment by MaksimBezdrobnoi** [comment]
I thought that if I add my project, Copilot will be able to see all files and will suggest more relevant code

**Comment by intitni** [comment]
Uh that's not what it does. It's for those who want to protect their company's project code from being spied on by GitHub Copilot.

**Comment by MaksimBezdrobnoi** [comment]
Oh, thanks. What do you think, is it possible that in the future will be available to check all files in the project by Copilot and suggestions will be more relevant? Or copilot will always work only in one file

**Comment by intitni** [comment]
It's not possible to do on my side.

**Comment by MaksimBezdrobnoi** [comment]
that's sad. Ok, thanks

**Comment by intitni** [comment]
It's here https://github.com/intitni/CopilotForXcode/releases/tag/0.14.0.beta.5
