### ISSUE TITLE
The request timed out.

### ISSUE THREAD

**Issue by huangpengfei-tal** [intitni/CopilotForXcode#182]
- [ ] I have checked FAQ, and there is no solution to my problem
- [ ] I have searched the existing issues, and there is no existing issue for my problem 

**Describe the bug and the expected behavior**
A clear and concise description of what the bug is. And a clear and concise description of what you expected to happen.

**To reproduce**
1.

**Additional information (optional)**
macOS version:  13.2.1 (22D68)
Copilot for Xcode version: 14.2
Node version:  v20.0.0

The request timed out.

**Comment by intitni** [comment]
Please first refer to the FAQ to check if it may address your problem. If you need further help, please clarify your question.

**Comment by txyhost** [comment]
https://github.com/intitni/CopilotForXcode/assets/59674898/0184afaa-bcf4-4eba-94ee-9e9697ce3b69

请问  视频里的问题如何解决

**Comment by intitni** [comment]
> 
> 
> https://github.com/intitni/CopilotForXcode/assets/59674898/0184afaa-bcf4-4eba-94ee-9e9697ce3b69
> 
> 
> 
> 请问  视频里的问题如何解决

请确认你是否能正常连接到 github.com，然后查看的 hosts 中有没有关于 GitHub 的改动，如果没有，请更新到 0.15 版本并打开 GitHub Copilot 的 verbose log，在 Console.app 中查看是否存在问题。

**Comment by txyhost** [comment]
> > 请问视频里的问题如何解决
> 
> 请确认你是否可以正常连接到 github.com，然后查看主机中没有关于 GitHub 的改动，如果没有，请更新到 0.15 版本并打开 GitHub Copilot 的详细日志，在 Console.app 中查看是否存在问题。

使用0.15.2版本 可以可以了

**Comment by panxiang1017** [comment]
可能是/etc/hosts里面加过github的映射，我这边也是类似问题，把hosts里面的github映射删掉就好了
