### ISSUE TITLE
[Feature Request]: how do you close the chat window with keyboard?

### ISSUE THREAD

**Issue by garyhighlinebeta** [intitni/CopilotForXcode#189]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

How do you close the chat window with keyboard? Tried escape, command+w

### How to reproduce the bug.

It just happens!

**Comment by intitni** [comment]
Converted this issue to a feature request.

**Comment by intitni** [comment]
Released in 0.14.1.

you can now use command+w to close it or command+m to minimize it

**Comment by garyhighlinebeta** [comment]
@intitni can you make it so that it gives the focus back to the code window?
