### ISSUE TITLE
Copilot version don't update

### ISSUE THREAD

**Issue by MaksimBezdrobnoi** [intitni/CopilotForXcode#20]
Copilot version doesn't update. I tried Restart XPC services, but nothing happened. Still 1.65.0 version

<img width="916" alt="image" src="https://user-images.githubusercontent.com/85101110/214795642-8fc8afde-67e1-43f3-9f85-447114f9dd7a.png">

**Comment by intitni** [comment]
The copilot version is not updated in this version.

**Comment by MaksimBezdrobnoi** [comment]
Hm, but that's mean "Bump copilot to 1.8.0"?
<img width="573" alt="image" src="https://user-images.githubusercontent.com/85101110/214800154-fb0f9c7b-851a-4051-9ff0-7ddd81a91c04.png">

**Comment by intitni** [comment]
It was included in the previous release. And the version is controlled by Copilot.vim, it may or may not update the Copilot version after each release.

**Comment by intitni** [comment]
I mean the 1.8.0 has nothing to do with the Copilot version.

**Comment by MaksimBezdrobnoi** [comment]
Ok, thanks
