### ISSUE TITLE
[Bug]: chat window sluggish/lags

### ISSUE THREAD

**Issue by DatZig** [intitni/CopilotForXcode#202]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

after pasting around 37 lines of code into the chat window the window becomes sluggish/laggy when trying to type into the chat box. 

### How to reproduce the bug.

I found after pasting around 37 lines of code into the chat box and then trying to type or paste more the window becomes sluggish and typing is laggy (character by character). 

### macOS version

13.1

### Xcode version

14.3

### Copilot for Xcode version

0.14.1

**Comment by intitni** [comment]
Released in 0.15.0
