### ISSUE TITLE
[Enhancement]: expandable entry box in chat window and ability to scroll with mouse

### ISSUE THREAD

**Issue by DatZig** [intitni/CopilotForXcode#208]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

in the chat window the input box should be expandable so we can check our input before submitting it, this is helpful when pasting code in and giving context to gpt, but need to verify something or edit something before sending it. Also, would be great to be able to scroll up and down in the input box with the mouse wheel.

**Comment by intitni** [comment]
Actually, I am working on it right now.. Do you think it's large enough?
<img width="535" alt="Screenshot 2023-05-11 at 22 46 47" src="https://github.com/intitni/CopilotForXcode/assets/793147/322f8430-5d0b-4ea4-9cf4-b2fd13785f8a">

**Comment by KieranConlon** [comment]
Could the height of the input box auto size to fit the height of the text, although maybe set a max size?

**Comment by intitni** [comment]
Fitting height of the text is too hard to do because I need to use NSTextView here and I am not familiar to AppKit. `TextField` supports it out of the box but it has performance issue.

**Comment by DatZig** [comment]
sounds great, can't wait to try it... will it let us scroll up and down with the mouse as well?

**Comment by intitni** [comment]
Actually the current implementation is scrollable dynamic height text view.

**Comment by intitni** [comment]
Released in 0.15.0
