### ISSUE TITLE
[Bug]: In dark mode, the icons in the menu bar are difficult to see!

### ISSUE THREAD

**Issue by SNQ-2001** [intitni/CopilotForXcode#215]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

<img width="372" alt="スクリーンショット 2023-05-14 21 20 16" src="https://github.com/intitni/CopilotForXcode/assets/84154073/eeb334e2-5302-434f-b948-f9602269fa7d">

### How to reproduce the bug.

Launch the application

### macOS version

13.3.1

**Comment by intitni** [comment]
\_(:3 」∠)\_

**Comment by intitni** [comment]
Fixed in 0.15.2
