### ISSUE TITLE
[Bug]: If you want to cancel a Codeium sign-in operation, you cannot go back.

### ISSUE THREAD

**Issue by SNQ-2001** [intitni/CopilotForXcode#216]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

If you complete the sign-in, you should be fine, but if you try to cancel the sign-in mid-sign-in and delete the tab, CopilotForXcode will not be able to close completely!

<img width="1012" alt="スクリーンショット 2023-05-14 21 39 41" src="https://github.com/intitni/CopilotForXcode/assets/84154073/e430d16c-0f36-4c3e-a31d-097fd1a5b86c">

If sign-in fails, you will need to close Sheet

### How to reproduce the bug.

1. Service -> Codeium -> Sign In
2. I am redirected to the browser
3. Delete the sign-in tab displayed in the browser
4. I can't operate it anymore!

### macOS version

13.3.1

### Copilot for Xcode version

0.15.1

**Comment by intitni** [comment]
Fixed in 0.15.2
