### ISSUE TITLE
[Bug]: can't run command Accept Suggestion

### ISSUE THREAD

**Issue by TangMonk** [intitni/CopilotForXcode#223]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

<img width="492" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/3498786/e4c29596-f691-47e6-a930-67cc829ab562">

### How to reproduce the bug.

plz check the screen record

https://github.com/intitni/CopilotForXcode/assets/3498786/108b240e-efb5-47a0-9b76-020b81dea370

### macOS version

12.6

### Xcode version

14.2 

### Copilot for Xcode version

0.15.4 

### Node version

v20.0.0

**Comment by intitni** [comment]
It looks like it can't find the command menu in Xcode menubar > Editor > Copilot > Accept Suggestion.

Can you accept the suggestion from the menubar?

Did you turn the source extension on in the System Setting.app?

**Comment by kimujinyogi** [comment]
I have allowed CopilotForXcodeExtensionService.app in my system settings, but the Copilot menu still does not appear in the Xcode Editor menu. It used to appear when I first installed it, but at some point, it stopped. My OS is 12.5.1 and I'm using Xcode 14.2.

**Comment by intitni** [comment]
@kimujinyogi You have to enable the `Copilot` extension for Xcode in the system settings too. If `Copilot` is not available in the extension settings, please try https://github.com/intitni/CopilotForXcode/issues/42

**Comment by kimujinyogi** [comment]
1. Reboot macOS,
2. Run 'brew reinstall ~~',
3. Sign out from Copilot and sign in again.

It's fixed now... thankyou!!!

**Comment by higekick** [comment]
I needed to check the box below to work suggestion ! Please check it !

<img width="450" alt="スクリーンショット 2023-06-01 16 59 58" src="https://github.com/intitni/CopilotForXcode/assets/7069618/6b686c9d-049c-4e01-a9b6-fba9c04a766d">
