### ISSUE TITLE
The Operation couldn't be completed.(LaunchServicesProtocol.ServerError error 13.)

### ISSUE THREAD

**Issue by fengchuanxiang** [intitni/CopilotForXcode#225]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

Can not signin GitHub Copilot. I get the following error:
The Operation couldn't be completed.(LaunchServicesProtocol.ServerError error 13.)
or
The Operation couldn't be completed.(LaunchServicesProtocol.ServerError error 8.)

**Comment by intitni** [comment]
Usually, it means the language server failed to connect to the GitHub server. Please check your hosts file and remove any entry about GitHub.

**Comment by fengchuanxiang** [comment]
> Usually, it means the language server failed to connect to the GitHub server. Please check your hosts file and remove any entry about GitHub.

When I Click "Sign In", I'm not be directed to a verification website provided by GitHub, I just get the error.

**Comment by intitni** [comment]
When you click sign in, the language server will contact the GitHub server to generate the verification code you need to sign-in. Please check if your hosts file contains anything related to GitHub. Remove them and try again.

**Comment by intitni** [comment]
Please try to use it behind a proxy, and use enhanced mode if possible

**Comment by fengchuanxiang** [comment]
> Please try to use it behind a proxy, and use enhanced mode if possible

Thanks for your reply.
I've try to use it behind a proxy, but still get the error.

**Comment by felipecp** [comment]
Did you install Node? I had the same issue but after installing Node it worked.
I installed directly from Node website at the documentation (https://nodejs.org/en)

**Comment by fengchuanxiang** [comment]
> 



> Did you install Node? I had the same issue but after installing Node it worked. I installed directly from Node website at the documentation (https://nodejs.org/en)

Thanks for your reply.
I installed node using Homebrew. I select Run Node with /bin/bash -i -I, it worked.

**Comment by esonwork** [comment]
> 

Thanks for your reply.

**Comment by Litt1er** [comment]
i meet the same error

**Comment by intitni** [comment]
@Litt1er Please check the [FAQ](https://github.com/intitni/CopilotForXcode/wiki/Frequently-Asked-Questions#github-copilot) to see if there is a solution for you. If the issue still exists, open a new issue with more information.
