### ISSUE TITLE
[Help Wanted]: Xcode plugin gives exteremely poor suggestions in comparison to VSCode. What am  I doing wrong?

### ISSUE THREAD

**Issue by eldare** [intitni/CopilotForXcode#226]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I'm struggling to make copilot in the xcode plugin to produce useful results.
It doesn't provide code suggestions from comments, and the overall quality of the copilot suggested results seems extremely poor when compared to the suggestions in VSCode on the same thing.

I feel like I'm doing something wrong. Please assist.

Suggestion in Xcode. A poor suggestion with broken code.
And more often it suggests comments and opening function blocks with `{`.
<img width="1281" alt="Screenshot 2023-05-23 at 21 58 52" src="https://github.com/intitni/CopilotForXcode/assets/40336237/80e36a28-6f12-4429-8cd7-365d64bcb85e">

Suggestion in VSCode. Exactly what I needed:
<img width="593" alt="Screenshot 2023-05-23 at 21 59 25" src="https://github.com/intitni/CopilotForXcode/assets/40336237/836bf6a9-5b06-44dc-9719-e1d6aaffe757">

**Comment by intitni** [comment]
1. Generating code with comment
Try to give it more hints that the next line is code. For example, 
- add an empty line after the comment:
  ```swift
  // do something
  
  // cursor here
  ```
- instruct it to generate code
  ```swift
  // a function to do something
  // cursor here
  ```
  or
  ```swift
  // do something
  func// cursor here
  ```

2. Broken code
  Currently, GitHub Copilot has the ability to generate suggestions based on the opened files in the same workspace. In order for GitHub Copilot to detect an opened file, language server notifications need to be sent to the language server when a file is opened.  It sounds simple, but Copilot for Xcode can't get those notifications from Xcode. As a result, it can only detect that a file is opened when the user **manually switches to the tab of the file and clicks into the file** (to change focused element, if you are opening a file from the side bar) for the first time.
  Additionally, if a file is already open prior to the extension launch, the user will also need to switch to the file manually in order for it to recognize that it is open.

**Comment by eldare** [comment]
Thank you for the quick response, it's very helpful indeed.

If I understand correctly number 2, if I work on something that depends on 10 other files, and I open all those files, that should be enough to improve copilot results?

**Comment by intitni** [comment]
Theoretically, yes, but sometimes even with the other files opened, GitHub Copilot can [still generate incorrect suggestions even in VSCode](https://github.com/intitni/CopilotForXcode/issues/193#issuecomment-1534908000).

**Comment by eldare** [comment]
Thank you 🙏
