### ISSUE TITLE
Chat - Add a default system prompt 

### ISSUE THREAD

**Issue by haroun-hajem** [intitni/CopilotForXcode#234]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Every model has a default _System Prompt_ from OpenAI. The extension should allow us to set our own _System Prompt_t, e.g. "The user is an IOS developer and will ask you about ... " 

Here is a screenshot from my own implementation of a OpenAI's model: 
![image](https://github.com/intitni/CopilotForXcode/assets/91464438/aab5128f-6a4a-41b2-b286-9e88361431ce)

**Comment by intitni** [comment]
You can use custom command - custom chat to overwrite the system prompt. Or use custom command - open chat to add additional instructions to the default system prompt.

**Comment by intitni** [comment]
Released in 0.18.0
