### ISSUE TITLE
[Bug]: Server error 10

### ISSUE THREAD

**Issue by YevgenStarikov** [intitni/CopilotForXcode#235]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

Endless error "Server error 10", and status loading.. (screenshot)
Service doesn't work!
![Screenshot 2023-05-26 at 10 13 17 AM](https://github.com/intitni/CopilotForXcode/assets/124806754/949549ce-3e4a-480f-b6ab-a158cf130527)

### How to reproduce the bug.

Just open Service tab and press "refresh"

### Relevant log output

```shell
Server error 10
```

### macOS version

Ventura 13.3.1

### Xcode version

14.3

### Copilot for Xcode version

0.17.0

### Node version

11.6.0

**Comment by intitni** [comment]
As it is written in the FAQ:

> Q: Host app shows Server unavailable, please make sure you have installed Node, or GitHub Copilot not working.
>
> ...
>
> If you are using Node version v16.13.x or anything lower, consider updating to a newer version of Node.

Please update your Node to a newer version.

**Comment by intitni** [comment]
@josefrichter The path contains the word shims, so it's probably not pointing to a real node executable. Please change the path to point to a real node executable, or change the run node with other options. 

You can find more details about how to do it with nodenv in FAQ, I believe it will work for asdf, too.

**Comment by josefrichter** [comment]
@intitni thank you for lightning fast solution!

The path to node executable when using ASDF is

`/Users/<username>/.asdf/installs/nodejs/<version>/bin/node`

With this path it works

**Comment by piroworkz** [comment]
had same problem , installed node with hombrew , input path returned by which node, still getting error , left the "Path to node" field empty and suddenly it worked.

**Comment by marcingalus** [comment]
Tried all of the above suggestions, still getting this error...

**Comment by intitni** [comment]
@marcingalus Please try
Q: Host app shows Server unavailable, please make sure you have installed Node, or GitHub Copilot not working.
Q: Host app shows timeout when signing in to GitHub Copilot.

from the FAQ #65

**Comment by marcingalus** [comment]
![Screenshot 2023-07-24 at 10 16 44](https://github.com/intitni/CopilotForXcode/assets/41484767/28070206-4a39-4dd0-99cd-fec0e8a982f7)
![Screenshot 2023-07-24 at 10 16 53](https://github.com/intitni/CopilotForXcode/assets/41484767/e5a96e95-eb0f-40f8-b9a7-5228911398d8)
![Screenshot 2023-07-24 at 10 17 13](https://github.com/intitni/CopilotForXcode/assets/41484767/50ae0838-5d6b-4a51-af2a-e65313ff1f79)

**Comment by intitni** [comment]
@marcingalus As mentioned in the FAQ, the Node version should be greater than 16.
