### ISSUE TITLE
[Enhancement]: Add GitHub Copilot X Chat Support

### ISSUE THREAD

**Issue by Awesomeplayer165** [intitni/CopilotForXcode#236]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Since GitHub Copilot X supports OpenAI’s `GPT-4`, I was wondering if chat support could be added through this? Thank you!

**Comment by intitni** [comment]
GitHub Copilot X Chat does not provide a public API. So, no.
