### ISSUE TITLE
[Bug]: Flashing red cancelled box

### ISSUE THREAD

**Issue by ICULikeMac** [intitni/CopilotForXcode#237]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

Whilst using codeium suggestions and typing a red box appears with cancelled in it. Suggestions do appear correctly after I stop typing but the red box is present (flashing effect) whenever typing.

<img width="615" alt="Screenshot 2023-05-31 at 9 46 53 am" src="https://github.com/intitni/CopilotForXcode/assets/36715486/965873c9-9320-4978-b522-949d3be9098b">

### How to reproduce the bug.

Select Codeium as a suggestion provider, with 0 debounce and start typing, particularly during comments. The open xcode file was a objc file which may/may not be relevant. 

### macOS version

13.4

### Xcode version

14.3

### Copilot for Xcode version

17

### Node version

NA

**Comment by intitni** [comment]
Thanks for reporting, the fix is released in 0.17.1.

**Comment by ICULikeMac** [comment]
Updated already - amazing, thank you so much!
