### ISSUE TITLE
[Enhancement]: Please revert back option chat with selection. It is not clear how to use in new UI.

### ISSUE THREAD

**Issue by EugeneEl** [intitni/CopilotForXcode#239]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Thank you for amazing tool.
Could you please consider reverting back option "chat with selection"? 
So I can select specific code and have a chat with Copilot. 
It is not clear from new UI how to use it. I updated to 0.17.0 and this cool feature has been disappeared.

**Comment by intitni** [comment]
All you need is to select the code and ask about it in the chat. 

The chat will look for the selected code automatically.

**Comment by intitni** [comment]
Please let me know if you still prefer the old behavior. Kindly share your use case if you do. 

I am not planning to return to using the “chat with selection” command but it would be reasonable to incorporate a "send selection to chat" feature.

**Comment by EugeneEl** [comment]
Thank you for your reply. Personally I would prefer old behavior, but you knows better from the other users feedback.
