### ISSUE TITLE
[Enhancement]: How can I set networkProxy for Copilot agent in CopilotForXCode?

### ISSUE THREAD

**Issue by fellowming** [intitni/CopilotForXcode#245]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Hello, I would like to request a feature for CopilotForXCode networkProxy  settings. In my work environment, I need to use an http proxy to access Github Copilot smoothly. However, after searching for information, I was unable to find any options for configuring network proxies in CopilotForXCode.

I have also noticed that Copilot.vim supports setting network proxies. Could you please add support for proxy settings in CopilotForXCode as well?

https://github.com/github/copilot.vim/blob/release/doc/copilot.txt
![image](https://github.com/intitni/CopilotForXcode/assets/127200629/c3b8fa8b-a29d-4710-836d-20a4f1ab71ef)

Thank you very much.

**Comment by fellowming** [comment]
Thank you for your response. I am looking forward to the new features being launched soon.

**Comment by intitni** [comment]
Released in 0.18.1
