### ISSUE TITLE
[Bug]: Operation Couldn't be completed

### ISSUE THREAD

**Issue by H4MST3R3N3RGYBALL** [intitni/CopilotForXcode#251]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I am expecting it to install and not have issues relating to it not showing up as installed.

### How to reproduce the bug.

Any time I restart the app it just shows the following 
<img width="387" alt="Screenshot 2023-06-09 at 1 10 42 AM" src="https://github.com/intitni/CopilotForXcode/assets/53465855/29eca8a8-7411-4777-9364-00bf4830a542">
<img width="537" alt="Screenshot 2023-06-09 at 1 10 49 AM" src="https://github.com/intitni/CopilotForXcode/assets/53465855/79ef94e7-e7cf-4a70-841a-f6f1a488b333">

### Relevant log output

```shell
N/A
```

### macOS version

14.0

### Xcode version

15.0

### Copilot for Xcode version

0.18

### Node version

18.13

**Comment by intitni** [comment]
Which of the proposed solutions in the FAQ have you tried?

**Comment by H4MST3R3N3RGYBALL** [comment]
I fixed that by restarting my computer and the application enough times. I’m now getting copilot as Ok. But it seems the extension service version and accessibly permission are now just stuck at loading.. I don’t see anything about this in the FAQ. Any ideas in regard to this?

**Comment by intitni** [comment]
Please have a look at Q: Host app shows Server unavailable, please make sure you have installed Node, or GitHub Copilot not working.

Usually it's caused by incorrect setup of Node.

**Comment by intitni** [comment]
Oh I misread your message. If extension service version and accessibly permission stuck at loading, try 
Q: The extension says it can't connect to the XPC service/helper or the XPC Service version loading never ends.

If you can't see the helper app from the menu bar (The tentacle), that means the Launch Agent is not correctly setup.
