### ISSUE TITLE
[Enhancement]: Can you add support for the github copilot chat function, no need for a chatgtp account？

### ISSUE THREAD

**Issue by arhatcn** [intitni/CopilotForXcode#254]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Can you add support for the github copilot chat function, no need for a chatgtp account。

**Comment by intitni** [comment]
Duplicated to #236.

No. GitHub Copilot X Chat doesn't provide any public API.
