### ISSUE TITLE
[Bug]: Unable to generate suggestion

### ISSUE THREAD

**Issue by Jia199906** [intitni/CopilotForXcode#258]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I installed CopilotForXcode and completed the setup
<img width="900" alt="截圖 2023-06-14 上午11 10 56" src="https://github.com/intitni/CopilotForXcode/assets/136293221/7719cd63-5f8c-4370-8d4c-df6330166b9e">
<img width="458" alt="截圖 2023-06-14 上午11 10 40" src="https://github.com/intitni/CopilotForXcode/assets/136293221/a1750984-2e35-4e2d-a3ac-b0ae86333893">
<img width="432" alt="截圖 2023-06-14 上午11 10 30" src="https://github.com/intitni/CopilotForXcode/assets/136293221/850a92f6-94f1-44e3-92c4-285ffe209c92">

But after I input the culvert I need to generate按下Get Suggestions
He doesn't generate suggestions
<img width="332" alt="截圖 2023-06-14 上午11 12 53" src="https://github.com/intitni/CopilotForXcode/assets/136293221/ea1528dd-ba5c-4f05-8bf1-f6ce843ada6f">

But you can paste the code from prompt to code
<img width="842" alt="截圖 2023-06-14 上午11 20 28" src="https://github.com/intitni/CopilotForXcode/assets/136293221/dcf1a64e-4072-4f1f-b95a-1730b43c5af1">

My macbook pro is m1 
What part is the problem?

### How to reproduce the bug.

It just happens!

### macOS version

13.0

### Xcode version

14.2

### Copilot for Xcode version

0.18.1

**Comment by intitni** [comment]
Please turn on the verbose log from your first screenshot and check the logs from the Console.app. 

You can filter the process with CopilotForXcodeExtensionService to see only logs from the app, and filter subsystem with copilot to see Github Copilot logs. 

It's also possible that Github Copilot was not generating suggestions for the comment. Please try to give it more hints and move the text cursor to an appropriate location and try again. 

You don't need to use the command to generate suggestions if Real-time suggestion is already on. 

Prompt to code uses ChatGPT to generate code, it has nothing to do with GitHub Copilot.

**Comment by Jia199906** [comment]
1.The log has been turned on, but he did not generate
<img width="900" alt="截圖 2023-06-14 下午12 13 15" src="https://github.com/intitni/CopilotForXcode/assets/136293221/5e66e3d2-f9f1-4b84-bc55-c1491f27c063">
<img width="812" alt="截圖 2023-06-14 下午12 16 58" src="https://github.com/intitni/CopilotForXcode/assets/136293221/4b37f0fd-4bf6-444d-aa91-6e7100780b2f">


Where do I need to move the cursor?

**Comment by intitni** [comment]
Try removing the subsystem, I don't remember what the subsystem is for GitHub Copilot.

**Comment by Jia199906** [comment]
是否是這些呢？
<img width="813" alt="截圖 2023-06-14 下午12 22 32" src="https://github.com/intitni/CopilotForXcode/assets/136293221/780f7f9b-b67c-44cb-a4b5-55380e9a5898">

<img width="804" alt="截圖 2023-06-14 下午12 22 49" src="https://github.com/intitni/CopilotForXcode/assets/136293221/41df1ae3-07d7-4b16-8905-1b60618f2604">

**Comment by intitni** [comment]
不是，你就一直在 Xcode 里打字让它不停触发请求

**Comment by Jia199906** [comment]
<img width="806" alt="截圖 2023-06-14 下午12 27 45" src="https://github.com/intitni/CopilotForXcode/assets/136293221/b91682dc-5a2b-4c66-be98-4773ae08f267">

**Comment by intitni** [comment]
也不是啊，你把 Feature - Suggestion 的设置截图我看看？

**Comment by intitni** [comment]
还有 Node 的版本号也提供一下

**Comment by intitni** [comment]
因为没看到相关截图问一下，Accessibility API 权限给了没有？

**Comment by Jia199906** [comment]
<img width="460" alt="截圖 2023-06-14 上午11 10 14" src="https://github.com/intitni/CopilotForXcode/assets/136293221/3156de2a-efd9-4a17-9394-8a85b7f57179">

Node v18.16.0

<img width="900" alt="截圖 2023-06-14 下午12 45 24" src="https://github.com/intitni/CopilotForXcode/assets/136293221/8c89c8b2-6a8b-46d6-8962-3bae652ce6b0">

**Comment by Jia199906** [comment]
兄弟感謝您協助，由於我將點腦脊Xcode14.2整個重啟後，他正常工作了。

**Comment by intitni** [comment]
果然还是重启最有效啊

**Comment by Jia199906** [comment]
當我新增新的頁面及新的程式碼頁面
在ViewController2.swift他又無法正常運作了
我已嘗試重啟
但是他在新頁面無法正常的給出建議
回到舊的ViewController
相同的提示他可以給出建議

**Comment by intitni** [comment]
<img width="405" alt="Screenshot 2023-06-14 at 14 39 42" src="https://github.com/intitni/CopilotForXcode/assets/793147/2d54528c-efda-435c-8fce-a9c5c33e07df">

请按照这个去筛选 log

**Comment by intitni** [comment]
<img width="365" alt="Screenshot 2023-06-14 at 14 40 52" src="https://github.com/intitni/CopilotForXcode/assets/793147/17a1b953-beed-48fd-becb-832edea9ea67">

另外在 real-time suggestion 触发时应该能看到这个 log

**Comment by Jia199906** [comment]
我一樣沒有找到上面的Log，但我嘗試在其他多頁面得專案以及新開的專案中新增多頁面皆無法複製出相同錯誤
因此我先關閉此問題了
