### ISSUE TITLE
[Enhancement]: Correct name for Launch item

### ISSUE THREAD

**Issue by transat** [intitni/CopilotForXcode#266]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

This extension uses a launch item. Would you be able to re-name it so that I know what application it belongs to? I was looking through my launch items recently and found one called "Shangxin Xuo" which looked odd until I realised it belongs to this extension. Giving it the same name as the app/extension would make it easier for people to keep track of what's what on the system.

**Comment by intitni** [comment]
I have update the launch agent template to contain `AssociatedBundleIdentifiers` and will release it soon. But a better way is to use `SMAppService`, I will leave it for a future update. This issue will be marked as low-priority to serve as a reminder.

**Comment by intitni** [comment]
Released in 0.21.0
