### ISSUE TITLE
[Bug]: CopilotForXcodeExtensionService in Mission Control

### ISSUE THREAD

**Issue by GkFoxes** [intitni/CopilotForXcode#269]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

When Copilot for Xcode work I see CopilotForXcodeExtensionService in Mission Control on every Desktop on macOS (screenshot). Can we hide it from Mission Control and work at the same time?
<img width="345" alt="Screenshot 2023-06-22 at 12 31 46" src="https://github.com/intitni/CopilotForXcode/assets/26763098/9dcdc82d-e3ef-4bd1-87fd-43ec81f01b80">

### How to reproduce the bug.

Open Copilot for Xcode

### macOS version

13.4.1

### Xcode version

14.3.1

### Copilot for Xcode version

0.18.2

**Comment by intitni** [comment]
I am not sure if the pull request fixes the bug. What I observed was that when I switch spaces in mission control, the Copilot for Xcode widgets will be brought to the front. Is that what you experienced?

**Comment by GkFoxes** [comment]
Not exactly. I have this Service constantly hanging in Mission Control, on any of the Desktop Screens. I can't somehow tap on it or hide it, it's just everywhere if Copilot works. In CMND + Tab menu I didn't see that this app is Run

**Comment by intitni** [comment]
Released in 0.19.0
