### ISSUE TITLE
"Cannot find helper application"

### ISSUE THREAD

**Issue by ICULikeMac** [intitni/CopilotForXcode#27]
I have used `mdfind` in terminal to remove all instances of the app then reinstalled with brew and cannot seem to get xcode to find the helper application. 

I get no errors under 'Copilot' in the app. The XPCService Version is listed and the status reads OK. I can also see the service running as per F.A.Q.

Any other suggestions? 

Note: Somewhere it's remembering I've had the app installed previously as Input Monitoring remains selected, so this could be related. i.e Xcode is looking for another helper? Maybe?

Thank you in advance for your assistance and for all your work making this possible.

**Comment by intitni** [comment]
That’s weird. 

What are the commands available in Xcode? Do you see

- Toggle real-time suggestions

Or 

- Turn on real-time suggestions for workspace
- Turn off…

**Comment by ICULikeMac** [comment]
Yeah very odd! - Thanks for your help.

I seem to have all options available in xcode?

<img width="690" alt="Screenshot 2023-02-15 at 12 25 12 pm" src="https://user-images.githubusercontent.com/36715486/218907517-071f5af4-7dc0-4463-a97d-811c7ed3c573.png">

**Comment by intitni** [comment]
Great. The latest version 0.7.0 has replaced the two turn on/off commands with one single toggle command. That means Xcode is running another version of the extension. 

Please look for Copilot in Activity Monitor.app, double-click one of them (I guess two Copilot are running), and choose the open files and ports tab to locate the wanted one.

**Comment by intitni** [comment]
It doesn't matter if there is only one running, please try to locate it by double-clicking it.

**Comment by ICULikeMac** [comment]
Found it! It was related to having AppCode installed 🤷🏼‍♂️ Anyway thanks so much for your help and I said before more thanks for creating this tool!
