### ISSUE TITLE
The software needs to support objective-c language

### ISSUE THREAD

**Issue by zhongTom** [intitni/CopilotForXcode#283]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

My project is developed in objective-c language, and I also want to use CopilotForXcode, can your software support objective-c language?

**Comment by intitni** [comment]
The app itself supports Objective-C, but I am not sure how well the language is supported by GitHub Copilot and Codeium, However, feel free to give it a try. To the best of my recollection, they do generate suggestions for Objective-C.
