### ISSUE TITLE
[Enhancement]: Command to open current file in VSCode

### ISSUE THREAD

**Issue by imWildCat** [intitni/CopilotForXcode#286]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

I want a feature that we can open the current file in VSCode quickly to use other Copilot features like Chat or Labs.

Are you open to this idea? If so, I can start a PR

**Comment by intitni** [comment]
I understand that GitHub Copilot users may prefer to use GitHub Copilot Chat, but I am not feeling very comfortable with adding a dedicated command to allow open files in VSCode. To make it feel better for me, I propose supporting running commands silently with the `/run` chat plugin. #287 

<img width="966" alt="Screenshot 2023-07-03 at 15 40 24" src="https://github.com/intitni/CopilotForXcode/assets/793147/60c931d9-9fd8-417d-ba0f-73fb01b8f0ae">

This custom command will open the file in VSCode and the chat panel will not open. It can be used in other situations, too.

**Comment by intitni** [comment]
I think we can simply add a new type of custom command that creates a one-time conversation that replies with notifications or no reply at all.

**Comment by imWildCat** [comment]
GitHub also offers other features like https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-labs


I really hope that we have such a command.

**Comment by intitni** [comment]
I am aware of the GitHub Copilot lab. The code translation and brushes it provides can be accomplished with the prompt to code feature in the app, just in case anyone is unaware. 

What do you think about my proposed solution? I think it should cover your needs.

**Comment by intitni** [comment]
The new custom command type is released in 0.20.0. You can set the prompt to `/run code $FILE_PATH` to open the current  file in VSCode.

**Comment by imWildCat** [comment]
> The new custom command type is released in 0.20.0. You can set the prompt to `/run code $FILE_PATH` to open the current file in VSCode.

Whoa! Thanks a lot!

**Comment by imWildCat** [comment]
Sorry, could you give me a screenshot? This does not seem to work

![Uploading image.png…]()

**Comment by KieranConlon** [comment]
This works for me.

I tried using `code`, but on my Mac that opened VSCode on my Ubuntu VM instead of locally on macOS; so using the exact app name worked for me.

<img width="1012" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/33759139/2c9ae287-3c78-4c9f-861c-26197c7f9f4a">
