### ISSUE TITLE
[Bug]: Cannot use this tool alongside neovim

### ISSUE THREAD

**Issue by rsarv3006** [intitni/CopilotForXcode#289]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I'm prefacing this with two things. First off thank you for taking the time to build this plug in. It's amazing and has sped up my xcode development so much. 

Second, I don't even know if this is fixable so this may just need to be added as an FYI in the FAQs. This "solution" is totally acceptable to me I just wanted to bring it up in case I'm missing something or I've misconfigured something.

On to the issue at hand. I've been using this Copilot plugin for a while and it works great. I even used the Emacs port of the vim plugin similar to what this plugin does. I recently decided to take Neovim for a spin to see what I thought and I ran into a glaring issue. If the CopilotForXcode app is running and the plugin working I can get copilot suggestions in XCode but not in NeoVim. If I quit the Copilot For Xcode app it starts working again. 

Like I said I don't know if this is fixable or if I've misconfigured something because the Emacs plugin worked with CopilotForXCode running but it's a port so it might be doing things differently.

### How to reproduce the bug.

1. Make sure neovim is installed and Copilot is installed using Packer.
2.  Quit out of neovim.
3. Open Copilot for Xcode and Xcode - suggestions should work
4. Reopen neovim, no suggestions.

I've also seen the reverse if I have xcode and copilotforxcode closed and neovim running. If I then open Xcode and copilot suggestions won't work in CopilotForXcode

Like I previously mentioned this could totally be a me issue but on the off chance it's not I wanted to call it out potentially.

Thanks again for taking the time to build this tool!

### macOS version

13.1

### Xcode version

14.3.1

### Copilot for Xcode version

0.19.2

### Node version

v16.19.0

**Comment by intitni** [comment]
Thanks for the report, but I am unable to reproduce the bug. I am currently using Neovim 0.9.1, which was installed via brew. However, I cannot recall how Copilot.vim was installed.

In both Copilot for Xcode and Copilot.vim, a new instance of node will be created to run the language server. The application communicates with this instance through stdin/stdout, so it is unlikely that they would interfere with each other.

Would you like to try again, but with a more recent version of Node?

**Comment by rsarv3006** [comment]
Closing this, it's definitely an issue with my neovim config, I just tried it on a mac without copilot for xcode installed and it's still no working. Sorry to bother and thanks again for the awesome plugin!
