### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by swiatrzyk** [intitni/CopilotForXcode#29]
<img width="1012" alt="Screenshot 2023-02-20 at 11 08 09" src="https://user-images.githubusercontent.com/28967717/220384065-21f223d7-e9eb-451f-8311-ea62a565338c.png">

I have installed node v19.6.1. I have tried to reinstall this app via brew cask, and manual installation and I still have this error. Refresh button does nothing

**Comment by intitni** [comment]
Please run `which node` in terminal to get the path to node.

**Comment by swiatrzyk** [comment]
`which node`
`/opt/homebrew/bin/node`

also
`npm config get prefix`
`/usr/local`

**Comment by intitni** [comment]
You need to paste it to the "Path to Node" text field

**Comment by swiatrzyk** [comment]
Thank you, it solved the issue 🙂
