### ISSUE TITLE
[Bug]: Accept Button does not work !!

### ISSUE THREAD

**Issue by dipcse07** [intitni/CopilotForXcode#290]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I am using Xcode Version 14.3 (14E222b) and installed the extension. When I write code it suggests codes but when try to add those code clicking accept button the Xcode View Refreshes but the code does not get imported ..
![Screenshot 2023-07-06 at 18 03 48](https://github.com/intitni/CopilotForXcode/assets/19185636/8c00f4c1-3253-4f27-a515-7047cf67c35a)

### How to reproduce the bug.

1. Add the extension to Xcode 14 properly
2. Start to write code and it will suggest codes . Try to accept and then this problem will occur. 

### macOS version

Version 13.4.1 (22F82)

### Xcode version

14.3 (14E222b)

### Copilot for Xcode version

Copilot.Vim Version 1.8.4

### Node version

v18.16.1

**Comment by intitni** [comment]
If you have just updated Copilot for Xcode, there is a chance that the Copilot menu in Xcode will stop working. Restarting Xcode should fix that. 

If it's not fixed, you can try turning on Always accept suggestions with Accessibility API in advanced settings if you are sure that the app is correctly setup.

**Comment by dipcse07** [comment]
Okay After restart the Xcode That worked !!! Thank you Very Much !!
