### ISSUE TITLE
[Help Wanted]: Couldn't communicate with a helper application.

### ISSUE THREAD

**Issue by Maxwin-z** [intitni/CopilotForXcode#292]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

Xcode: Version 14.3.1 (14E300c)
Copilot for Xcode: Version 0.19.2 (192)
NodeJS: v18.16.0

It seems the error occurs after Xcode update to 14.3 a fews days ago.
I update/reinstall the Copilot for Xcode, still error.

The system setting as shown:
<img width="900" alt="Pasted Graphic" src="https://github.com/intitni/CopilotForXcode/assets/1728633/f6048fd0-e5bd-4a69-a827-73e35bbd7a91">

<img width="475" alt="Pasted Graphic 4" src="https://github.com/intitni/CopilotForXcode/assets/1728633/07be0954-df68-41ca-8fba-03cea9b2bdcf">

<img width="505" alt="Pasted Graphic 3" src="https://github.com/intitni/CopilotForXcode/assets/1728633/47a0abb3-aaa3-40b0-826b-9cfd857756a7">

Thanks.

**Comment by Maxwin-z** [comment]
Just Click the "Set Up Launch Agent". Done.

**Comment by rodrigo-rdc** [comment]
I am facing this issue and clicking that button doesn't work for me

**Comment by davidgaag** [comment]
Same here in 0.20.1

**Comment by CivelXu** [comment]
I face the same problem. There is no solution.

**Comment by intitni** [comment]
@CivelXu Please try [this section](https://github.com/intitni/CopilotForXcode/wiki/Frequently-Asked-Questions#q-the-extension-says-it-cant-connect-to-the-xpc-servicehelper-or-the-xpc-service-version-loading-never-ends) in FAQ

Open a new issue if it's still not working.
