### ISSUE TITLE
[Help Wanted]: runing project in debug config

### ISSUE THREAD

**Issue by jonz-tech** [intitni/CopilotForXcode#293]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

recently, i run the source project in debug mode. i always change bundle id by my personal team
i have install my node version by brew , and version is 
```
node -v
v20.3.1
```
=================
in HostApp general view:
![image](https://github.com/intitni/CopilotForXcode/assets/6789118/df76edfd-43f8-478c-8532-01be8119d2b9)

in service view:
![image](https://github.com/intitni/CopilotForXcode/assets/6789118/7d687a75-0199-4756-887e-812540deb087)

but i still cannot install my Language Severice and i can not found agent.js in my Application suport/copilot path

please help find the reason

**Comment by intitni** [comment]
The install location is defined in Config.xcconfig APPLICATION_SUPPORT_FOLDER

**Comment by jonz-tech** [comment]
I debug the code and found that in my project  suportURL path1 is: file:///var/root/Library/Application%20Support/com.xxx.abc.CopilotForXcode/GitHub%20Copilot/
seems that it install in root User Library path but some service find language server in the path2 is: 
~/Library/Application%20Support/com.xxx.abc.CopilotForXcode/GitHub%20Copilot/

path1 and path2 is diffent path , may be this is a bug?

**Comment by intitni** [comment]
The path is fetched in `userDomainMask`, if you are running the app as root, the path will become path1. Did you change the scheme settings to debug process as root?

**Comment by jonz-tech** [comment]
> The path is fetched in `userDomainMask`, if you are running the app as root, the path will become path1. Did you change the scheme settings to debug process as root?

yes. i use my personal Team account to set a new bundle id and try to  run the project. 
my project is in /Users/username/path/ 

just as you mentioned: host app get the path1, but when i breakpoint at  ExtensionService target , it return path2 ,

**Comment by intitni** [comment]
None of the targets should be run as root. Please check your settings to ensure they are running as your logged-in user.

**Comment by jonz-tech** [comment]
i do not know why  it run as root. 
but my root accout is also my logged-in user

**Comment by jonz-tech** [comment]
problem solved, thx for your help~
one of my workmate change project  edit scheme debug process as root, which make two target get different path 
![image](https://github.com/intitni/CopilotForXcode/assets/6789118/6c0a6ead-3cea-4d8c-9c3e-eb70b26b3229)

**Comment by jonz-tech** [comment]
one more err: Error on ghost text request FetchError: getaddrinfo ENOTFOUND copilot-proxy.githubusercontent.com
any idea for this error?

**Comment by jonz-tech** [comment]
![image](https://github.com/intitni/CopilotForXcode/assets/6789118/10b37e8f-f4c6-462f-b20e-283c043d3ce9)
can you tell me, after the query respone  where is the entry point to triger this GUI.
