### ISSUE TITLE
Real-time suggestion not working unless I reduce the debounce time

### ISSUE THREAD

**Issue by haifengkao** [intitni/CopilotForXcode#30]
If I turn on `Real-time suggestion` in `Copilot for Xcode` and switch to `Xcode`,
the `Real-time suggestion` will be turned off automatically.

After I reduce the `fetch debounce` time to 0.2s, the `Real-time suggestion` won't be turned off automatically anymore.

Weird.

**Comment by intitni** [comment]
It appears the app is not correctly displaying the settings as it should. When the menu bar app is started, the toggle in the host app would be reset even though the feature should remain turned on.

**Comment by intitni** [comment]
Fixed in 0.8.1
