### ISSUE TITLE
[Help Wanted]:  The Copilot for Xcode project compile error

### ISSUE THREAD

**Issue by alexlee002** [intitni/CopilotForXcode#300]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

![image](https://github.com/intitni/CopilotForXcode/assets/576164/f7341467-4283-4cd4-b293-e045a5fd946e)

![image](https://github.com/intitni/CopilotForXcode/assets/576164/b53732e3-f034-4c5b-b33f-2c1d0f483ea4)

**Comment by intitni** [comment]
I will submit an update to remove the Python package later, for now, you can simply remove the package from the project.

**Comment by intitni** [comment]
The repo is updated
