### ISSUE TITLE
[Help Wanted]: Suggestion window doesn't show

### ISSUE THREAD

**Issue by rodrigo-rdc** [intitni/CopilotForXcode#303]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I need help!

Xcode: `14.3.1`
CopilotForXcode: `0.20.0`
Node: `18.16.1`

I can see Copilot in the Editor menu on Xcode, but none of the options do anything.
The suggestion window is not on the screen. Nothing happens; what am I missing here?

<img width="888" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/106767028/3c14bc52-2776-439d-bdcf-f16e07fb6a24">
<img width="888" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/106767028/fd214024-e6bc-4e93-8bb1-a050548a9a75">

**Comment by intitni** [comment]
The launch agent is not correctly setup, please check FAQ for details

**Comment by rodrigo-rdc** [comment]
The file wasn't created. I needed to do it manually. It is working now, thanks!
