### ISSUE TITLE
[Enhancement]: Hide Floating Widget Funciton

### ISSUE THREAD

**Issue by Dark-Existed** [intitni/CopilotForXcode#307]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Hi, any way to hide the floating widget, for me, I prefer hiden it and use the shortcuts to activate the function.
Could add a option to hide it ? thx.

**Comment by MrMage** [comment]
As an alternative, would it be possible to show the widget only when it is fetching suggestions from Copilot, as a sort of status indicator, but hide it when it has nothing to display? That way, I don't get distracted by the grey blob but still know that Copilot is working.

**Comment by intitni** [comment]
> As an alternative, would it be possible to show the widget only when it is fetching suggestions from Copilot, as a sort of status indicator, but hide it when it has nothing to display? That way, I don't get distracted by the grey blob but still know that Copilot is working.

It will be tracked in another issue #328 

This issue will be closed.
