### ISSUE TITLE
[Enhancement]: Connect to a local LLM instead of an online service

### ISSUE THREAD

**Issue by c0008** [intitni/CopilotForXcode#308]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

LLMs you can run locally are more private and they are getting better and better. It would be useful if there would be the option to connect to a local LLM. LocalAI and FastChat already have an OpenAI compatible API.

https://github.com/go-skynet/LocalAI
https://github.com/lm-sys/FastChat

**Comment by intitni** [comment]
If they have an OpenAI compatible API, you should already be able to use it by changing the OpenAI Base URL to your localhost and ensuring that the model name matches any of the existing models. I haven't tried it, so please let me know if it works.

By the way, do you know if any of them supports function calling?

**Comment by c0008** [comment]
It doesn't work with LocalAI for me. I have edited the hard coded model names, typed in the server ip and clicked on "Test". It does calculate a prediction on the server but the application displays the following error.

![The data couldn't be read because it is missing](https://github.com/intitni/CopilotForXcode/assets/139379535/0a73a8dd-2202-4c0d-9ef9-dce6f069bc4b)

I have tried to trace it down. The function call "JSONDecoder().decode(CompletionResponseBody.self, from: result)" in CompletionAPI.swift is throwing the error but I don't unterstand why.

I can make API-calls from the command line. For example:
curl http://192.168.1.150:8080/v1/completions -H "Content-Type: application/json" -d '{
     "model": "ggml-replit-code-v1-3b",
     "prompt": "-(void)printCurrentTime", 
     "temperature": 0.5
   }'

response:
{"object":"text_completion","model":"ggml-replit-code-v1-3b","choices":[{"index":0,"finish_reason":"stop","text":"-(void)printCurrentTime{\n\n    NSDate *date = [self date];\n    NSLog(@\"%ld\",[date timeIntervalSince1970]);\n\n}"}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}%  



I don't know about support of function calling.

**Comment by intitni** [comment]
You should use a model that supports the chat/completions endpoint.

**Comment by c0008** [comment]
The model "ggml-replit-code-v1-3b" supports /v1/chat/completions just like /v1/completions. I can insert "/chat" into to the curl command above and it works the same.

**Comment by intitni** [comment]
Looks like the id in the response body is missing 

```json
{
  "id": "chatcmpl-123",
  "object": "chat.completion",
  "created": 1677652288,
  "choices": [{
    "index": 0,
    "message": {
      "role": "assistant",
      "content": "\n\nHello there, how may I assist you today?",
    },
    "finish_reason": "stop"
  }],
  "usage": {
    "prompt_tokens": 9,
    "completion_tokens": 12,
    "total_tokens": 21
  }
}
```

**Comment by intitni** [comment]
I will change the id to be optional in the next update, but I think we need a better way to import different models in the future.

**Comment by c0008** [comment]
You can get a list of the available models with "/v1/models". This list should be the basis for the model selector. This will be also useful for using chatGPT when models are added or removed in the future.

http://localhost:8080/v1/models
https://api.openai.com/v1/models
