### ISSUE TITLE
[Bug]: {{selected_code}}, {{active_editor_file_url}} and similar template arguments don't work as described

### ISSUE THREAD

**Issue by coolbnjmn** [intitni/CopilotForXcode#309]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I'm trying to use the {{selected_code}} and {{active_editor_file_url}} template arguments, but they are not being replaced by the actual values as expected when I run commands in the chat window. 

Perhaps I'm trying this in an unexpected way?

### How to reproduce the bug.

Open plugin chat window, type "/run echo {{selected_code}}"

Expected output:
- echo of whatever is currently highlighted in my Xcode editor window

Actual output:
{{selected code}}

### Relevant log output

```shell
N/A
```

### macOS version

13.4.1

### Xcode version

14.1

### Copilot for Xcode version

0.20.0(200)

### Node version

16.19.0

**Comment by KieranConlon** [comment]
This works if you set it up as a custom command.

<img width="2029" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/33759139/c3b1166b-3fdb-4e8f-88dd-70d5af42e816">

**Comment by intitni** [comment]
It currently only works for custom commands. Do you think it should be supported for sending messages as well?

**Comment by coolbnjmn** [comment]
Well perhaps my issue is strictly with custom commands then 😅 
I started by trying to use this from a custom command, but I couldn't get that to actually be run. I created a similar test command as what you showed @KieranConlon, closed and re-opened Xcode, but then couldn't figure out how to actually execute it. What exactly did you do in the chat window to execute that command? :)

**Comment by intitni** [comment]
It's available from the Xcode > Editor > Copilot menu and the context menu of the circular widget.

<img width="649" alt="Screenshot 2023-07-21 at 21 37 28" src="https://github.com/intitni/CopilotForXcode/assets/793147/7af5fbe6-1f12-408d-9d16-70febdee37c2">
<img width="746" alt="Screenshot 2023-07-21 at 21 37 22" src="https://github.com/intitni/CopilotForXcode/assets/793147/6ddbdb29-e8f7-4481-8b90-6cf1fa0fe9ef">

**Comment by coolbnjmn** [comment]
Ah nice, got it working, thank you!

I'll close this issue out, I'd suggest making it more clear how to use custom commands, since the steps shared here I was definitely not able to intuit from the material available thus far 👍
