### ISSUE TITLE
[Help Wanted]: The operation couldn't be completed, (LanguageServerProtocol.ServerError error 10.

### ISSUE THREAD

**Issue by Aaslte** [intitni/CopilotForXcode#310]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I want help!

**Comment by Aaslte** [comment]
<img width="900" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/16889972/f4a705f1-87ab-435d-a261-c6e366491956">

**Comment by Aaslte** [comment]
<img width="900" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/16889972/5bd09c98-465d-49a3-a4fc-dd56a064eeea">

**Comment by Aaslte** [comment]
Language Server Version and Status have been in the Loading... state all the time. After clicking the Refresh button, the following error appears: "The operation couldn't be completed, (LanguageServerProtocol.ServerError error 10.)"

**Comment by Aaslte** [comment]
<img width="1007" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/16889972/cda1840a-ec7b-43c9-a114-a56a8be3cb77">

**Comment by intitni** [comment]
Most of the time, you don't need to set the proxy in the app, it will use your system proxy. If you choose to set it in app, the first text field should not contain the scheme.

You can turn on verbose log to see more logs.

Also, please try these 2 QA

### Q: Host app shows Server unavailable, please make sure you have installed Node, or GitHub Copilot not working.

A: Please ensure that the Path to Node correctly points to a valid Node executable. Avoid using ~ in place of /Users/username

If you are using Node version v16 or anything lower, consider updating to a newer version of Node.

If you're using nodenv, use the path that points to a specific version of Node, such as /Users/username/.nodenv/versions/19.8.1/bin/node.

You can also try setting "run node with" to other options.

After making changes, be sure to restart both the host app and the helper app.

If none of the above is working for you, you can observe the logs posted by the language server using the Console.app.

Set up the filter to the process:CopilotForXcodeExtensionService subsystem:com.chimehq.JSONRPC to show only the logs from the language server. See if there is anything you can do.
Set up the filter to process:CopilotForXcodeExtensionService subsystem:com.intii.CopilotForXcode to show only logs from the helper app.

### Q: Host app shows timeout when signing in to GitHub Copilot.

A: The language server seems to be not working correctly. You can observe the logs posted by the language server using the Console.app. Set up the filter to the process CopilotForXcodeExtensionService and subsystem com.chimehq.JSONRPC to show only the logs from the language server. See if there is anything you can do.

**Also, make sure you are not doing any thing in you hosts file about GitHub.**

**Comment by Aaslte** [comment]
> Most of the time, you don't need to set the proxy in the app, it will use your system proxy. If you choose to set it in app, the first text field should not contain the scheme.
> 
> You can turn on verbose log to see more logs.
> 
> Also, please try these 2 QA
> 
> ### Q: Host app shows Server unavailable, please make sure you have installed Node, or GitHub Copilot not working.
> A: Please ensure that the Path to Node correctly points to a valid Node executable. Avoid using ~ in place of /Users/username
> 
> If you are using Node version v16 or anything lower, consider updating to a newer version of Node.
> 
> If you're using nodenv, use the path that points to a specific version of Node, such as /Users/username/.nodenv/versions/19.8.1/bin/node.
> 
> You can also try setting "run node with" to other options.
> 
> After making changes, be sure to restart both the host app and the helper app.
> 
> If none of the above is working for you, you can observe the logs posted by the language server using the Console.app.
> 
> Set up the filter to the process:CopilotForXcodeExtensionService subsystem:com.chimehq.JSONRPC to show only the logs from the language server. See if there is anything you can do. Set up the filter to process:CopilotForXcodeExtensionService subsystem:com.intii.CopilotForXcode to show only logs from the helper app.
> 
> ### Q: Host app shows timeout when signing in to GitHub Copilot.
> A: The language server seems to be not working correctly. You can observe the logs posted by the language server using the Console.app. Set up the filter to the process CopilotForXcodeExtensionService and subsystem com.chimehq.JSONRPC to show only the logs from the language server. See if there is anything you can do.
> 
> **Also, make sure you are not doing any thing in you hosts file about GitHub.**

Okay, it's been resolved. The reason was that the Node version was too low. Thank you very much for the reminder.

**Comment by paulz** [comment]
had this issue while using node installed via ASDF(https://asdf-vm.com) 
fixed by switching to use homebrew `brew install nodejs`
now my node path is `/opt/homebrew/Cellar/node/20.8.0/bin/node`
