### ISSUE TITLE
[Help Wanted]: "You exceeded your current quota, please check your plan and billing details."

### ISSUE THREAD

**Issue by Epoch2022-iOS** [intitni/CopilotForXcode#314]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I want help!
When I setup Copilot for Xcode, Choose Service -> OpenAI, fill the OpenAI API Key and Choose ChatGPT Model **gpt-3.5-turbo**, then click Test Button, Copilot for Xcode show me a error: `You exceeded your current quota, please check your plan and billing details.`.

After logging into OpenAI, I checked Billing usage, and the background showed that I had enough unused.

Please help me solve this problem

**Comment by Epoch2022-iOS** [comment]
<img width="1008" alt="截屏2023-07-25 11 57 20" src="https://github.com/intitni/CopilotForXcode/assets/24999102/cf764973-58db-4b0f-84c5-fb8a15e73680">

**Comment by Epoch2022-iOS** [comment]
<img width="637" alt="截屏2023-07-25 11 57 05" src="https://github.com/intitni/CopilotForXcode/assets/24999102/c5bfc3c0-b553-4a9d-ae20-eeb6b652d455">

**Comment by intitni** [comment]
The pink bar is annotated as "Expired", and they expired since June 1st.

**Comment by Epoch2022-iOS** [comment]
> The pink bar is annotated as "Expired", and they expired since June 1st.

I changed my payment method and customized the API payment plan, and it is still not available.

According to the description of the url, https://help.openai.com/en/articles/ 7102672 - how can - I - access - GPT - 4. "I need to consume at least $1, I should how to consume, because I can't use now.
<img width="946" alt="截屏2023-07-26 09 46 23" src="https://github.com/intitni/CopilotForXcode/assets/24999102/b5a641f4-e32d-4de5-9ef6-cab16119dacd">

<img width="937" alt="截屏2023-07-26 09 46 14" src="https://github.com/intitni/CopilotForXcode/assets/24999102/586bd9a3-00df-4413-a2b8-929bb1f83ee6">

**Comment by intitni** [comment]
You will need to ask OpenAI about that.

**Comment by Epoch2022-iOS** [comment]
> You will need to ask OpenAI about that.

thanks.

**Comment by Epoch2022-iOS** [comment]
> You will need to ask OpenAI about that.

**I configured this GitHub Copilot, do I still need to configure OpenAI？**

<img width="927" alt="截屏2023-07-26 10 24 03" src="https://github.com/intitni/CopilotForXcode/assets/24999102/b9716e8b-816a-40a9-8e97-da5371d2ccb0">

**Comment by intitni** [comment]
If you want to use the chat and prompt to code feature, you will need to setup the OpenAI API key

**Comment by 0xZeyn** [comment]
> > You will need to ask OpenAI about that.
> 
> **I configured this GitHub Copilot, do I still need to configure OpenAI？**
> <img alt="截屏2023-07-26 10 24 03" width="927" src="https://user-images.githubusercontent.com/24999102/256089559-b9716e8b-816a-40a9-8e97-da5371d2ccb0.png">

hey, have you finded any solution ?? I have the same problem

**Comment by 0xZeyn** [comment]
hey @Epoch2022-iOS , have you finded any solution ?? I have the same problem

**Comment by renanmd** [comment]
Having the same issue and still haven't found a solution.

**Comment by intitni** [comment]
@renanmd It's not an issue of Copilot for Xcode, please check your OpenAI API usage on openai.com. You may have run out of free quota, and have to add credits or payment methods to your account to continue using the API. 

If you have subscribed to ChatGPT Plus, please note that it and the API are different services using different billing systems.
