### ISSUE TITLE
[Help Wanted]: Extension is freezing when I'm importing a CoreML model

### ISSUE THREAD

**Issue by ipodishima** [intitni/CopilotForXcode#316]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

Hey!

First of all, thank you for the work being done here, really useful. It changed my way of working.
I ran into an issue today: when you import a CoreML model, the app is freezing.
I think it probably tries to process the content of it, and since it's big / contains many data, it's stuck.

Maybe should we ignore those files?

**Comment by intitni** [comment]
What it size of the model file?
