### ISSUE TITLE
Consistent CPU usage in the background

### ISSUE THREAD

**Issue by j-f1** [intitni/CopilotForXcode#32]
Hi! I took a peek at Activity Monitor when I hadn’t been using Xcode for several hours and noticed that CopilotForXcodeExtensionService was consistently using ~5% CPU.

Here’s a sample of the process if that helps: [Sample of CopilotForXcodeExtensionService.txt](https://github.com/intitni/CopilotForXcode/files/10840239/Sample.of.CopilotForXcodeExtensionService.txt)
And an Instruments trace: [CopilotForXcode.trace.zip](https://github.com/intitni/CopilotForXcode/files/10840271/CopilotForXcode.trace.zip)

It looks like most of the processing is happening inside SwiftUI but it would be great if there was a way to reduce or eliminate this CPU usage to improve battery life.

**Comment by intitni** [comment]
I noticed that too. A SwiftUI animation is running when the window is not presented. Another performance issue is that the display link was used to update the location of the real-time suggestion indicator, which is just not right.

For the first issue, I think I will just remove the animation. For the second one, AXObserver will be used instead.

**Comment by intitni** [comment]
Fixed in 0.8.1

**Comment by j-f1** [comment]
Confirmed — usage is much lower, and it seems to be zero when Xcode is in the background!
