### ISSUE TITLE
[Help Wanted]: 

### ISSUE THREAD

**Issue by FFFcomewhere** [intitni/CopilotForXcode#334]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I want help!
i use azure openai api for chat. when i enter any message , i  just got " Unrecognized request argument supplied: functions".
i trust my azure openaiapi is working. i search the question by google, i think relate to the "openai.api_version = "2023-07-01-preview". 

message form google : https://github.com/openai/openai-python/issues/517
pc: mac

thank you for replying.

**Comment by intitni** [comment]
I forgot to mention it in the change log, you have to update the model version to 0613 to make it support function calling.

<img width="824" alt="Screenshot 2023-08-14 at 15 07 25" src="https://github.com/intitni/CopilotForXcode/assets/793147/9fd9c55b-27dc-48b7-adfb-c4c19a8a17c8">
