### ISSUE TITLE
[Bug]: Using Azure ChatGPT deployment is broken by functions argument

### ISSUE THREAD

**Issue by Vybo** [intitni/CopilotForXcode#335]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

One of the recent updates broken the Azure ChatGPT functionality. Chat now supplies `functions` argument in its request, which this particular version of the API does not support.

### How to reproduce the bug.

Use Azure ChatGPT deployment that uses the 2023-05-15 API version and then try to use Chat. You'll get this error: "Unrecognized request argument supplied: functions".

### macOS version

13.4.1 (22F82)

### Xcode version

14.3.0

### Copilot for Xcode version

0.21.1

### Node version

v20.0.0

**Comment by intitni** [comment]
Please update your model version to 0613 #334

**Comment by Vybo** [comment]
The model is GPT-4 and I am unfortunately not able to update the model, since it's not managed by me, but the company.

**Comment by intitni** [comment]
I will add a toggle to turn the function calling off later. In the meantime, you can try turning off the default code scope in the chat feature settings, or revert to 0.20.x.
