### ISSUE TITLE
[Help Wanted]: please give a detail guid to develop locally

### ISSUE THREAD

**Issue by jchuai** [intitni/CopilotForXcode#345]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I want help!

HI ,could you please give a detail guid about how to build and debug the app in a local machine. We maintained our own LLM, and we want to try the code copilot with this app. But we have no idea how to build and debug the app, so that we can re-develop it to connect to our own LLM service. 

Thanks

**Comment by intitni** [comment]
If you need to change the chat provider to use your own LLM, you can simply make it conform to OpenAI API format, set the model name to one of the names known by the app (e.g. gpt-3.5-turbo), and change the base URL to point to your own server.

For development instructions, please read DEVELOPMENT.md.

**Comment by jchuai** [comment]
hi，thanks for help!  We decide to follow your suggestion, provide owner own LLM.  However, we are not sure which API format we should conform. Could you please tell us, which OpenAI API you have used in this project? Or you can tell us the code about calling api, so we can list by ourselves. Thanks

**Comment by intitni** [comment]
The chat completion API is used in the app. https://platform.openai.com/docs/api-reference/chat

The settings have changed a lot since the last reply. 
 
You can setup an OpenAI compatible chat model after setting up your own chat completion API. Be sure to turn off the function calling toggle if it's not supported by your model.

**Comment by intitni** [comment]
I checked your question again, if you want to use your LLM as a provider for the suggestion feature, it's not supported yet. 

In the future we may support Tabby to allow using custom LLM to generate suggestion. 

If you want it now, you will have to implement you own SuggestionProvide. Please use CodeiumSuggestionProvider as an example.

**Comment by jchuai** [comment]
OK，thanks intitni. I did want to use the my LLM for suggestion feature instead of chat feature.  I will try your suggestion.
