### ISSUE TITLE
[Bug]: Mac M2  EXC_CRASH (SIGKILL (Code Signature Invalid))

### ISSUE THREAD

**Issue by jchuai** [intitni/CopilotForXcode#346]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

A bug happened!
when I try to build the project in my mac pro (M2), a crash happened. please help me , thanks.  Full system logs as followed

`
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: C4AA5E8B-E5AA-4A0B-AC0D-9DA655910980
CrashReporter Key:   868C8F3F-F311-9C95-141F-A06DDBCDACB9
Hardware Model:      Mac14,10
Process:             Copilot for Xcode Dev [30249]
Path:                /Users/USER/Library/Developer/Xcode/DerivedData/Copilot_for_Xcode-erbmliemhecjqmbokeizktunsjzu/Build/Products/Debug/Copilot for Xcode Dev.app/Contents/MacOS/Copilot for Xcode Dev
Identifier:          dev.com.intii.CopilotForXcode
Version:             0.22.2 (232)
Code Type:           ARM-64 (Native)
Role:                Background
Parent Process:      launchd [1]
Coalition:           dev.com.intii.CopilotForXcode [46445]

Date/Time:           2023-08-28 19:34:38.3650 +0800
Launch Time:         2023-08-28 19:34:38.3541 +0800
OS Version:          macOS 13.4 (22F66)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: CODESIGNING 1 Taskgated Invalid Signature

Triggered by Thread:  0

Thread 0 Crashed:
0   ???                           	       0x10657ca40 _dyld_start + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x000000016ce22c20   pc: 0x000000010657ca40 cpsr: 0x00001000
   far: 0x0000000000000000  esr: 0x00000000  Address size fault

Binary Images:
       0x106578000 -        0x106607fff ??? (*) <bd993f39-c902-37d6-8bd8-6d827c7f121e> ???
       0x102fdc000 -        0x103d6ffff  (*) <f77f35f9-884d-35bf-b3ee-28896a7afa7d> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"Copilot for Xcode Dev","timestamp":"2023-08-28 19:34:38.00 +0800","app_version":"0.22.2","slice_uuid":"f77f35f9-884d-35bf-b3ee-28896a7afa7d","build_version":"232","platform":0,"bundleID":"dev.com.intii.CopilotForXcode","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.4 (22F66)","roots_installed":0,"name":"Copilot for Xcode Dev","incident_id":"C4AA5E8B-E5AA-4A0B-AC0D-9DA655910980"}
{
  "uptime" : 330000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,10",
  "coalitionID" : 46445,
  "osVersion" : {
    "train" : "macOS 13.4",
    "build" : "22F66",
    "releaseType" : "User"
  },
  "captureTime" : "2023-08-28 19:34:38.3650 +0800",
  "incident" : "C4AA5E8B-E5AA-4A0B-AC0D-9DA655910980",
  "pid" : 30249,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-08-28 19:34:38.3541 +0800",
  "procStartAbsTime" : 7937951105371,
  "procExitAbsTime" : 7937951357555,
  "procName" : "Copilot for Xcode Dev",
  "procPath" : "\/Users\/USER\/Library\/Developer\/Xcode\/DerivedData\/Copilot_for_Xcode-erbmliemhecjqmbokeizktunsjzu\/Build\/Products\/Debug\/Copilot for Xcode Dev.app\/Contents\/MacOS\/Copilot for Xcode Dev",
  "bundleInfo" : {"CFBundleShortVersionString":"0.22.2","CFBundleVersion":"232","CFBundleIdentifier":"dev.com.intii.CopilotForXcode"},
  "storeInfo" : {"deviceIdentifierForVendor":"09628388-AC65-5428-BF43-15BA7DC3DF0D","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "dev.com.intii.CopilotForXcode",
  "crashReporterKey" : "868C8F3F-F311-9C95-141F-A06DDBCDACB9",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 16777216,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 15285,
  "sleepWakeUUID" : "17D99F15-8CD8-419E-9440-96DF82D3543F",
  "sip" : "disabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"flags":66,"code":1,"namespace":"CODESIGNING","indicator":"Taskgated Invalid Signature"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":2},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":10396486,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6121729056},"esr":{"value":0,"description":" Address size fault"},"pc":{"value":4401384000,"matchesCrashFrame":1},"far":{"value":0}},"frames":[{"imageOffset":19008,"symbol":"_dyld_start","symbolLocation":0,"imageIndex":0}]}],
  "usedImages" : [
  {
    "size" : 589824,
    "arch" : "arm64e",
    "source" : "P",
    "base" : 4401364992,
    "uuid" : "bd993f39-c902-37d6-8bd8-6d827c7f121e"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4345151488,
    "size" : 14237696,
    "uuid" : "f77f35f9-884d-35bf-b3ee-28896a7afa7d",
    "name" : ""
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=48.5M resident=0K(0%) swapped_out_or_unallocated=48.5M(100%)\nWritable regions: Total=8720K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8720K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \n__DATA                            1616K        3 \n__DATA_CONST                       368K        2 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                        34.3M        2 \n__LLVM_COV                        1392K        1 \n__TEXT                            14.1M        2 \n===========                     =======  ======= \nTOTAL                            115.8M       13 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "f8a0075acc72f2c14ec5c514be756eac2b591483",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {

      },
      "deploymentId" : 240000002
    },
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: Mac14,10, BootROM 8422.121.1, proc 12:8:4 processors, 32 GB, SMC 
Graphics: Apple M2 Pro, Apple M2 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Display: LEN T27q-20, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4388), wl0: Apr 15 2023 07:04:38 version 23.20.84.0.40.50.94 FWID 01-a7cc62f5
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB Type-C Digital AV Adapter
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
`

### How to reproduce the bug.

It just happens!

**Comment by intitni** [comment]
Please update the configuration files mentioned in DEVELOPMENT.md and try again.

**Comment by jchuai** [comment]
![image](https://github.com/intitni/CopilotForXcode/assets/3783205/d33debd8-cba8-4f6f-8246-ac773f0e6364)
thanks for your reply. is this files I should update ? 
Could you please tell me , which content should I update ? Thanks

**Comment by jchuai** [comment]
![image](https://github.com/intitni/CopilotForXcode/assets/3783205/7d56c7f8-e106-44ba-96d1-15228390186d)
with launchAgent, should I update Label and program?

**Comment by intitni** [comment]
Since the crash says Code Signature Invalid, my guess is you should update the bundle identifiers and team ids in those files. I haven't seen those errors before so I can't tell you exactly what to do.

**Comment by jchuai** [comment]
Hi，after I update the Team and Bundle Identifier in xcconfig files, launchAgent.plist, and Tool/Configs/Configurations.swift, it  can build and launch successfully. Thanks for suggestion ~~ I will close this bug.
