### ISSUE TITLE
[Enhancement]: Disable new line after Accept

### ISSUE THREAD

**Issue by GkFoxes** [intitni/CopilotForXcode#349]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

I think it will be cool to disable automatically starting a new line after accepting the code from Copilot. Make a cursor at the end of the new code after accepting it.

It's better to add this on Settings with some check button because it's not for everybody, but I think it will be really cool!

**Comment by intitni** [comment]
The new line is generated by GitHub Copilot, not the app. And it doesn't always generate the new line, which is quite annoying. If you don't like the behavior, you can turn this on:

<img width="401" alt="Screenshot 2023-08-29 at 22 24 13" src="https://github.com/intitni/CopilotForXcode/assets/793147/89d8e84e-1ca5-4955-b92e-88437c7bfa4e">

**Comment by GkFoxes** [comment]
Sorry, I didn't find it, right now it's good
Thank you!
