### ISSUE TITLE
[Help Wanted]:  The extension doesn't show up in the Editor menu.

### ISSUE THREAD

**Issue by Wawa1996** [intitni/CopilotForXcode#351]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I want help!

Q: The extension doesn't show up in the Editor menu.
A: Please make sure Copilot is turned on in System Settings.app > Privacy & Security > Extensions > Xcode Source Editor Extension.

I have enabled the control permissions of copilotforxocdeextensionService in the accessibility function, but there is no copilot option in the extension setting.

Please tell me how to solve it Thanks a lot

**Comment by intitni** [comment]
There is another toggle you need to turn on.
<img width="743" alt="Screenshot 2023-09-04 at 18 51 08" src="https://github.com/intitni/CopilotForXcode/assets/793147/908f2d5c-a819-4b63-bb8a-d6e73fdf4c2d">
<img width="745" alt="Screenshot 2023-09-04 at 18 51 14" src="https://github.com/intitni/CopilotForXcode/assets/793147/3ff07234-0d89-4128-8853-a9e0bee287b0">
<img width="533" alt="Screenshot 2023-09-04 at 18 51 20" src="https://github.com/intitni/CopilotForXcode/assets/793147/93b8ecf7-f2df-4722-90c7-20067a1b35d5">

**Comment by Wawa1996** [comment]
Thank you for your answer, but I can't find the copilot option in the Xcode source editor
![1](https://github.com/intitni/CopilotForXcode/assets/58599960/5edf8db0-c9c9-4bc7-bed6-57f8dc4bad67)

**Comment by intitni** [comment]
Did you open the app once? I believe it's an Xcode issue. You can try restarting Xcode or, well, rebooting (´･ω･｀)

**Comment by Wawa1996** [comment]
Yes, I have opened the app. I have experienced the real-time code prompting function, but it is not displayed in the editor. . .

**Comment by intitni** [comment]
You can also try moving the Copilot for Xcode.app out of the Applications folder and move it back in.

**Comment by Wawa1996** [comment]
In fact, I am working on internal AI support and want to add an additional AI service. If I want to compile copilot dev from source code, what are the steps to add the project to the editor?

**Comment by intitni** [comment]
Please read DEVELOPMENT.md for details
