### ISSUE TITLE
[Bug]: Intermittently getting "cannot parse response"

### ISSUE THREAD

**Issue by patterueldev** [intitni/CopilotForXcode#353]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I sometimes get a "cannot parse response" response from the chat feature, and to be honest, while I don't mind getting that, I just wish there was a way to easily "regenerate" the response because I can't even do a copy and paste from my previous message properly. 

https://imgur.com/inX47ke

I hope we  get a sort of "resend message" feature so I wouldn't have to copy and paste it. it especially is hard to copy my previous message if there's a code I wrapped with '```'

### How to reproduce the bug.

It intermittently happens, my ISP could be an issue since no one else seem to encounter the issue.

### macOS version

Ventura 13.5.1 (22G90)

### Xcode version

Version 15.0 beta 7 (15A5229h)

### Copilot for Xcode version

0.22.3

### Node version

20.1.0

**Comment by intitni** [comment]
You can right click on the cell (or the empty space on the left or right side of the cell, but not on the text) to open a context menu, click resend you send the message again.
