### ISSUE TITLE
[Bug]: Tab to complete broken

### ISSUE THREAD

**Issue by marcusziade** [intitni/CopilotForXcode#357]
I've used the app since January, no big issues until now.

### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

v0.23.1 broke tab to complete for me. None of the usual tricks fix it. I've tried what the FAQ said as well.

### How to reproduce the bug.

Try to accept a result

### macOS version

14.0 Beta 7

### Xcode version

15 Beta 8

### Copilot for Xcode version

0.23.1

### Node version

v20.5.1

**Comment by intitni** [comment]
Can you accept suggestions by clicking the accept button on the suggestion?

**Comment by intitni** [comment]
Accepting with Tab does basically the same thing as the accept button. 

If the button is also not working for you, it may be something wrong with the Copilot menu from the Editor menu in Xcode. If this is the case, the reason may be that Xcode is talking to another version of the extension. Please let me know if it works with "Always accept suggestions with Accessibility API" on.

If the button is working, It may be that the app failed to observe keystrokes. This case will be complicated.

**Comment by marcusziade** [comment]
- I have the buttons hidden
- Always accept suggestions with Accessibility API - I've done this already
- Started happening when I updated to v0.23.1
![CleanShot 2023-09-09 at 19 27 54@2x](https://github.com/intitni/CopilotForXcode/assets/47460844/8cf5eb4e-9c39-4ba5-b48e-eda6731cbe39)
![CleanShot 2023-09-09 at 19
![CleanShot 2023-09-09 at 19 28 09@2x](https://github.com/intitni/CopilotForXcode/assets/47460844/7ecdb435-5487-4ad7-ab68-ad886579e184)
 27 59@2x]

![CleanShot 2023-09-09 at 19 28 05@2x](https://github.com/intitni/CopilotForXcode/assets/47460844/b92ec11a-0ee9-46f7-92ea-c7dcae9cd756)

<img width="1012" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/47460844/8476c114-dcc9-44f3-a3de-5cd1935d90c2">

**Comment by intitni** [comment]
Please update to version 0.23.2, open Console.app and set the filter to 
```
Copilot 
category:Service
any:TabToAcceptSuggestion:
```

Deactivate and activate Xcode and show me the log.

**Comment by marcusziade** [comment]
This is the log when I launch Xcode while console.app is streaming with the filter you said 

![CleanShot 2023-09-09 at 19 52 12@2x](https://github.com/intitni/CopilotForXcode/assets/47460844/80fd3bf7-eb32-4f5d-8c27-44ff046dfb4b)

**Comment by marcusziade** [comment]
I think the issue started after updating to macOS 14 Beta 7 🤔

**Comment by intitni** [comment]
What happen if you try toggling accept with tab off then on? It look like some other logs are missing too..

**Comment by marcusziade** [comment]
Toggling tab to complete on or off doesn't seem to do anything, and I only get that output when I launch Xcode from a killed state

**Comment by marcusziade** [comment]
Ok, got a bigger output by restarting all the apps

![CleanShot 2023-09-09 at 20 18 42@2x](https://github.com/intitni/CopilotForXcode/assets/47460844/dbd8173d-b13b-4a0b-a074-089edf37a798)

**Comment by intitni** [comment]
Do you want to give this version a try? I have added more logs to it.
https://github.com/intitni/CopilotForXcode/releases/download/0.22.3/test.app.zip

I think I will have to update to Sonoma to test it out.

**Comment by marcusziade** [comment]
Update: 
One more restart of the MacBook got the tab completion working again, but there's some weird glitch whenever I accept a result. All the code in the file makes this weird jump




https://github.com/intitni/CopilotForXcode/assets/47460844/042ab839-774f-4cc4-80f8-38b438403057

**Comment by intitni** [comment]
The glitch comes from "Always accept suggestion with Accessibility API"

**Comment by marcusziade** [comment]
Ok, good, cause I had that disabled before.

**Comment by marcusziade** [comment]
I think it works fully again

**Comment by intitni** [comment]
It looks like the app fails to receive notification `NSWorkspace.didActivateApplicationNotification` in your case.

Well I think I will still update to Sonoma, I will close it after that.
