### ISSUE TITLE
[Bug]: ChatGPT starts speaking giberish after asking a question

### ISSUE THREAD

**Issue by Ashtronaut09** [intitni/CopilotForXcode#358]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I ask it a question and it gives me back gibberish, which renders it unusable. It's been doing this on and off and randomly the past month. It seems that the longer the answer the more likely it will begin to stop making sense.

Attached screenshot
<img width="450" alt="Screenshot 2023-09-13 at 2 05 29 AM" src="https://github.com/intitni/CopilotForXcode/assets/13004940/cd10776f-d604-41c3-8d28-dff25ac17294">

### How to reproduce the bug.

Ask it a coding question where you might expect a long answer.

### macOS version

13.5.1 Ventura

### Xcode version

Version 14.3.1 (14E300c)

### Copilot for Xcode version

Version 0.23.2 (241)

**Comment by intitni** [comment]
What is the value of temperature in your settings? You can set it to a lower value to avoid gibberish response. Avoid setting it to anything greater than 1.
