### ISSUE TITLE
Extension gets stuck in Floating Widget mode

### ISSUE THREAD

**Issue by chihsuanwu** [intitni/CopilotForXcode#36]
When using the Floating Widget mode, the extension gets stuck after the first suggestion appears. This happens whether real-time suggestion is enabled or disabled. 

https://user-images.githubusercontent.com/22000682/222893617-2fe234fc-aced-4cf1-bac9-64e09d37e381.mov

Suggestions in comment mode work fine.

**Comment by intitni** [comment]
Is the menu bar app still working? What happens if you accept the suggestion by running the command from the menu bar?

**Comment by intitni** [comment]
@LisonFan 可以详细描述一下吗？我没有办法重现。是整个 CopilotForXcodeExtensionService.app 都卡住了还是只是 UI 卡住了？

**Comment by intitni** [comment]
@LisonFan 我猜是我临发版前写了个 bug，你可以试试这个版本吗？
[Copilot for Xcode.app.zip](https://github.com/intitni/CopilotForXcode/files/10889181/Copilot.for.Xcode.app.zip)

**Comment by intitni** [comment]
我好像发了一个 CopilotForXcodeExtensionService.app 被放到了其他目录的版本( •̅_•̅ )，所以权限要重新设置。这两个版本的差别在于显示 Xcode Completion Panel 时能不能生成实时建议，发版时间实在太晚了搞了个大乌龙写了个 bug，得回退回去了 ( ･᷄ὢ･᷅ )

**Comment by intitni** [comment]
对我测试的时候被要求重新设置权限我还以为是目录的问题，实际上是 notarized 和没有 notarized 的问题，所以又改回去了

**Comment by intitni** [comment]
Should be fixed in 0.8.2

**Comment by chihsuanwu** [comment]
0.8.2不會卡住了

**Comment by intitni** [comment]
不知两位是否有更新到 0.8.3 呢？如果有的话有再次遇到卡住的 bug 吗？

**Comment by chihsuanwu** [comment]
我在一個比較大的project上使用的時候又卡住了（0.8.2），不知道跟project的大小有沒有關係。
等等我更新到0.8.4後再測試看看。
