### ISSUE TITLE
[Help Wanted]:I want to upgrade XCODE to XCODE15 copilotforxcode Does XCode support XCODE15?

### ISSUE THREAD

**Issue by hotdog12345a** [intitni/CopilotForXcode#360]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I want to upgrade XCODE to XCODE15 copilotforxcode Does XCode support XCODE15?
THANKS

**Comment by intitni** [comment]
Yes, it does. But I haven't spent too much time using Xcode 15, so please let me know if you encounter any issues.

**Comment by hotdog12345a** [comment]
Thanks, I just updated XCODE15 and it's working fine.
