### ISSUE TITLE
[Enhancement]: press tab to accept suggestion?

### ISSUE THREAD

**Issue by anwarulislam** [intitni/CopilotForXcode#367]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Currently, If I write something and get a suggestion on a prompt I see a button to Accept the suggestion. And I can accept it by clicking that button.

But, it would be better if I just press tab button to accept the suggestion.

**Comment by intitni** [comment]
It's a plus feature, please consider getting the plus license key to support this project.
