### ISSUE TITLE
[Enhancement]: When using Accept Suggestion with tab newline optional

### ISSUE THREAD

**Issue by th-mustache-dk** [intitni/CopilotForXcode#369]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Hey I could really use a setting that disable the newline insertion when using tab for accepting suggestion.

**Comment by intitni** [comment]
What do you mean by "disable newline insertion"?

**Comment by intitni** [comment]
If you mean the extra new lines inserted by GitHub Copilot, there is a toggle for it in the GitHub Copilot settings.

**Comment by th-mustache-dk** [comment]
Oh yes, sorry you are right. Thank you very much for the help
