### ISSUE TITLE
[Enhancement]: Ability to read clipboard contents in a custom command

### ISSUE THREAD

**Issue by chrisvasselli** [intitni/CopilotForXcode#376]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

I would love the ability to use the clipboard contents in my custom command, similar to using `{{selected_code}}` to get the selected code. Perhaps `{{clipboard}}`?

I have a custom command to convert ObjC code to Swift. Currently I cut it from the ObjC file, paste it into the Swift file, and then select it and run my command. It would be awesome if I could cut out that last step, and just run a custom command to paste the converted code directly into the Swift file.

**Comment by intitni** [comment]
Sounds cool, added to my todo list. I will see If I have time to include it in the next release.

**Comment by intitni** [comment]
Released in 0.26.0.

If you use prompt to code custom command, the settings should look like: 

<img width="1012" alt="Screenshot 2023-10-20 at 23 15 59" src="https://github.com/intitni/CopilotForXcode/assets/793147/00b3e07f-fff6-4512-85eb-bb074cc4affe">

**Comment by chrisvasselli** [comment]
Awesome, just tried it out and it worked perfectly. Thanks so much for the super quick turnaround! 🤩
