### ISSUE TITLE
[Enhancement]: Make the chat panel close button bigger 

### ISSUE THREAD

**Issue by marcusziade** [intitni/CopilotForXcode#379]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Making the button bigger would make it easier to click. I might implement this and make a PR, so feel free to assign it to me.

**Comment by intitni** [comment]
That would be awesome! I don't even remember why I made them so small.

The buttons are defined in `ChatTitleBar` in `ChatWindowView`. If you change the height of the bar, you should also update the `ChatWindow.mouseDown` at the bottom of `SuggestionWidgetController.swift` to match the new height.

**Comment by intitni** [comment]
And the 16 in `windowDidBecomeKey`

Sorry for the magic value. (´･ω･｀)

**Comment by marcusziade** [comment]
Cool, I'll check it out at some point. A little busy with the move right now.

**Comment by intitni** [comment]
I was just trying to remove the magic values.. But after removing them I immediately noticed that I could just give them a bigger value.. (´･ω･｀)

Please let me know if they are big enough ( • ̀ω•́ )/

**Comment by marcusziade** [comment]
I'll have to compile locally, but I simply don't have any bandwidth atm. Make a release and I'll re-open this if needed.

**Comment by intitni** [comment]
Released in 0.27.0

**Comment by marcusziade** [comment]
Also, would be a good idea to link issues to pull requests with #<issuenumber>, so it's easy to find
