### ISSUE TITLE
[Bug]: GPT-4 model doesn't use GPT-4

### ISSUE THREAD

**Issue by grangej** [intitni/CopilotForXcode#381]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I am enabled for GPT-4 now, but when I query the chat It still reports using GPT-3 ( I have confirmed going directly to the chat.openai.com and querying the chat it correctly returns GPT-4)

The query I am giving is: What model of GPT are you running right now, and when was it released?

> As an AI developed by OpenAI, I am based on the GPT-3 model. However, I don't have real-time updates or access to the latest model versions' specifics. As of my last update, GPT-3 was the latest model, which was publicly released in June 2020. For the most accurate and up-to-date information, please refer to the official OpenAI documentation or announcements.

If I try the same query on chat.openai.com with GPT-4 selected I get

> I am based on the GPT-4 architecture. As of my last training data cutoff in January 2022, GPT-4 was the most recent version. I'm not aware of any subsequent versions released after that date. If there have been newer versions since then, I wouldn't have information on them.

<img width="881" alt="Screenshot 2023-10-26 at 7 53 08 AM" src="https://github.com/intitni/CopilotForXcode/assets/604788/a926f16a-493d-4c3b-8d2c-86bf4d1024f9">
<img width="909" alt="Screenshot 2023-10-26 at 7 53 44 AM" src="https://github.com/intitni/CopilotForXcode/assets/604788/f513a6e2-9138-4f6f-b497-8bb73bf09f67">

### How to reproduce the bug.

1. configure OpenAI for GPT-4
2. query the chat

**Comment by intitni** [comment]
This is not a bug, please check the following issue for details.

Duplicated to #372
