### ISSUE TITLE
[Help Wanted]: Redeeming PLUS activation key throws an SSL Error

### ISSUE THREAD

**Issue by BoiLudens** [intitni/CopilotForXcode#384]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I'm getting an error trying to redeem my plus key that says:
"An SSL error has occurred and a secure connection to the.."
<img width="902" alt="Screenshot 2023-11-04 at 11 10 28 AM" src="https://github.com/intitni/CopilotForXcode/assets/25911562/d7b52d64-a6ff-47af-b3e2-b641e54b84fa">
And when I visit the site on firefox I receive this error:
<img width="1260" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/25911562/573b4149-0f36-47b2-8916-92ebd985f22a">

**Comment by intitni** [comment]
I can't tell what was going on. The server is hosted as a Cloudflare worker, and the certificate was generated automatically. I think it should be trusted by your computer.

I have updated the server to handle a get request at the root, so you can refresh the webpage to see if anything is changed.

<img width="750" alt="Screenshot 2023-11-05 at 12 21 38" src="https://github.com/intitni/CopilotForXcode/assets/793147/52c70e83-4503-42c9-a9f2-83faba092598">

**Comment by BoiLudens** [comment]
I'm thinking the API service may be having a rough time.
I tried on another browser just in case, 
<img width="612" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/25911562/672e6830-8b4b-4b2c-88b5-bb6b4e4d2f10">
no dice unfortunately.

**Comment by intitni** [comment]
Looks like the API outage is already over.

Can you please check if the certificate matches the one I sent in the screenshot by clicking the lock icon in the address bar? Also, the IP address for the domain should be 172.67.146.136. If any of them don't match, you can try changing your DNS server to something else and try again.

**Comment by BoiLudens** [comment]
I connected to my personal hotspot, there is a good chance my pi-hole was getting in the way. That's wild that the pi-hole was fighting the activation.

**Comment by intitni** [comment]
Please also note that the app will verify the license upon launch. I recommend making changes to the pi-hole so that it will not get blocked again.
