### ISSUE TITLE
[Bug]: Could not communicate with a helper app

### ISSUE THREAD

**Issue by marandaneto** [intitni/CopilotForXcode#386]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

The operation could not be completed, operation not permitted.
Could not communicate with a helper app.

### How to reproduce the bug.

Go to General tab or click on Set up Launch Agent

### macOS version

14.0

### Xcode version

15.0.1

### Copilot for Xcode version

0.26.0

### Node version

18.17.1

**Comment by marandaneto** [comment]
<img width="811" alt="Screenshot 2023-11-06 at 09 02 15" src="https://github.com/intitni/CopilotForXcode/assets/5731772/df96e37d-128b-436a-b1da-174e5833d535">

<img width="880" alt="Screenshot 2023-11-06 at 09 02 26" src="https://github.com/intitni/CopilotForXcode/assets/5731772/1f791732-7d0d-431f-a982-713e325dfd02">

<img width="833" alt="Screenshot 2023-11-06 at 09 02 53" src="https://github.com/intitni/CopilotForXcode/assets/5731772/220d9110-31a9-4f38-a405-407d8fce42d2">

Everything is configured correctly, extension settings, accessibility settings, app is under the Application folder, created the plist file manually as well, logged out and in from GH, etc.

**Comment by intitni** [comment]
Looks like the app can't register the launch agent for some unknown reasons.

After manually creating the launch agent file, you need to run `launchctl load /path/to/the/launchagent.plist` to set it up.

It has nothing to do with GitHub Copilot. If the issue persists, please try rebooting your Mac.

**Comment by marandaneto** [comment]
Thanks, Apparently the error is gone now and everything is working.

What I did: 
* Added missing `chmod` to plist file and did the `launchctl` thing (error was still happening).
* Opened Login items under System settings and gave "Allow in the background permission" to Copilot for Xcode.

Should I add those to the FAQ? or was it just a coincidence? Maybe the later is now required under some circumstances.

**Comment by intitni** [comment]
Thanks, I will add them to the FAQ later.

**Comment by RiceGTSTW** [comment]
I solved this by moving the app from `/Users/{your user name}/Applications` to `/Applications`.
