### ISSUE TITLE
[Bug]: Chat window scroll to top when done processing output

### ISSUE THREAD

**Issue by zenangst** [intitni/CopilotForXcode#387]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

The scroll view goes to the top after the output has been processed.

### How to reproduce the bug.

Simply open the chat, ask something and wait for the response.

### macOS version

macOS Sonoma 14.1 (23B74)

### Xcode version

Xcode 15.0.1 (15A507)

### Copilot for Xcode version

0.26.0

### Node version

v20.3.1

**Comment by intitni** [comment]
Can you provide a screen recording?

**Comment by zenangst** [comment]
Coming right up!


https://github.com/intitni/CopilotForXcode/assets/57446/8f58db6d-7641-4d65-9342-7b0e4c77f95b

**Comment by intitni** [comment]
I can't reproduce it, it's probably some SwiftUI art. 

I noticed from the video that there was an animation when the chat panel tried to stick to the bottom, the animation never worked for me so I forgot to remove it. I think that may be the cause.

Please give this version a try https://github.com/intitni/CopilotForXcode/releases/download/0.25.0/Copilot.for.Xcode.temp.app.zip

**Comment by zenangst** [comment]
@intitni tried the version that you attached.
That one doesn't scroll when I use the keyboard shortcut to have it explain code.

https://github.com/intitni/CopilotForXcode/assets/57446/3b797846-26b7-4a21-9041-80e05e3683b3

It does however keep being stuck at the bottom if I manually scroll down and run the command again. But never with a fresh window.

Here are my settings for CoPilot for Xcode.

<img width="1012" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/57446/9a4c5d4c-97bf-43e9-a030-55fb01d41dcc">

**Comment by zenangst** [comment]
Seems like a timing issue 🤔 
Because if I close the window and open it again using the keyboard command, it will work, like 1 out of 5 times or so.

**Comment by intitni** [comment]
The behavior in the video is expected. When the scroll to the bottom at the bottom right is displayed, the chat panel will not stick to the bottom. 

I should update it to re-enable stick to the bottom when a new message is sent. 

> But never with a fresh window.

Does the fresh chat start at the bottom?

**Comment by zenangst** [comment]
It sometimes sticks to the bottom, other times it just keeps the current scroll location.

**Comment by zenangst** [comment]
At least the version you attached doesn't seem to jump to the top when it is done processing, which is a good thing.

**Comment by intitni** [comment]
Released in 0.27.0
