### ISSUE TITLE
[Bug]: Using Accept Suggestion with Tab has some weird side-effects

### ISSUE THREAD

**Issue by zenangst** [intitni/CopilotForXcode#392]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

There is a difference between using Tab to accept the suggestions or using `Accept Suggestion` using the menubar item.

### How to reproduce the bug.

It can lose focus or jump around in the same file.

Here is what happens when you use `Accept Suggestion` using a keyboard shortcut.

https://github.com/intitni/CopilotForXcode/assets/57446/19e10855-554c-40e4-8d34-0b778c3e226e

Here is what happens when you use Tab:

https://github.com/intitni/CopilotForXcode/assets/57446/e910c329-c1e5-4b51-865c-18b575b970cd

These two recording is "best"-case. In a larger file, it can jump to the top and lose the current location. In addition, using undo on the change has some odd behavior as well.

I'd favor it if both methods worked the same, so that `Tab` would simply just invoke `Accept Suggestion` and it would take over from there.

I haven't checked the implementation to know how they different, so I'm missing some context on how big of a change this would be.

### macOS version

macOS Sonoma 14.1.1 (23B81)

### Xcode version

Xcode Version 15.0.1 (15A507)

### Copilot for Xcode version

0.27.0

### Node version

v20.3.1

**Comment by intitni** [comment]
They run the same piece of code under the hood. The jump happens when the Copilot menu is grayed out and it needs to use the fallback solution to accept a suggestion. 

It usually happens after updating the extension. Restarting Xcode will fix it.

**Comment by zenangst** [comment]
Yeah that is what I thought, but the behavior is a lot different depending on the change.

I'll try an come of with some better recording because this doesn't really give it justice.

Keep you posted!

**Comment by intitni** [comment]
Any chance you have turned the toggle “Always accept suggestion with Accessibility API” on in the advanced settings?

**Comment by zenangst** [comment]
@intitni yeah, that setting is turned on. Should it be off? 🤔

**Comment by intitni** [comment]
Yes, that is the fallback solution ( • ̀ω•́ )✧

Most of the time you don't need to change the settings in that tab.

**Comment by zenangst** [comment]
I'll give it a shot, thanks! ❤️

**Comment by zenangst** [comment]
Seems to do the trick! 🤩 

**Solved by disabling `Always accept suggestion with Accessibility API`**

**Comment by intitni** [comment]
I also noticed that you have turned “Disable Enhanced Workspace” on. That will disable some features, too.

**Comment by zenangst** [comment]
This is what I get for fiddling with settings that I don't know the outcome of. I'll disable that because I don't really have a good reason for having it enabled 🤡

**Comment by zenangst** [comment]
Oh wait, right now I'm running with these settings:

![image](https://github.com/intitni/CopilotForXcode/assets/57446/b521ac1c-f80c-4d1a-a630-1c5f92754408)

Does that look okay?

**Comment by intitni** [comment]
Looks good to me.
