### ISSUE TITLE
[Help Wanted]: I have a Copilot subscription but can't get it running in Xcode

### ISSUE THREAD

**Issue by carlca** [intitni/CopilotForXcode#394]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

* Xcode 15.1 beta
* macOS 13.6

I have an active Github Copilot subscription and have been using it in VS Code and Cursor ( a VS Code clone). I've installed the Copilot for Xcode extension and the extra option appears at the foot of the `Editor` menu in Xcode. So far, so good!

When I try to use the extension I get this error...

![SCR-20231112-olje](https://github.com/intitni/CopilotForXcode/assets/260612/0ed19e2d-209f-4088-beb4-376246b98b81)

I've been to the openai website and have generated a new API key, but I don't know how to add it to `Copilot for Xcode`!

Please can you or anyone reading this explain what I need to do? Thx! 
I promise I've checked the issues (both open and closed) and the FAQs 😉

**Comment by carlca** [comment]
I looked at the instructions and saw that I hadn't completed the Github Copilot stage, even though I'm using Github Copilot in another editor (Cursor), so I completed these steps...

![SCR-20231112-rvam](https://github.com/intitni/CopilotForXcode/assets/260612/a09815e8-2554-49ee-8ebb-130079e77257)

And tried again. It is still after my API key, which as I say, I have ready and waiting - I just need to know where to stick it 😉

**Comment by intitni** [comment]
The chat feature is not provided by GitHub Copilot, please read the [next section in the README.md](https://github.com/intitni/CopilotForXcode#setting-up-chat-feature) to setup a chat model.

**Comment by intitni** [comment]
It's not the same error. You just don't have access to GPT-4 yet. Please check the link in the error message https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4 for details

**Comment by carlca** [comment]
This is from `https://chat.openai.com`...

![image](https://github.com/intitni/CopilotForXcode/assets/260612/6a320b8b-1410-418b-9289-0f05fc9dfb79)

Now do you understand why I am finding the error messages and comments like "You just don't have access to GPT-4 yet" very frustrating!

Could you also tell me which of the Editor -> Copilot menu options I should use to access the Github Copilot facilities?

**Comment by intitni** [comment]
ChatGPT Plus and the API thing are using different payment systems. From what I can see from the link, you have to use at least 1 USD before you can access GPT-4.

GitHub Copilot fetches suggestions automatically when you type, you can use the accept suggestion command to accept it. You can find the meanings of the other commands in the README.md in the [Feature section](https://github.com/intitni/CopilotForXcode#feature).

**Comment by carlca** [comment]
I've just added $10 to my Chat GPT API account. And after having to delete my existing API key and adding a new one, I'm now getting somewhere in terms of the `Test` button with `Copilot for Xcode`...

![SCR-20231113-ktob](https://github.com/intitni/CopilotForXcode/assets/260612/ae44d100-e213-4fc1-be81-516c0f882e61)

However, I am still getting the error in the Chat facility...

![SCR-20231113-kvfl](https://github.com/intitni/CopilotForXcode/assets/260612/75f38d12-eb67-4870-a32b-e16a63113a53)

Any ideas?

**Comment by intitni** [comment]
Change the chat model in Feature - Chat to the new one.

**Comment by carlca** [comment]
Thank you! I've got the Chat working now 😃

For the record, I've got a thirty year development career behind, so I don't think I am a stupid man, but I have to say that that process of getting it set up was much more difficult than it needed to be, with too many stages of the process relying on the user knowing things about Chat GPT in advance, that the docs don't tell you!

To be fair, I would say that `openai` are guilty of the same thing. It was only half an hour ago that I discovered that the `Chat GPT API` service was a separate thing from the `Chat GPT Plus`!

This afternoon, I will try to get the Github Copilot suggestions working. You may here from me again 😉

**Comment by emrdgrmnci** [comment]
I'm in same headache! To be able to use that Copilot for Xcode's chat and suggestions and get rid of that 'You didn't provide an API key ...' thing I have to buy separate Chat GPT API service in addition to my current Chat GPT 4 subscription?

**Comment by intitni** [comment]
@emrdgrmnci Yes

**Comment by emrdgrmnci** [comment]
Thank you! So, I couldn't find the place for buying that additional ChatGPT API subscription. Can you guide me?

**Comment by intitni** [comment]
@emrdgrmnci you can create a key in the the user settings page on openai.com 

https://platform.openai.com/api-keys

**Comment by emrdgrmnci** [comment]
@intitni  I have already created and pasted API key into the Copilot for Xcode but still getting error "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys."

**Comment by intitni** [comment]
@emrdgrmnci Please make sure that
1. You have selected the key in the chat model settings. 
2. You have selected the correct model in the chat feature settings. 

If the issue persists, please post the screenshots of the two pages here.

**Comment by emrdgrmnci** [comment]
I'm a Chat GPT Plus subscriber and I'm able to use Chat GPT-4, but I tried with all Model Names (gpt-4, gpt-3,5 and so on..) but still getting that You didn't provide an API key... error

<img width="898" alt="Screenshot 2023-11-25 at 16 37 49" src="https://github.com/intitni/CopilotForXcode/assets/10485498/7becf7e8-d67e-4fe5-8783-aac01454416f">
<img width="1512" alt="Screenshot 2023-11-25 at 16 40 04" src="https://github.com/intitni/CopilotForXcode/assets/10485498/04f9f659-5f89-4653-968f-b24392a4f859">
<img width="1512" alt="Screenshot 2023-11-25 at 16 40 31" src="https://github.com/intitni/CopilotForXcode/assets/10485498/98379480-8e9e-4a22-ac37-765d6d7b55e8">

**Comment by intitni** [comment]
@emrdgrmnci It looks like the error message is about insufficient quota, from the second screenshot. Chat GPT Plus and the API key are two different products using different billing system, please check that your billing information is correct on openai.com.

**Comment by emrdgrmnci** [comment]
Yes, I understood they are different and I have only Chat GPT Plus subscription for now. And, I'm still not able to find their another subscription and paying page for the API key. But, it's ridiculous to already setting API key through Chat GPT Plus subscription as well. 

In that case, what I understand is, I need to buy Chat GPT API subscription for getting it's API key which is other than Chat GPT Plus API key.

**Comment by intitni** [comment]
@emrdgrmnci try this page https://platform.openai.com/account/billing/overview

**Comment by emrdgrmnci** [comment]
I bought 6$ Chat GPT API subscription but still there's no luck! Also, I updated to Copilot for Xcode to version 0.27.1 and when I selected gpt-4-vision-preview as a Model Name, app is crashed at all. 

<img width="454" alt="Screenshot 2023-11-25 at 17 32 26" src="https://github.com/intitni/CopilotForXcode/assets/10485498/f6cc42b6-c905-408f-a6fd-60a53391a0d0">
<img width="1512" alt="Screenshot 2023-11-25 at 17 32 36" src="https://github.com/intitni/CopilotForXcode/assets/10485498/432dd9c3-a69e-4e93-829f-aaabaf59167a">
<img width="1512" alt="Screenshot 2023-11-25 at 17 33 51" src="https://github.com/intitni/CopilotForXcode/assets/10485498/eb8d085d-dbb4-4bc5-98a7-e11935c44a39">

**Comment by emrdgrmnci** [comment]
ok. finally, it worked! I was also added Codeium, and now I removed Codeium at all and Copilot started to work on.

**Comment by intitni** [comment]
@emrdgrmnci Glad to hear that. Please send me the crash log if possible. You can find it from the Console.app.

**Comment by emrdgrmnci** [comment]
[Copilot for Xcode-2023-11-25-183856.ips.zip](https://github.com/intitni/CopilotForXcode/files/13464526/Copilot.for.Xcode-2023-11-25-183856.ips.zip)

**Comment by varyP** [comment]
@intitni any idea on this?
![copilot-chat](https://github.com/intitni/CopilotForXcode/assets/8818244/713c48ff-55ed-49e8-a143-169b780a4cf1)

API Key added & test is a success in the host app settings. /run commands work but anything else does not work in the chat and gives this SSL error

**Comment by intitni** [comment]
@varyP Sorry I have no idea if the test in the host app is a success.. Can you show me the chat model settings?

**Comment by varyP** [comment]
> @varyP Sorry I have no idea if the test in the host app is a success.. Can you show me the chat model settings?

![image](https://github.com/intitni/CopilotForXcode/assets/8818244/3d9f29a8-dfd5-4e5c-86c3-7f55c281f308)

**Comment by wnykuang** [comment]
Is it possible to use github copilot to suppurt code chat? Just like vscode github copilot's feature?

**Comment by intitni** [comment]
> Is it possible to use github copilot to suppurt code chat? Just like vscode github copilot's feature?
> 
> Never mind, I figured it out. Q: Can I use the GitHub Copilot Chat A: No, they don't have any public API for it yet.

Actually there is a possible solution now, but not validated yet. Please keep an eye on this issue #380 

You can also find a workaround solution at the very bottom of the issue.

**Comment by LARSXX** [comment]
I am having the same problem.

**Comment by intitni** [comment]
@LARSXX I believe this issue has already been explained. If you have the same issue, you can find an answer from the thread. If you have another issue, please open a new issue and explain it in detail.
