### ISSUE TITLE
[Bug]: hotkey to toggle widget doesn't focus on chat's text box

### ISSUE THREAD

**Issue by kleber-maia** [intitni/CopilotForXcode#395]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

When using the hotkey to present the chat window, its text box doesn't get the focus: not desired. However, when I click that blue dot to present the chat window, its text box does get the focus (as expected).

### How to reproduce the bug.

- Go to Copilot's settings and set a hotkey to toggle the widget (e.g.: F1);
- Go to Xcode and hit your hotkey (F1 in this case);
- The chat window shows up;
- The focus is still on Xcode's editor (not good), while the expected result is for the widget's text editor to receive the focus so that I can continue my chat.

The way it is now, the hotkey is completely useless since I have to also use the mouse to click on the chat's text box.

### Relevant log output

```shell
NA
```

### macOS version

14.1.1 (23B2082)

### Xcode version

15.0.1

### Copilot for Xcode version

Version 0.27.0 (280)

### Node version

-

**Comment by zenangst** [comment]
I think the same goes for `Prompt to Code`. I wonder if #396 fixes both issues?

**Comment by intitni** [comment]
Yes it does

**Comment by intitni** [comment]
Released in 0.27.1
