### ISSUE TITLE
[Bug]: Suggestion feature is disabled for non-gitignored files.

### ISSUE THREAD

**Issue by GeRryCh** [intitni/CopilotForXcode#400]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

After the upgrade to 0.28.0, I'm receiving a "suggestion feature is disabled" error for all my files across all projects. Dumping the prior version solved the issue.

### How to reproduce the bug.

It just happens!

### macOS version

13.5.2

### Xcode version

15.0.1

### Copilot for Xcode version

0.28.0

### Node version

20.2.0

**Comment by intitni** [comment]
Does it work if you turn on "Disable git ignore check" in the advanced settings?

**Comment by GeRryCh** [comment]
> Does it work if you turn on "Disable git ignore check" in the advanced settings?

Yes.

**Comment by WingCH** [comment]
"Disable git ignore check" is work for me.

**Comment by intitni** [comment]
@GeRryCh How about removing "-i" from the argument list?

**Comment by intitni** [comment]
Something in my configuration is making the task throws on my Mac which made me think that it should throw for not in gitignore. In fact it returns empty string. Which should be handled in the missing else case that the content can't be parsed.

**Comment by GeRryCh** [comment]
> @GeRryCh Please give this version a try https://github.com/intitni/CopilotForXcode/releases/download/0.28.1/Copilot.for.Xcode.app.fixed.zip
> 
> > Removing all arguments gives the error:
> > return /bin/bash: git check-ignore "": No such file or directory although it exists.
> 
> You have to keep the "-c" or it will treat the string as the path to program.

In the version you've sent, it seems to be working regardless of whether the 'gitignore check' flag is selected! 👏

**Comment by intitni** [comment]
Thank you for reporting, it's now fixed in 0.28.2!
