### ISSUE TITLE
[Help Wanted]: How to uninstall GopilotForXcode

### ISSUE THREAD

**Issue by kanari3** [intitni/CopilotForXcode#401]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I want help!

Sorry, I want to know how to uninstall Copilot for Xcode🙏

**Comment by intitni** [comment]
Move the app to trash bin. Delete ~/Library/Application Support/com.intii.CopilotForXcode

**Comment by kanari3** [comment]
Thank you. That was very helpful.
