### ISSUE TITLE
[Help Wanted]: Missing key bindings for Codeium installation

### ISSUE THREAD

**Issue by guttentag** [intitni/CopilotForXcode#403]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I've installed Codium For Xcode and followed the instructions. I understand that I should see the copilot shortcut keys in the Xcode key binding list, but I don't

**Comment by intitni** [comment]
Please make sure you have enabled the source editor extension https://github.com/intitni/CopilotForXcode#enable-the-extension

If you are using the Codium For Xcode fork, you should look for `Codeium` in the list.

If you don't see the menu under Menu Bar > Editor > Codeium, restart Xcode.

**Comment by guttentag** [comment]
prefect!
