### ISSUE TITLE
[Enhancement] Sourcegraph Cody AI support

### ISSUE THREAD

**Issue by vi4m** [intitni/CopilotForXcode#410]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Cody is the Open Source plugin https://github.com/sourcegraph/cody which is the Copilot alternative. It would be awesome to offer support for this API as well.

**Comment by intitni** [comment]
I don't plan to add direct support to other services like this anymore, because there are just too many of them. A better approach is to implement a Copilot for Xcode extension with [CopilotForXcodeKit](https://github.com/intitni/CopilotForXcodeKit).

Let me know if anyone wants to give it a spin!

**Comment by intitni** [comment]
It looks like Cody is implemented as a VSCode extension and doesn't provide a language server. It's not possible to bring it to Copilot for Xcode.
