### ISSUE TITLE
[Enhancement]: Chat panel to support fullscreen mode and menu bar for window management

### ISSUE THREAD

**Issue by cliffordh** [intitni/CopilotForXcode#411]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

I'd like the Chat popup to be treated like a normal Window so that I can use Maximize and Move to iPad more easily.

**Comment by intitni** [comment]
Simply drag on its top bar to detach it, or click the detach button on the top bar, then then window will be movable and resizable.

**Comment by cliffordh** [comment]
Thanks but it is not treated as a window in its own right and can't be maximized via the green button or socked to iPad with a single menu option selection or keystroke and has to be manually moved. Granted it's low priority but would be a nice to have!

**Comment by intitni** [comment]
It's implemented as window. I think the real issue is that the window doesn't support fullscreen style mask and the service app doesn't provide a menu bar.

**Comment by intitni** [comment]
Released in 0.30.0

**Comment by cliffordh** [comment]
@intitni thank you! Move to iPad works perfectly :)
