### ISSUE TITLE
[Enhancement]: Close on Escape

### ISSUE THREAD

**Issue by cliffordh** [intitni/CopilotForXcode#412]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Let user close popup suggestion window with Escape or Cmd-W. Reject is insufficient since I am not rejecting the suggestion I am ignoring the suggestion.

**Comment by intitni** [comment]
ESC to dismiss suggestions is implemented in 0.30.0.
