### ISSUE TITLE
[Help Wanted]: building previews failed

### ISSUE THREAD

**Issue by juno12560** [intitni/CopilotForXcode#413]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

hi, When I compile Copilot for Xcode locally, everything works fine, but when I try to build previews, I encounter an error indicating that the tree_sitter library is missing. How should I configure the project to resolve this error? 🙇

![image](https://github.com/intitni/CopilotForXcode/assets/19220784/f4740089-b5db-4126-8ea9-cef725eb47b4)

<unknown>:0: error: missing required module 'tree_sitter'

**Comment by intitni** [comment]
Change the scheme to anything else that is not an app target.

**Comment by juno12560** [comment]
> Change the scheme to anything else that is not an app target.

thx, it's solved since I changed the scheme to 'Service'~
