### ISSUE TITLE
Xcode extension not visible in System Preferences

### ISSUE THREAD

**Issue by MrMage** [intitni/CopilotForXcode#42]
I am using macOS Monterey and can't see the Xcode extension in "System Preferences > Extensions" — in fact, there is nothing about Xcode anywhere in that pane (I am not on Ventura, so I think I'm looking in the right place).

The rest of the app is set up correctly, I think:
<img width="1012" alt="Screen Shot 2023-03-10 at 13 45 36" src="https://user-images.githubusercontent.com/117466/224319538-e981d9d5-3e5a-4c23-b1e9-2e860023b6cc.png">

Is there a way for me to install the extension manually?

**Comment by intitni** [comment]
There is no other way to install the extension. You can take a look at [this issue](https://github.com/nicklockwood/SwiftFormat/issues/494#issuecomment-547101989) and [this link](https://stackoverflow.com/questions/51648536/xcode-source-editor-option-not-displayed-in-extensions) which look to be solving a similar problem to yours. Or you can try installing another source editor extension from App Store to see if it can enable the menu.

**Comment by MrMage** [comment]
Thank you; calling `lsregister` as mentioned in the issue immediately fixed things for me:

```
$ PATH=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support:"$PATH"
$ lsregister -f /Applications/Xcode.app
```

**Comment by mfbx9da4** [comment]
What version of the app are you using I just installed from brew but I don't see the "Reveal Extension App in Finder" button. I'm on version `Version 0.6.0 (20)`. Is brew behind the latest?
