### ISSUE TITLE
[Bug]: Regression on Esc to Dismiss Suggestions

### ISSUE THREAD

**Issue by cliffordh** [intitni/CopilotForXcode#427]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

This enhancement was implemented but then functionality regressed: https://github.com/intitni/CopilotForXcode/issues/412

### How to reproduce the bug.

After suggestion appears press Escape key. Dialog is not dismissed.

### macOS version

14.3

### Xcode version

15.2

### Copilot for Xcode version

0.30.1

**Comment by intitni** [comment]
It's working for me. Can you check if the toggle is on in the suggestion settings?

**Comment by cliffordh** [comment]
@intitni the toggle was on. I re-toggled, and still not working. Screen capture shows me typing ".c" at the end of a SwiftUI View and getting the Xcode command completion dropdown. The suggestions appear to the right of the context menu. Escape dismisses the context menu but does not dismiss the suggestions. I believe my Xcode settings (also attached) may be the problem...

<img width="1258" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/1755156/93d61084-8ccf-4b41-b0e7-50e4207edc2b">

<img width="817" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/1755156/7a03f30b-8435-419a-8009-7d2047ec62dd">

**Comment by intitni** [comment]
We have the identical settings. Could you please open Console.app and set the filter to "TabToAcceptSuggestion". Let me know what the logs are.

**Comment by cliffordh** [comment]
Which panel in Console? 

<img width="254" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/1755156/95ad4bd0-a4cf-4992-b156-a447a098cb87">

**Comment by intitni** [comment]
Choose your Mac in the devices, and click start streaming

**Comment by intitni** [comment]
If you can see TabToAcceptSuggestion: Activated, please try this build below.

https://github.com/intitni/CopilotForXcode/releases/download/0.1.0/Copilot.for.Xcode.debug.20240129.zip

Show me the logs when you tap "ESC" when there is a suggestion presented. Same filter.

**Comment by cliffordh** [comment]
Same issue. No logs are appearing. Note also that Tab does NOT complete the suggestion any longer, it inserts a tab in the editor instead. It's as if the key listeners are no longer working for the popup.

**Comment by intitni** [comment]
Please try regranting Accessibility API permission to the app

**Comment by cliffordh** [comment]
Accessibility settings toggled.. no effect.. trying a restart!

**Comment by cliffordh** [comment]
Rebooting resolved the issue.
