### ISSUE TITLE
[Bug]: Use "Tab" to auto complete suggestion will cause Xcode editor to jump to most top of the file

### ISSUE THREAD

**Issue by davidhsu1115** [intitni/CopilotForXcode#429]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

When using the "Tab" to auto complete suggestion, It will not maintain at current line, it will jump to the most top line of current file.

### How to reproduce the bug.

Each time using auto complete with "Tab" will cause this issue

### macOS version

13.5.2

### Xcode version

15.1

### Copilot for Xcode version

0.30.1

**Comment by intitni** [comment]
The Copilot menu in XCode is greyed out, the app has to use a fallback solution to accept the suggestions. Please restart XCode. 

And please remember to restart Xcode whenever you update Copilot for Xcode.

**Comment by davidhsu1115** [comment]
The Copilot menu in Xcode is not greyed out, I have restart Xcode, reboot Mac, and restart Copilot as well. Issue still remain

<img width="388" alt="CleanShot 2024-01-31 at 14 06 54@2x" src="https://github.com/intitni/CopilotForXcode/assets/10396887/c2c4d46e-c517-4e80-8732-11b33518e27a">

Thanks

**Comment by intitni** [comment]
Please check the advanced settings in Copilot for Xcode and see that if the “Use Accessibility API to accept suggestion” is on. 

Turn it off if it is.

**Comment by davidhsu1115** [comment]
It's already turned off

![CleanShot 2024-01-31 at 14 12 19@2x](https://github.com/intitni/CopilotForXcode/assets/10396887/5dd0c22f-deaa-4aab-b21d-19f322ac9c3f)

Thanks for the quick reply.

**Comment by intitni** [comment]
Please open Console.app, click start streaming, and set the filter to "Trigger menu item ".

Try to accept a suggestion with tap, let me know if you can see the errors. You can also try to turn off "Trigger command with Accessibility API" to see if it works.

**Comment by davidhsu1115** [comment]
I did not see any error related to "Trigger menu item " in the Console.app. And it appears that turn off "Trigger command with Accessibility API" did not work as well.

**Comment by intitni** [comment]
Please install this version:

https://github.com/intitni/CopilotForXcode/releases/download/0.1.0/Copilot.for.Xcode.debug.20240201.zip

I have added more logs to this build, and removed an Xcode-is-active guard before triggering the command. Please:

- turn "Trigger command with Accessibility API" back on.
- accept a suggestion with tab and show me the logs in the Console.app.
- and capture a screenshot of the content of Editor > Copilot menu.

**Comment by davidhsu1115** [comment]
Oddly this debug version works perfectly fine.

- [x] turn "Trigger command with Accessibility API" back on.
- [x] accept a suggestion with tab and show me the logs in the Console.app.
<img width="1227" alt="CleanShot 2024-02-01 at 14 45 00@2x" src="https://github.com/intitni/CopilotForXcode/assets/10396887/12fb1838-1644-41f5-b506-3e519d82b11f">

- [x] and capture a screenshot of the content of Editor > Copilot menu
<img width="655" alt="CleanShot 2024-02-01 at 14 45 40@2x" src="https://github.com/intitni/CopilotForXcode/assets/10396887/6d1a0b33-692e-43ee-afe6-637bb7b00991">

**Comment by intitni** [comment]
I think it's the Xcode-is-active check is not working as expected. Please give this version a try, if it works, I will release it immediately.

https://github.com/intitni/CopilotForXcode/releases/download/0.1.0/Copilot.for.Xcode.debug.20240201.2.zip

**Comment by intitni** [comment]
I will treat it as "it works".

**Comment by davidhsu1115** [comment]
Works perfectly 🎉

**Comment by intitni** [comment]
Released in 0.30.2. It's the same build you just tried.

**Comment by Nivru** [comment]
I have same issue. As per above suggestion trying to open but it say Not Found

https://github.com/intitni/CopilotForXcode/releases/download/0.1.0/Copilot.for.Xcode.debug.20240201.zip

**Comment by intitni** [comment]
@Nivru Please restart Xcode after an update. This issue has been closed a long time ago, so the debug build has already been removed.

Please check the FAQ is restarting Xcode doesn't help: [FAQ](https://copilotforxcode.intii.com/faq/app-faq/#q-the-editor-jumps-when-i-accept-a-suggestion)

Create a new issue if needed.
