### ISSUE TITLE
[Bug]: github copilot status is not ok,please check if you have a valid github copilot  subscription

### ISSUE THREAD

**Issue by zhongTom** [intitni/CopilotForXcode#430]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

A bug happened!
![image](https://github.com/intitni/CopilotForXcode/assets/20367203/a5d22d12-771a-49a4-b46e-95b5130a152b)
I have authorized it, but I still get an error after refreshing it.
![image](https://github.com/intitni/CopilotForXcode/assets/20367203/720792ec-bd38-4c60-9471-26b97c95adf9)

### How to reproduce the bug.

It just happens!

### macOS version

14.0

### Xcode version

15.0

### Copilot for Xcode version

0.30.1

### Node version

18.0.0

**Comment by intitni** [comment]
It's not a bug. Please go to GitHub.com and check that your subscription to GitHub Copilot is valid.
