### ISSUE TITLE
[Bug]: After the proposal is accepted, the document is rewritten and the accepted proposal code is added

### ISSUE THREAD

**Issue by TBoyLi** [intitni/CopilotForXcode#431]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

A bug happened! After the proposal is accepted, the document is rewritten and the accepted proposal code is added

### How to reproduce the bug.

Choosing to accept the offer will happen
![Uploading CleanShot 2024-02-01 at 12.43.42.gif…]()

### macOS version

14.3

### Xcode version

15.2

### Copilot for Xcode version

0.30.1

### Node version

2

**Comment by intitni** [comment]
?

Please feel free to report in Chinese. And make sure the image is uploaded.

**Comment by TBoyLi** [comment]
@intitni gif 图片无法上传。
<img width="597" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/14815341/675c1b19-246a-4156-b58e-2234b257ee40">
点击accept 时，.m 文件代码会全部重写一下并添加你接受的代码

**Comment by TBoyLi** [comment]
@intitni 给你的感觉就是闪屏了一下。

**Comment by intitni** [comment]
请查看菜单栏 > Editor > Copilot 这个彩蛋是不是失效了，如果是的话请重启 Xcode。

**Comment by intitni** [comment]
如果解决了的话请关闭这个 issue，如果没有解决请关注 #428

**Comment by TBoyLi** [comment]
@intitni 点击提示的accept按钮会全部重写一下并添加你接受的代码，感觉闪屏了一下。但是你用快捷键option+shift+}就不会闪屏。

**Comment by intitni** [comment]
请使用 #428 中的版本看看

同时请开启 Console.app，设置 filter 为 `Trigger menu item`，并点击 start streaming。把点击 accept 按钮后出现的 log 截图给我。

**Comment by TBoyLi** [comment]
点击 accept 按钮并没有日志
<img width="1044" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/14815341/30d26064-eafa-4fe1-bf2b-b4d06d0ecc9a">

**Comment by intitni** [comment]
不好意思我粘错 issue 了，是 #429

**Comment by intitni** [comment]
https://github.com/intitni/CopilotForXcode/releases/download/0.1.0/Copilot.for.Xcode.debug.20240201.2.zip

**Comment by intitni** [comment]
应该已经在 0.30.2 修复了
