### ISSUE TITLE
[Bug]: App freezes on 0.30.2 (or 0.30.1)

### ISSUE THREAD

**Issue by nrbrook** [intitni/CopilotForXcode#432]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

The service locks up since 0.30.2, making it unusable – no suggestions, clicking the widget gets beach ball. Log attached.

[lockup.log](https://github.com/intitni/CopilotForXcode/files/14128290/lockup.log)

**Comment by intitni** [comment]
I don't see any useful information from the log. Which version were you using before the update? I don't think there is any change in 0.30.2 that can cause the app to freeze.

**Comment by nrbrook** [comment]
0.30.1. I have reverted to that version and now it is fine.

**Comment by intitni** [comment]
I only added and removed some checks where a command is triggered to accept a suggestion in 0.30.2. I don't see any reason that can freeze the app.

Let's see if anyone else is experiencing this issue.

**Comment by zenangst** [comment]
I think I've had this issue since 0.30.1.
It comes and goes, I ended up having to kill the extension and restart it to get it working again.

**Comment by intitni** [comment]
Do you think you can use time profiler to check what is running when the app hangs again?

**Comment by zenangst** [comment]
@intitni I'll give it a go the next time it decides to throw a tantrum

**Comment by Romaaan3** [comment]
No suggestions for me as well
Version 0.30.3 
Xcode 15.2
Build version 15C500b

**Comment by intitni** [comment]
@Romaaan3 This issue is not about suggestion. Please try if rebooting the Mac or anything in the FAQ in wiki works. Open a new issue if the issue persists.

**Comment by zenangst** [comment]
@intitni the latest version is causing issues with input lag and keeps beach balling.

I ran time profiler on both the app and the extension services here. Hope that helps.

[CopilotForXcode.trace.zip](https://github.com/intitni/CopilotForXcode/files/14280691/CopilotForXcode.trace.zip)

**Comment by intitni** [comment]
@zenangst I don't see anything wrong in the trace. Could you provide more details like how often is it, what was the last thing you were doing before it happens, etc?

**Comment by zenangst** [comment]
I've had the extension disabled because of the input lag. Tried it a few times today and it freezes up if I open the chat and try to focus on the input field.

**Comment by intitni** [comment]
@zenangst After digging in a little bit, I think the cause is the app is frequently updating the widget location in irrelevant situations. Please give the [0.30.4 beta release](https://github.com/intitni/CopilotForXcode/releases/tag/0.30.4.beta) a try. 

You can update in-app by turning the "Install beta builds" toggle on in the general settings, too.

**Comment by zenangst** [comment]
@intitni gonna take it for a spin today. I'll report back to you!

**Comment by zenangst** [comment]
@intitni so far everything looks dandy. Haven't encountered any beach balls or slowdowns.

**Comment by intitni** [comment]
@zenangst Good to know! Beta 2 has been released and has more tweaks, please give it a try!

**Comment by intitni** [comment]
I think the issue is still here. I have encountered the app freezing just now...It feels like something was blocking the main thread.

**Comment by zenangst** [comment]
Seems a lot better than it was, messaging timeout might be the way to go here if the extension is trying to reach out to a non-responsive app (if that is the case).

**Comment by intitni** [comment]
File closed! It's the package AsyncExtension causing deadlock.

**Comment by intitni** [comment]
The beta build is [submitted](https://github.com/intitni/CopilotForXcode/releases/tag/0.30.5.beta)!

**Comment by intitni** [comment]
Released in 0.30.5
