### ISSUE TITLE
Cannot start copilotforxcode automatically when Xcode Launched

### ISSUE THREAD

**Issue by AnInsomniacy** [intitni/CopilotForXcode#434]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I reinstalled my macOS and  xcodeforcopilot failed to launch itself when i open xcode（it worked perfectly before i reinstall my macOS），i dont know if it is a bug, or a feature which has removed recently. Everything works well, but every time I have to launch copilotfoexocde manually.

### How to reproduce the bug.

It just happens!

### macOS version

13.6.4

### Xcode version

15.2

### Copilot for Xcode version

0.30.2

### Node version

21.6.1

**Comment by intitni** [comment]
<img width="827" alt="Screenshot 2024-02-04 at 21 40 41" src="https://github.com/intitni/CopilotForXcode/assets/793147/49423cdb-7a0a-4e82-853d-f415919af823">

When Copilot for Xcode.app launches for the first time, it will install a launch agent to the system. Please check if Copilot for Xcode is on the list, and make sure the toggle is on.

If it's not on the list, click remove launch agent and then setup launch agents in the app. 

If it's still not working, you can find an old-school solution in Wiki/FAQ to setup the launch agent by hand.

**Comment by AnInsomniacy** [comment]
<img width="751" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/62804262/170a123a-1fa0-49df-bd97-08661fa47dde">
bro it seems has been in the list and I reinstalled the agent in your way, but it seems not working...

**Comment by intitni** [comment]
Hmm, I think it's not about the launch agent. If the launch agent is not working, I believe the issue would become "the app is complaining that it can't connect to the XPC service".

Did you enable the Xcode source editor extension? The source editor extension is responsible for starting the app when Xcode launches.

**Comment by AnInsomniacy** [comment]
dude it worked after a reboot! Thanks for your hard working'😄
