### ISSUE TITLE
[Help Wanted]: How can I apply a Copilot-Enterprise liscense

### ISSUE THREAD

**Issue by kphungry** [intitni/CopilotForXcode#440]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

It seems that the extension doesnot support Copilot-Enterprise liscense. I want contribute some code to help that. But I have no idea where the Copilot-Enterprise document is. I think make some change to the signin part may help. It seems easy if only I can find the document.
I need some help.

**Comment by intitni** [comment]
I am not sure about the enterprise license thing. There is no documentation. But from the source code of [Copilot.vim](https://github.com/github/copilot.vim/), it seems that we can [pass a dictionary about the enterprise license in the settings](https://github.com/github/copilot.vim/blob/1a284014d2e0baf367706a94b2a9ee5fd56fd457/autoload/copilot/agent.vim#L458).

The dictionary was changed a while ago and more changes need to be made in this app. It's hard to explain, so I give it a spin. Please let me know if it works.

https://github.com/intitni/CopilotForXcode/releases/download/0.30.5.beta/Copilot.for.Xcode.github.copilot.enterprise.app.zip

If it doesn't, you can use the pull request as a hint about what to change.

**Comment by intitni** [comment]
Actually the dictionary was changed in 1.19.0 but Copilot for Xcode is still using 1.17.0.

Please try this version instead 

https://github.com/intitni/CopilotForXcode/releases/download/0.30.5.beta/Copilot.for.Xcode.github.copilot.enterprise.2.app.zip

**Comment by MichaelPei** [comment]
> Actually the dictionary was changed in 1.19.0 but Copilot for Xcode is still using 1.17.0.
> 
> Please try this version instead
> 
> https://github.com/intitni/CopilotForXcode/releases/download/0.30.5.beta/Copilot.for.Xcode.github.copilot.enterprise.2.app.zip

I can see and config the Auth Provider URL for enterprise, but I can't see the button "Refresh Configuration for Enterprise and Proxy" in your merge request.

**Comment by intitni** [comment]
@MichaelPei Please try the latest beta build. 0.30.5 beta 2.

**Comment by MichaelPei** [comment]
> @MichaelPei Please try the latest beta build. 0.30.5 beta 2.

Actually I tried both, and the result were same, sorry about don't mention it before.

**Comment by intitni** [comment]
@MichaelPei Chat support is planned, it will be the next thing to work on once I finished the suggestion service updates. You can follow this issue #380 for updates (But I think I will work on Codeium chat first). You can also find a workaround at the bottom of the issue.

**Comment by intitni** [comment]
Released in 0.30.5
