### ISSUE TITLE
Support Mistral API

### ISSUE THREAD

**Issue by cliffordh** [intitni/CopilotForXcode#444]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

I would like to have Mistral API mistral.ai as an additional chat endpoint.

**Comment by intitni** [comment]
I haven't tried it, but according to the [API Reference](https://docs.mistral.ai/api/#operation/createChatCompletion), both the chat completions and embedding API of Mistral.ai are OpenAI compatible. 

Please try to set it up as an OpenAI compatible model and let me know if it works

**Comment by cliffordh** [comment]
@intitni I setup an API key w/ Mistral.ai and they do claim to have an OpenAI compatible API. Although the Test button works when setting up the new endpoint, the chat does not work. I have tried turning off function calling, reducing token sizes, starting a brand new chat, restarting the agent and Xcode. No luck. How can I help debug this?

**Comment by cliffordh** [comment]
┌[MBA13]-(~)-[40%]
└> curl -X "POST" "https://api.mistral.ai/v1/chat/completions" \
     --header 'Content-Type: application/json' \
     --header "Authorization: Bearer $MISTRAL_API_KEY" \
     --data '{
    "model": "mistral-large-latest",
    "stream": true,
    "messages": [
    {
      "content": "Tell me a joke",
      "role": "user"
    }
  ]
  }'
data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":"assistant","content":"","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":"Why","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":" don","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":"'","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":"t","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":" scientists","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":" trust","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":" atoms","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":"?","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":"\n\nBecause","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":" they","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":" make","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":" up","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":" everything","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":"!","tool_calls":[]},"finish_reason":null,"logprobs":null}],"usage":null}

data: {"id":"50a4bcd6a4f3418799eccdb5526de091","object":"chat.completion.chunk","created":1709239334,"model":"mistral-large-latest","choices":[{"index":0,"delta":{"role":null,"content":"","tool_calls":[]},"finish_reason":"stop","logprobs":null}],"usage":{"prompt_tokens":7,"total_tokens":23,"completion_tokens":16}}

data: [DONE]

**Comment by cliffordh** [comment]
Docs here: https://docs.mistral.ai/platform/overview/
Get an API key here: https://console.mistral.ai/

**Comment by intitni** [comment]
Looks like it doesn't allow unknown fields in the request body that were available in an older format of an OpenAI API. I think it's safe now to remove the old fields. I will make the change in the next release.

Disabling function calling works for me.

**Comment by liuqqwwe** [comment]
I've tried the latest code but the problem still hasn't been resolved.

**Comment by intitni** [comment]
@liuqqwwe Mistral.ai doesn't support function/tool calling. You have to turn it off in the chat model settings. I have tested it on the latest development branch. If that is what you were trying, please show me the error. The implementation is at `OpenAIChatCompletionsService.swift`

**Comment by intitni** [comment]
[0.31.0 beta](https://github.com/intitni/CopilotForXcode/releases/tag/0.31.0.beta) has been released with the API change.

After looking at the Mistral.AI API doc again, I noticed that they simply don't support function/tool calling. The tiny model doesn't accept a `tool_call` field. The large model accepts the field but doesn't call any tool.

**Comment by liuqqwwe** [comment]
> @liuqqwwe Mistral.ai doesn't support function/tool calling. You have to turn it off in the chat model settings. I have tested it on the latest develop branch. If that is what you were trying, please show me the error. The implementation is at `OpenAIChatCompletionsService.swift`

I have implemented an interface that complies with the open ai protocol locally and configured the local interface. My interface can be called during chat and has streaming output. However, the interface return content is not displayed in the plug-in, and 【
![Uploading test.png…]()
the support function/tool calling】 has been turned off in the configuration.

**Comment by intitni** [comment]
@liuqqwwe the image is not uploaded. 

Please show me the chat model settings. And if you are hosting the service locally, you should be able to see the errors from the service. Please let me know what the errors are.

**Comment by liuqqwwe** [comment]
data: {"created":1709555697,"model":"gpt-3.5-turbo","id":"42c692a5-f9a9-4f4f-86e8-b3a6e8723ccf","choices":[{"delta":{"content":"Hello","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555697,"model":"gpt-3.5-turbo","id":"998b587f-4d96-41d6-8b7f-320a82de348d","choices":[{"delta":{"content":"!","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555697,"model":"gpt-3.5-turbo","id":"a1c0ebac-5c6d-4d49-89fc-b91b9239c5be","choices":[{"delta":{"content":" How","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555697,"model":"gpt-3.5-turbo","id":"cffcd971-3599-45af-8d99-00aa2052b4d0","choices":[{"delta":{"content":" can","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555697,"model":"gpt-3.5-turbo","id":"b81ce68a-a48c-4fe8-96cd-9833b19f926d","choices":[{"delta":{"content":" I","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555697,"model":"gpt-3.5-turbo","id":"1c7e17bc-6f22-4813-a746-8695411e248c","choices":[{"delta":{"content":" assist","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555697,"model":"gpt-3.5-turbo","id":"7bf7d131-14c1-42b9-b01c-a1ce243f2dc5","choices":[{"delta":{"content":" you","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555697,"model":"gpt-3.5-turbo","id":"ef9e6674-6620-4308-bae8-548387fa8831","choices":[{"delta":{"content":" with","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555697,"model":"gpt-3.5-turbo","id":"795efc2a-187a-410e-9e37-1aa8c0257dbf","choices":[{"delta":{"content":" your","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555697,"model":"gpt-3.5-turbo","id":"c4de8301-63b3-494a-871e-b8172ac1473f","choices":[{"delta":{"content":" Objective","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555697,"model":"gpt-3.5-turbo","id":"f1f96f0f-af34-4224-87c2-16906fb3f63c","choices":[{"delta":{"content":"-C","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555698,"model":"gpt-3.5-turbo","id":"e53c7525-e191-4ead-a35b-f715b4b57e41","choices":[{"delta":{"content":" code","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555698,"model":"gpt-3.5-turbo","id":"2d31d902-f0b1-4cd7-b77f-79be80f1e83a","choices":[{"delta":{"content":" today","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555698,"model":"gpt-3.5-turbo","id":"619b0bcc-082b-4e68-9a13-458d630492a1","choices":[{"delta":{"content":"?","role":null,"tool_calls":[]},"index":0,"finish_reason":null,"logprobs":null}],"object":"chat.completion.chunk"}


data: {"created":1709555698,"model":"gpt-3.5-turbo","id":"619b0bcc-082b-4e68-9a13-458d630492a1","choices":[{"finish_reason":"stop","index":0,"delta":{"content":null,"role":null,"tool_calls":[]},"logprobs":null}],"object":"chat.completion.chunk"}


this is the local api log，But there is no answer in the dialog box, only question。

![image](https://github.com/intitni/CopilotForXcode/assets/5780515/e6776bae-ced4-418c-8f75-75d7bda2493c)

**Comment by liuqqwwe** [comment]
> @liuqqwwe the image is not uploaded.
> 
> Please show me the chat model settings. And if you are hosting the service locally, you should be able to see the errors from the service. Please let me know what the errors are.

![image](https://github.com/intitni/CopilotForXcode/assets/5780515/c8123a65-3aad-4ce2-983c-92827f5a9e86)

The test of the chat model setting was successful. No error message was found, but the chat reply was always empty. Where can I see more logs?

**Comment by intitni** [comment]
@liuqqwwe Looks like it's not about Mistral API.

The response format looks correct to me. The app will log decoding errors to Console.app under subsystem:com.intii.CopilotForXcode category:Service. If nothing is displayed, there can be a decode error, or that the app doesn't receive the response. What tool are you using for the local server?

**Comment by intitni** [comment]
@liuqqwwe not this decode error. I mean Codable decode error. Actually, I don't think it's a decode error. Please share the tool that you are using for the local server.

**Comment by intitni** [comment]
@liuqqwwe If you can't share the tool, I will not be able to test it for you. I have tested several OpenAI-compatible APIs and all of them worked. So I suspect that your implementation may be incorrect or not OpenAI-compatible. 

Since it's not actually about Mistral AI support, if you need more help, please open a new issue.

**Comment by liuqqwwe** [comment]
> @liuqqwwe If you can't share the tool, I will not be able to test it for you. I have tested several OpenAI-compatible APIs and all of them worked. So I suspect that your implementation may be incorrect or not OpenAI-compatible.
> 
> Since it's not actually about Mistral AI support, if you need more help, please open a new issue.

I simplified the python implementation of the tool and can run it offline. The new question link is as follows
https://github.com/intitni/CopilotForXcode/issues/449

**Comment by liuqqwwe** [comment]
> > @liuqqwwe If you can't share the tool, I will not be able to test it for you. I have tested several OpenAI-compatible APIs and all of them worked. So I suspect that your implementation may be incorrect or not OpenAI-compatible.
> > Since it's not actually about Mistral AI support, if you need more help, please open a new issue.
> 
> I simplified the python implementation of the tool and can run it offline. The new question link is as follows #449

You solved my problem. It seems to be my oversight. I did not observe that the first content returned by Azure contains the role field. Thank you so much

**Comment by intitni** [comment]
Released in 0.31.0
