### ISSUE TITLE
[Bug]: When using OpenAI compatible chat, the response is truncated after 1024 characters

### ISSUE THREAD

**Issue by czottmann** [intitni/CopilotForXcode#445]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I'm using v0.30.5 with one of the models from OpenRouter.ai. Generally, it works fine, but the chat responses are cut at 1024 characters, usually mid-sentence.

### How to reproduce the bug.

Set up a new chat model:

Format: OpenAI Compatible
Base URL: https://openrouter.ai/api
Model name: phind/phind-codellama-34b
Max tokens: 16000

The latter two are exchangeable, other values make no difference.

![CleanShot 2024-03-01 at 18 02 56@2x](https://github.com/intitni/CopilotForXcode/assets/1501/14811d01-ecfb-4825-be6d-1cb28e53e70c)

Configure Copilot to use the chat model, ask for a detailed answer about your code.

### macOS version

14.3.1

### Xcode version

Version 15.2 (15C500b)

### Copilot for Xcode version

0.30.5

**Comment by intitni** [comment]
After doing some searches, I think the context window of this model is 4096.

**Comment by czottmann** [comment]
You're right, but as I've said, it doesn't make a difference. But I did some more digging, and now in my local tests w/ LM Studio etc. it seems like the 1kB response limit is maybe an OpenRouter thing?

Sorry to waste your time, @intitni.

**Comment by intitni** [comment]
I don't know, Copilot for Xcode doesn't set a limit in the response length. Maybe they have a default value or something. 

It can also be that the prompt is too long. You can try to lower the memory field in the chat settings, and use a smaller value for the max focused code in the code scope settings.

**Comment by intitni** [comment]
There is a section about token limit in the [OpenRouter docs](https://openrouter.ai/docs#frameworks), looks like it can be different for users. 

Token Limits
Some users may have too few credits on their account to make expensive requests. OpenRouter provides a way to know that before making a request to any model.
To get the maximum tokens that a user can generate and the maximum tokens allowed in their prompt, add authentication headers in your request to https://openrouter.ai/api/v1/models:

```
type Model = {
  id: string;
  pricing: {
    prompt: number;
    completion: number;
  };
  context_length: number;
  per_request_limits: {
    prompt_tokens: number;
    completion_tokens: number;
  };
};
```

I am not sure if I understand it correctly.

**Comment by czottmann** [comment]
Thanks, appreciate it! I'm closing this ticket now, as it's an iss-me, not an iss-you. 😅
