### ISSUE TITLE
[Bug]: Didn't handle the case where the stream response doesn't provide a role.

### ISSUE THREAD

**Issue by liuqqwwe** [intitni/CopilotForXcode#449]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I have implemented an interface that complies with the open ai protocol locally and configured the local interface. My interface can be called during chat and has streaming output. However, the interface return content is not displayed in the plug-in, and 【the support function/tool calling】 has been turned off in the configuration.

test python api
[chatapitest.py.zip](https://github.com/intitni/CopilotForXcode/files/14482963/chatapitest.py.zip)

streemming response run sucess  in vscode plugin
![image](https://github.com/intitni/CopilotForXcode/assets/5780515/a3834f88-338c-483f-bace-b1d6e34e2181)

setting sucess
![image](https://github.com/intitni/CopilotForXcode/assets/5780515/53da0e11-f376-4880-b785-69a85115e787)

chat and no response
![image](https://github.com/intitni/CopilotForXcode/assets/5780515/3e041c07-f687-4b81-92d7-455952857723)

### How to reproduce the bug.

run test python api  
set config like the screenshot
chat

### macOS version

mac m1 

### Xcode version

Version 15.0.1 

### Copilot for Xcode version

Version 0.30.5 (328)

**Comment by intitni** [comment]
Please try adding `Transfer-Encoding: chunked` to the response header.

**Comment by liuqqwwe** [comment]
> Please try adding `Transfer-Encoding: chunked` to the response header.

[chatapitest.py.v2.zip](https://github.com/intitni/CopilotForXcode/files/14483235/chatapitest.py.v2.zip)

![image](https://github.com/intitni/CopilotForXcode/assets/5780515/62cddddd-52a2-481c-b25b-28a66cdb3e2f)

It didn't work after I tried

**Comment by intitni** [comment]
The reason is the `role` is always nil in your stream reply, and we are not handling this case.

**Comment by intitni** [comment]
Even though I don't feel like calling it a bug, but yes, give it a default value is more robust.

**Comment by intitni** [comment]
Released in 0.31.0
