### ISSUE TITLE
[Bug]：The operation couldn't be completed. (LanguageServerProtocol.ServerError error 13.)

### ISSUE THREAD

**Issue by wisepmlin** [intitni/CopilotForXcode#452]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

A bug happened!The operation couldn't be completed. (LanguageServerProtocol.ServerError error 13.)
<img width="703" alt="截屏2024-03-05 19 55 20" src="https://github.com/intitni/CopilotForXcode/assets/74945717/2519a62d-d597-425e-8ac3-d33c167ab926">

### How to reproduce the bug.

It just happened!

### macOS version

14.4

### Xcode version

15.2

### Copilot for Xcode version

1.19.2

**Comment by intitni** [comment]
Please check the FAQ section for more details. https://github.com/intitni/CopilotForXcode/wiki/Frequently-Asked-Questions#github-copilot

If the issue persist, please provide a screenshot of the settings and the logs you have observed in the Console.app (Please make sure the filter is set according to the FAQ)
