### ISSUE TITLE
[Help Wanted]: No API Key?

### ISSUE THREAD

**Issue by Visual-Studio-Coder** [intitni/CopilotForXcode#453]
### Before Reporting

- [x] I have checked FAQ, and there is no solution to my issue
- [x] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I want help!
<img width="452" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/78756662/56e9495a-ceed-4762-8f04-bda02e32e2f8">

**Comment by intitni** [comment]
I think the message is very clear that you didn't provide an OpenAI API key. Please check the [README.md](https://github.com/intitni/CopilotForXcode) and the [FAQ](https://github.com/intitni/CopilotForXcode/wiki/Frequently-Asked-Questions) for details

**Comment by Visual-Studio-Coder** [comment]
But im using copilot? i shouldn't need a key for that?

**Comment by intitni** [comment]
@Visual-Studio-Coder That's explained in both the README and the FAQ. 

Q: Can I use the GitHub Copilot Chat

A: It's under investigation and no ETA available yet. [#380](https://github.com/intitni/CopilotForXcode/issues/380)

If you want to use GitHub Copilot in chat, you can check #380 for a workaround.

**Comment by Visual-Studio-Coder** [comment]
ok thank you very much. please let me know when Copilot Chat is available!
