### ISSUE TITLE
[Bug]: Previous/Next suggestion command dismisses the suggestion

### ISSUE THREAD

**Issue by intitni** [intitni/CopilotForXcode#457]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

A bug happened!

### How to reproduce the bug.

It just happened!

**Comment by intitni** [comment]
Released in 0.31.2

**Comment by nippach** [comment]
@intitni
Please update CodeiumForXcode. It has this bug too.
