### ISSUE TITLE
[Enhancement]: Have scope-type chat inherit main chat model

### ISSUE THREAD

**Issue by czottmann** [intitni/CopilotForXcode#460]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

It'd be nice if there was a setting in Feature → Chat to make the scope-type chats inherit the main chat model configuration. Something like an additional option in the dropdowns, "Use main chat model".

![CleanShot 2024-03-13 at 19 23 21@2x](https://github.com/intitni/CopilotForXcode/assets/1501/86087790-5f07-4a06-b100-d3a9fde8dc00)

(Unless I'm misunderstanding the "None" option in the dropdowns, and it does exactly that?)

**Comment by intitni** [comment]
Setting it to none means it doesn't have a preference in model selection, which also means inheriting the main model.

**Comment by czottmann** [comment]
Cool, thank you, that answers my question. As a suggestion: I'd make that more clear in the UI, it's not entirely obvious, I think.
