### ISSUE TITLE
[Bug]: GitHub Copilot Language Server install issue.

### ISSUE THREAD

**Issue by Dark-Existed** [intitni/CopilotForXcode#463]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

The GitHub Copilot Language Server continuously loading, and when click install, a error report.
![Snipaste_2024-03-14_09-29-26](https://github.com/intitni/CopilotForXcode/assets/24956657/9ad6373f-23a3-4b55-8362-a31d1ad1f5d6)
![Snipaste_2024-03-14_09-36-20](https://github.com/intitni/CopilotForXcode/assets/24956657/1de897ec-be7a-41a0-b96c-855ff654f0eb)
![Snipaste_2024-03-14_09-29-50](https://github.com/intitni/CopilotForXcode/assets/24956657/3aa70ad9-0346-4a81-b66d-773af590535e)

### How to reproduce the bug.

When I update to 0.31.0 from some one old version.

### macOS version

14.3.1

### Xcode version

15.2

### Copilot for Xcode version

0.31.0 & 0.31.1

**Comment by intitni** [comment]
Please delete ~/Library/Application Support/com.intii.CopilotForXcode/GitHub Copilot and try again.

**Comment by Dark-Existed** [comment]
It works, thx!
