### ISSUE TITLE
[Bug]: Copilot Overlay is stretched when Xcode is in full screen and mission control is shown

### ISSUE THREAD

**Issue by jamesyorke** [intitni/CopilotForXcode#468]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

Copilot overlay is stretched

![Screenshot 2024-03-21 at 12 43 37](https://github.com/intitni/CopilotForXcode/assets/7203530/f7f61259-933e-443e-8144-24aabd8e9702)

### How to reproduce the bug.

1. Open Xcode with copilot for xcode open
2. Put Xcode in full screen mode
3. Go to mission control aka., F3 button on keyboard
4. See Stretched Copilot for Xcode overlay

### macOS version

14.4

### Xcode version

15.3

### Copilot for Xcode version

0.31.2

**Comment by intitni** [comment]
Released in 0.33.3
