### ISSUE TITLE
[Bug]: File page jumped after accepting suggestions

### ISSUE THREAD

**Issue by sypyyy** [intitni/CopilotForXcode#471]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

After installing the newest update, when I accept the suggestion by copilot, the file jumps to a wrong offset. This never happened in old version. BTW I am using regression suggestion, not hotkey.

### macOS version

13.5

### Xcode version

15.0.1

### Copilot for Xcode version

0.31.2

**Comment by intitni** [comment]
It's an [Xcode bug](https://github.com/intitni/CopilotForXcode/wiki/Frequently-Asked-Questions#q-the-editor-jumps-when-i-accept-a-suggestion). Please restart Xcode after updating the app.
