### ISSUE TITLE
[Bug]:  Chat window off screen

### ISSUE THREAD

**Issue by tgunr** [intitni/CopilotForXcode#474]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I am using Kodium for Xcode on a dual display system connected to my computer. Recently I had changed the resolution of one of the monitors and then changed it back to 1920 by 1080. Now, when using Codium, I see the little widget, either at the bottom or next to the text, as set by the application Clicking on the widget the chat window never appears. The active window goes inactive, indicating the chat window appeared but according to what I can find debugging, it is set to  minus 1361 on the and is somewhere off screen. 

I tried uninstalling and then reinstalling that didn't work. I tried changing the resolution of the displays. I tried disconnecting and reconnecting displays one at a time.

So somewhere in the code it is not being clamped to the screen it is located on.

### How to reproduce the bug.

Not sure how to reproduce it, but I believe it had something to do with changing the resolution on one of the monitors. I downloaded the Xcode project and it compiled okay but I get lost in the filer window positioning. 

### macOS version

14.4

### Xcode version

15.3

### Copilot for Xcode version

0.30.5

**Comment by intitni** [comment]
The Codeium for Xcode fork only supports the suggestion feature. Clicking the widget won't open the chat window.
