### ISSUE TITLE
[Help Wanted]: xcode editor extension does not show up

### ISSUE THREAD

**Issue by juno12560** [intitni/CopilotForXcode#475]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I want help!

I have rebuilt the project locally and completed the signing and notarization process. The plugin works perfectly on my development machine.

But after other users install it, the Xcode editor extension does not show up in their Xcode. What do I miss that is preventing the Xcode extension from being distributed and used by others? Thank you in advance for your help.
![image](https://github.com/intitni/CopilotForXcode/assets/19220784/662b3698-3757-403b-a52c-98a41ef12ac5)

**Comment by intitni** [comment]
It's probably either an Xcode bug or a macOS bug. Please search online for a solution. I do remember seeing it in another issue, but I am not sure which one.

**Comment by zenangst** [comment]
Try renaming Xcode.app to Xcode2.app and then back again, that usually works to kick-start so that the extension shows up.

**Comment by juno12560** [comment]
I resolved the issue by setting the ENABLE_HARDENED_RUNTIME to no for the CopilotForXcode target and then repackaging and resigning the app. 
I'm not clear on the root cause, but this fixed the problem.
