### ISSUE TITLE
[Enhancement]: Detect system-wide proxy setting

### ISSUE THREAD

**Issue by ifsheldon** [intitni/CopilotForXcode#476]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Hi! Great work! Currently we need to set proxy in the setting of the app, but can it automatically detect system-wide proxy settings? When turning on VPNs, many of them will automatically set up proxy settings like proxy config file URL.

**Comment by intitni** [comment]
I don't think we need to do anything to support system proxy, it just works. If you need to use GitHub Copilot behind a self-signed certificate, please read #455

**Comment by ifsheldon** [comment]
I see. I thought if I am behind a proxy, I need to manually set it in the app setting, but it just works when I unset those proxy settings. It seems the app will just use system-wide proxy settings by default.
