### ISSUE TITLE
Syntax highlighting fails to highlight Objective-C and shows only `undefined`

### ISSUE THREAD

**Issue by jianAjian** [intitni/CopilotForXcode#48]
only undefined in widget ,but complete when i click accpet button

**Comment by intitni** [comment]
Sorry, I don't understand what you mean. Do you have a screenshot or something? You can use Chinese if you want.

**Comment by jianAjian** [comment]
哦, 试了下swift 是可以提示的, OC下小组件里面只有一个undefined,但是点击accept可以填充进去

**Comment by intitni** [comment]
可以提供一下相关的代码吗

**Comment by intitni** [comment]
不用了，我猜是代码高亮的语言传错了

**Comment by jianAjian** [comment]
ok

**Comment by intitni** [comment]
Released in 0.8.5-Update 1. But let's keep it open until I release 0.8.6 or 0.9.0.

**Comment by jianAjian** [comment]
👍
