### ISSUE TITLE
[Enhancement]: Add support for custom Google Generative AI Base URL

### ISSUE THREAD

**Issue by borrrrring** [intitni/CopilotForXcode#481]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

I want a feature! Because it keeps prompting "User location is not supported for the API use." in my country, I need to build a proxy to use it normally.

**Comment by intitni** [comment]
I was hoping Google could do it but apparently, they won't. 

https://github.com/google/generative-ai-swift/issues/76

**Comment by borrrrring** [comment]
Could you please use the [REST API] (https://ai.google.dev/tutorials/rest_quickstart) to call Google Generative AI? This way, we can customize the Base URL. Thanks a lot. @intitni

**Comment by intitni** [comment]
Using the REST API is too tricky. I have already made a fork of generative-ai-swift to support changing the base URL.

**Comment by intitni** [comment]
Released in 0.32.0 beta2

**Comment by intitni** [comment]
1.5 models only works for API version v1beta according to this issue https://github.com/google/generative-ai-python/issues/227#issuecomment-2046665032

Maybe we should just wait until they release it.

The SDK is only responsible for composing the request and handling the response. Behind the scene it still calls the REST API.

**Comment by intitni** [comment]
Since you are already using a proxy, you can try simply rewriting the v1 in the url to v1beta.

**Comment by borrrrring** [comment]
<img width="978" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/12905116/33a0c0cb-6771-48a1-b878-410c4487173e">
<img width="1366" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/12905116/444bc462-a0d8-4261-a33d-e68d87f93edb">
<img width="1480" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/12905116/7e3d666f-a41e-4ae1-8c4a-a826fe656993">
The SDK is only responsible for composing the request and handling the response. Behind the scene it still calls the REST API.
This is what I found.

**Comment by intitni** [comment]
Beta is marked as beta for a reason. The API may not be stable and can break the whole feature when it changes. I can add a feature to allow users to specify the api version in settings. It will be included in the coming major release.

**Comment by intitni** [comment]
Released in 0.32.0
