### ISSUE TITLE
[Bug (Beta)]: checkbox 'Automatically Check for Update' does not refresh

### ISSUE THREAD

**Issue by juno12560** [intitni/CopilotForXcode#482]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

UI Bug: Interface Does Not Refresh After Ticking "Automatically Check for Update"

When ticking the "Automatically Check for Update" checkbox within the settings page, the interface fails to refresh immediately. It only refreshes when I select another option.

### How to reproduce the bug.

Reproducible Bug.

### macOS version

14

### Xcode version

15.2

### Copilot for Xcode version

0.31.3

**Comment by intitni** [comment]
Released in 0.32.0
