### ISSUE TITLE
[Help Wanted]: Enable/disable copilot for specific project

### ISSUE THREAD

**Issue by mkowalski87** [intitni/CopilotForXcode#490]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

Hi,
Due to security policies in the company, in some of the projects I'm allowed to use copilot but in others it is forbidden.
Currently, when I want to use the plugin I have to enable it in system settings and disable it when I'm switching to a different project.

Is there any option to make this process easier? 

Maybe some kind of config file in to project directory?

**Comment by intitni** [comment]
Please not that it only works for the suggestion feature. The app will check if the project root URL is or is a sub directory of an item in the exception list, if it is, the suggestion feature will be enabled.

**Comment by mkowalski87** [comment]
@intitni Thank you. This is exactly what I was looking for
