### ISSUE TITLE
[Bug]:  Update Error! The update is improperly signed and could not be validated.

### ISSUE THREAD

**Issue by ianhlavats** [intitni/CopilotForXcode#493]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I tried to update the Copilot for Xcode when prompted and got the following error message "Update Error! The update is improperly signed and could not be validated. Please try again later or contact the developer."

<img width="372" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/3005952/9f904249-4f7c-4d9c-9230-fd0c3de8d395">

It said to contact the app developer so I'm reaching out.

I tried to download the zip file directly from the GitHub release page and Chrome blocked the download, however it does not block 0.32.0:

<img width="326" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/3005952/3e799d83-5313-4465-8a85-9309c6b46f34">

### How to reproduce the bug.

* Install 0.32.0 
* Try to upgrade to 0.32.2

After closing both Xcode and Copilot for Xcode, and also restarting my Mac, I'm still unable to run the installer without the error.

### Relevant log output

```shell
There is no crash report because there is no crash.
```

### macOS version

14.4.1

### Xcode version

15.2

### Copilot for Xcode version

0.32.0

**Comment by intitni** [comment]
Thanks for reporting, it's now fixed! I think it's time to make up my mind to stop updating the appcast file by hand (•̀_•́).
