### ISSUE TITLE
[Feature Request]: Add ability to toggle Real-time Suggestions

### ISSUE THREAD

**Issue by zenangst** [intitni/CopilotForXcode#496]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

Using the Real-time Suggestions menu item doesn't actually toggle real-time suggestions.
The menu item is invoked but nothing happens, the toggle is still of in the CoPilot app and they are not toggled inside Xcode.

### How to reproduce the bug.

Disable Real-time Suggestions in CoPilot app
Invoke Real-time Suggestions using the menu item in Xcode

### macOS version

14.4.1 (23E224)

### Xcode version

Version 15.3 (15E204a)

### Copilot for Xcode version

0.32.2

**Comment by intitni** [comment]
This command is not meant to be called by users. 

> Commands called by the app:
> 
> Real-time Suggestions: Call only by Copilot for Xcode. When suggestions are successfully fetched, Copilot for Xcode will run this command to present the suggestions.
> Prefetch Suggestions: Call only by Copilot for Xcode. In the background, Copilot for Xcode will occasionally run this command to prefetch real-time suggestions.

**Comment by intitni** [comment]
Which implementation do you think is better?

- As a command from the Xcode menu, works only when the editor in Xcode is active
- As a shortcut provided by Copilot for Xcode which available when Xcode is active

**Comment by intitni** [comment]
Released in beta 0.33.1

**Comment by zenangst** [comment]
Fantastic! 🤩

**Comment by intitni** [comment]
Released in 0.33.1
