### ISSUE TITLE
[Bug]: After logout can't sign in again 

### ISSUE THREAD

**Issue by amir-ardalanuk** [intitni/CopilotForXcode#497]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I have an issue related to token expiry. I tried to log out and sign in again, but I received an error message while trying to log in again.

https://github.com/intitni/CopilotForXcode/assets/12419118/d4cbf8d5-18d0-4837-80bb-dc53a7960b03

### How to reproduce the bug.

Try to logout and then login again in Copilot section

### macOS version

14.0

### Xcode version

15.0.1

### Copilot for Xcode version

0.32.2

**Comment by intitni** [comment]
This error happens inside the GitHub Copilot language server. It looks like it's was making a network request, but the response body was not a valid JSON. Please follow [this issue](https://github.com/intitni/CopilotForXcode/issues/492#issuecomment-2063071210) to see what the actual errors are.

You can also try deleting `~/Library/Application Support/com.intii.CopilotForXcode/GitHub Copilot` and setting it up again.

**Comment by amir-ardalanuk** [comment]
@intitni Unfortunately I can't fix this issue, I've even removed the app and try to reinstall it but the old configuration was set on the app

**Comment by intitni** [comment]
Please show me the logs or I can't help you.

I am not a GitHub Enterprise user so I don't know how it should be setup. Are you sure the auth provider URL is correct?

**Comment by amir-ardalanuk** [comment]
Yes I used it before but suddenly it has not worked anymore
Now i try to set a proxy on my copilot client the sign in item works but I’m getting some error logs related to certificate host ip

**Comment by intitni** [comment]
If using a proxy works, do you think it can be the DNS or the hosts file are pointing the GitHub domain name to a wrong IP address?

**Comment by amir-ardalanuk** [comment]
In advance, I really appreciate to helping us 
It is fixed, I think the biggest problem is back to IP and proxy because I just re-start the Mac and also cleaned all proxy from the client and it works now 
@intitni Thank you so much 
<img width="878" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/12419118/2e1add51-ed40-4c33-89ad-a87aec231885">
