### ISSUE TITLE
[Bug]: Accept suggestion with Tab doesn't work when the code contains emojis

### ISSUE THREAD

**Issue by wujianbotju** [intitni/CopilotForXcode#498]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I purchased a Plus license and activated Plus feature, but accept suggestion with Tab doesn't work. I have checked key bindings in Xcode preference, whether I set it or not, it doesn't work. When I pressed down Tab key, 4 white spaces were inserted to my code.
I want help!

**Comment by intitni** [comment]
Please first make sure the "Accept Suggestion with Tab" toggle is on. Restart the Mac if it's already on, it can be a macOS bug.

If restarting the Mac doesn't fix this issue for you, please open Console.app, click start streaming and set the filter to 

category:Service
any:CopilotForXcodeExtensionService

Let me know if you see the following logs when you activate an Xcode window:

<img width="1206" alt="Screenshot 2024-04-18 at 23 08 59" src="https://github.com/intitni/CopilotForXcode/assets/793147/12078a63-fc9d-4b43-be31-933985d4a2f0">

**Comment by BlueSkinMouse** [comment]
@intitni I figured it out. There is nothing with toggle or macOS, it is emoji text. If your code contains any emoji text, "Accept suggestion with Tab" won't work.
For example, if I wrote one line of code:
fileprivate var profileBgView: UIImageView!          /// 🎓
"Accept suggestion with Tab" stopped working.
Please fix it.

**Comment by intitni** [comment]
Interesting, I will convert it into a bug.

**Comment by intitni** [comment]
Released in 0.32.3 beta

**Comment by intitni** [comment]
Released in 0.32.3
