### ISSUE TITLE
Light mode support

### ISSUE THREAD

**Issue by j-f1** [intitni/CopilotForXcode#50]
Right now the app always uses dark UI. For those of us who prefer light mode would it be possible to add a toggle that switches the UI between light, dark, and matching the system setting?

**Comment by intitni** [comment]
Oh, I completely forgot that Xcode has a light mode.

**Comment by intitni** [comment]
Released in 0.8.6

**Comment by j-f1** [comment]
Looks beautiful, thanks!

**Comment by ICULikeMac** [comment]
Light mode is awesome, now everything in my dev environment is using light mode - thank you!
