### ISSUE TITLE
[Help Wanted]: Adding documentation for Objective-C doesn't work

### ISSUE THREAD

**Issue by milkyNik** [intitni/CopilotForXcode#501]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

Adding documentation for Objective-C doesn't work

<img width="494" alt="Screenshot 2024-04-30 at 19 44 57" src="https://github.com/intitni/CopilotForXcode/assets/10409551/95180aed-555f-454b-8b3f-fc0f0042290a">

**Comment by intitni** [comment]
Fixed in 0.32.3
