### ISSUE TITLE
CoPilot status "Not authorized", but unclear what that means

### ISSUE THREAD

**Issue by sgoehler** [intitni/CopilotForXcode#51]
Hello, I just successfully installed Copilot (didn't have success with earlier versions), however, despite having entered the code for Copilot and having authorized the extension on GitHub, I see "not authorized".
I currently don't pay for CoPilot and unfortunately my trial expired (despite having never used it). So it might be that. But paying $10 for just finding out if it's this, or something else (and waiting for a fix, and losing these $10 for it) is no good option in my opinion.

Can you make clear what this message means? Maybe also in the FAQ?

**Comment by intitni** [comment]
You have to type something meaningful to let GitHub Copilot generate suggestions for you.

For example, type `func mergeSort`, then try to get suggestions again.

**Comment by sgoehler** [comment]
Thanks! I did so, but as said, nothing happened.

I tried again, and it seems like my expectations on how it should work differ from how it works: I had put the cursor on the function name previously. 
When I had moved it to the function body, meaning between {}, it worked. 

Maybe it's helpful to either change that behaviour or explicitly showing that something went wrong (and maybe what).

**Comment by intitni** [comment]
That's how GitHub Copilot works, it completes the code for you, based on the context and your text cursor position. There is nothing I can do about it. You can turn on real-time suggestions to let it generate suggestions when you stop typing, then the behavior should make more sense.

**Comment by sgoehler** [comment]
All right, these are just suggestions, I come from application design, and implementing such things help to make things easier for the user - but it's up to you of course how you realize things. 
Thanks for the quick help!

**Comment by objectivec** [comment]
> I figured out how to do it and it was easy — could I suggest you add on the readme after: 
> 
It looks like there is no way to add default key bindings to commands, but you can set them up in Xcode settings > Key Bindings.

In the search window, type: copilot
when the list appears, click on the blank keybinding cell and enter the code as shown below.

— Hopefully we can make this as easy and effective to use as possible.
Thanks for your wonderful work to support Copilot in Xcode!

One question/perhaps feature request — Copilot labs seems to be the next generation of Copilot — right now only Visual Studio Code supports it. It adds commands for:
Explain your code
Document Code
Improve
Make code Robust

Thanks again, Yesterday I spent the day using Copilot in Xcode, and it was great!

Mark Nelson
