### ISSUE TITLE
[Bug]: Xcode Indexing breaks when Copilot for Xcode extension is activated.

### ISSUE THREAD

**Issue by craig-miller** [intitni/CopilotForXcode#512]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?
Xcode package indexing freezes

### How to reproduce the bug.
git clone of repository
Delete Derived data of previous builds
Fire up Xcode
Package indexing begins.  Freezes/hangs with a 2 in the status window.

### macOS version

Sonoma 14.4.1

### Xcode version

15.3

### Copilot for Xcode version

0.33

**Comment by intitni** [comment]
Does deleting Copilot for Xcode.app solves the issue for you? If so, does disabling enhanced workspace from the advanced settings solves the issue? The app does access data in the derived data but it shouldn't interfere the indexing process.

Please also provide a spindump of Xcode when it freezes.

<img width="528" alt="Screenshot 2024-05-16 at 08 56 30" src="https://github.com/intitni/CopilotForXcode/assets/793147/409fcc30-d844-4ed3-b6ae-d5de227e34e5">

**Comment by craig-miller** [comment]
Deleting and reinstalling appears to have fixed the issue.
