### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dennipahmah** [intitni/CopilotForXcode#515]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

Getting this error in the chat window.  No idea where to put the API key.

You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.

### How to reproduce the bug.

Went through all of the install steps and it all seemed to install correctly.  Opened a chat window from the Editor menu and sent just "test" in the chat window and it gave the above message.

### macOS version

14.5 Beta (23F5064f)

### Xcode version

Version 15.4 (15F31d)

### Copilot for Xcode version

Version 0.33.0 (376)

**Comment by intitni** [comment]
Please read the Setting Up Chat Feature section of README for details
