### ISSUE TITLE
[Bug]:  real-time Suggestion  do not working properly.

### ISSUE THREAD

**Issue by yuhuajun100** [intitni/CopilotForXcode#516]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

The software enables real-time Suggestion.
As the code was being written, a feature was triggered, but no advice was given.
If this feature is triggered manually, any recommendations are still given。

https://github.com/intitni/CopilotForXcode/assets/15060885/91e3ca3a-92a4-4498-bcc8-ac3eea3b28f9

### How to reproduce the bug.

It just happened!

### macOS version

14.5

### Xcode version

xcode 15.4

### Copilot for Xcode version

0.31.3

**Comment by intitni** [comment]
Please try updating the app to the latest version.

If the issue persists, please let me know:
- Does the circular widget animate when you stop typing (which indicates that the app is fetching suggestions)?
- Do the widgets update their position when the Xcode window moves?

**Comment by yuhuajun100** [comment]
Codeium for Xcode 0.31.3 is currently the newest version available.
Xcode app  15.4 is currently the newest version available.
Watch the video below

Uploading 20240520-135611.mp4…

**Comment by intitni** [comment]
Please simply use Copilot for Xcode. Codeium for Xcode is just a subset of the app. 

Moving text cursor will not trigger realtime suggestion and will cancel all previous requests, please don't move the text cursor by clicking in the video.

**Comment by nenseso** [comment]
I have the same problem only use Copilot for Xcode. 
version: 0.33.0.
circular widget animates when I stop typing
widgets aslo updates their position when the Xcode window moves.
![image](https://github.com/intitni/CopilotForXcode/assets/16931967/dac837cf-3e9d-4802-825f-8b8b77782be4)
![image](https://github.com/intitni/CopilotForXcode/assets/16931967/3576b541-68c5-4bf1-bfda-6d5472b0b2af)
![image](https://github.com/intitni/CopilotForXcode/assets/16931967/ce279241-f2e4-4b94-a1c1-b358c8485d2b)

**Comment by intitni** [comment]
@nenseso If you saw the animation that means the app was working. Maybe there was something wrong with the GitHub Copilot language server.

Please turn on verbose log. Open Console.app and click start streaming, set the filter to `category:GitHubCopilot`. Try to trigger real-time suggestion and see what the logs are. If you don't see any log, restart the service app.

**Comment by nenseso** [comment]
> @nenseso If you saw the animation that means the app was working. Maybe there was something wrong with the GitHub Copilot language server.
> 
> Please turn on verbose log. Open Console.app and click start streaming, set the filter to `category:GitHubCopilot`. Try to trigger real-time suggestion and see what the logs are. If you don't see any log, restart the service app.

Thanks for your response! I wasn’t sure what happened, but today when I upgraded my version to 0.33.1 beta, everything started working fine.
Here's what I did:
1.  Uninstall version 0.33.0.
2.  Downloaded version 0.33.1 beta  and placed it in the Applications folder.
3. Removed Accessibility API permission and re-added it again.
4. open `Copilot for Xcode.app` again
5. open Xcode
After these steps, it worked! Thanks again for your help. Next time, I'll know to check Console.app for GitHub Copilot logs.
![image](https://github.com/intitni/CopilotForXcode/assets/16931967/96abd68a-4fa1-4a91-b81e-545acb10d67b)

**Comment by arigatou1985** [comment]
I started experiencing the same issue just a few days ago. It used to work perfectly say for 2 ~ 3 weeks ago. In the Console.app, I found the following message when the suggestion stops working: 

> Try getting suggestions again: Language server error: Server error: -32603 non-abort error on ghost text request nil

Restarting Xcode and Copilot for Xcode together will bring back the suggestion prompts, but after a few minutes, the suggestions will stop again, i.e., no suggestion prompt during coding.
I tried to re-install Copilot for Xcode, I even tried it with Xcode 15.4, 15.3, the issue persists.

**Comment by intitni** [comment]
@arigatou1985 This error happens when the the network request failed inside the language server. It's hard to tell what was going on.

Please try setting the console filter to 
```
any:CopilotForXcodeExtensionService
category:ProtocolTransport
```

Hopefully we can get more information from it.

**Comment by intitni** [comment]
@arigatou1985 By the way, are you using self-signed certificates? I found that it can happen when I was using MITM on the GitHub Copilot domain names. It works at the beginning but stops working later.

**Comment by arigatou1985** [comment]
> @arigatou1985 This error happens when the the network request failed inside the language server. It's hard to tell what was going on.
> 
> Please try setting the console filter to
> 
> ```
> any:CopilotForXcodeExtensionService
> category:ProtocolTransport
> ```
> 
> Hopefully we can get more information from it.

I tried to filter console logs using the same exact two filters above, but didn't get anything at all when the suggestion prompt stops working. Only console message relevant are from single filter: process CopilotForXcodeExtensionService, regarding server error as mentioned above.

I'm sure my computer doesn't have self-signed certificates doing MITM related work when I experience the issue. GitHub copilot works perfectly fine continuously in my Visual Studio Code.

From what I experimented with so far, when I restart Xcode, and copilot for Xcode, after about 4 minutes, suggestions prompt will stop working.

**Comment by intitni** [comment]
@arigatou1985 Oh you have to turn on verbose log in the GitHub Copilot settings then restart the app.

**Comment by intitni** [comment]
@arigatou1985 sadly there is no useful information. It’s really weird that you can't see and logs from the ProtocolTransport category. Can you constantly get the errors you showed me after it stops working?

Would you mind trying the following:

- Turn the verbose log toggle off and back on. 
- Kill the node processes created by CopilotForXcodeExtensionService in Activity Monitor and try to get suggestions again.

**Comment by intitni** [comment]
I will submit a build later to always post the logs no matter what the state of the toggle is later.

**Comment by arigatou1985** [comment]
> @arigatou1985 sadly there is no useful information. It’s really weird that you can't see and logs from the ProtocolTransport category. Can you constantly get the errors you showed me after it stops working?
> 
> Would you mind trying the following:
> 
> * Turn the verbose log toggle off and back on.
> * Kill the node processes created by CopilotForXcodeExtensionService in Activity Monitor and try to get suggestions again.

I get those logs every time when suggestions stop working.
I tried to turn verbose log off and on. Restarted the copilot for xcode a couple of times. Also tried to kill the node processes created by CopilotForXcodeExtensionService. Unfortunately none of them helped.

**Comment by intitni** [comment]
@arigatou1985 https://github.com/intitni/CopilotForXcode/releases/download/0.1.0/Copilot.for.Xcode.app.debug.20240530.2023.zip

If you still can't see the logs, I honestly don't know what else we can do. You can still try:

- Deleting the app completely including ~/Library/Application Support/com.intii.CopilotForXcode and reinstall.
- Change "run node with" to other values.
- MitM the requests to copilot-proxy.githubusercontent.com to see what is going on. You may need to turn on "Load certificates in keychain".
- Run the app in Xcode. You need to run both the ExtensionService target and the CommunicationBridge target. You can set a break point to /Tool/Sources/GitHubCopilotService/LanguageServer/GitHubCopilotService.swift:408. Hopefully you can see the logs in the debug area.

**Comment by arigatou1985** [comment]
> @arigatou1985 https://github.com/intitni/CopilotForXcode/releases/download/0.1.0/Copilot.for.Xcode.app.debug.20240530.2023.zip
> 
> If you still can't see the logs, I honestly don't know what else we can do. You can still try:
> 
> * Deleting the app completely including ~/Library/Application Support/com.intii.CopilotForXcode and reinstall.
> * Change "run node with" to other values.
> * MitM the requests to copilot-proxy.githubusercontent.com to see what is going on. You may need to turn on "Load certificates in keychain".
> * Run the app in Xcode. You need to run both the ExtensionService target and the CommunicationBridge target. You can set a break point to /Tool/Sources/GitHubCopilotService/LanguageServer/GitHubCopilotService.swift:408. Hopefully you can see the logs in the debug area.

I tried to delete the directory for complete uninstallation. Didn't help.
I used a web proxy app to observe the communication between my computer to github, didn't find anything related to copilot-proxy.githubusercontent.com, but only copilot-telemetry.githubusercontent.com. 
I will try to set up and run the project in xcode. It might take more time, I'll come back if I find anything interesting.
BTW, on another intel iMac, with latest MacOS and Xcode, and copilot for xcode, all works perfectly without any issue. The problem only occurs on my M3 chip macbook pro.

**Comment by intitni** [comment]
@arigatou1985 Thank you! Let me know if you need any help.

**Comment by arigatou1985** [comment]
Thanks to your previous hints. I've experimented more with Node settings, and discovered that running node with `/usr/bin/env` always lead to no suggestions prompt issue few minutes after starting copilot and Xcode, while `/bin/bash/ -i -l` works reliably. I switched between these options many times and tried very thoroughly and can confirm the problem roots from the node selection setting.
<img width="645" alt="Screenshot 2024-06-01 at 07 29 56" src="https://github.com/intitni/CopilotForXcode/assets/1049512/c6ed7d2f-68fc-4e5f-a268-eb176e0ac75e">

**Comment by pawel-movelab** [comment]
Im having the same problem as described by OP. None of the suggestions in this thread helps. Icon shows for a seconds and disappears without any suggestion of code snippet. Really annoying issue.

**Comment by intitni** [comment]
@pawel-movelab please provide your settings in screenshots, logs, node version so that I can help you. 

You can get the logs by turning on verbose log in the GitHub Copilot settings, restart the service app if, open Console.app, click start streaming, and set the filter to one of the following

```
any:CopilotForXcodeExtensionService
category:ProtocolTransport
```

Or 

```
any:CopilotForXcodeExtensionService
category:GitHubCopilot
```

You mentioned that the widget appears and disappears, did it crash? Or you have turned on “Hide circular widget”?

**Comment by pawel-movelab** [comment]
> You mentioned that the widget appears and disappears, did it crash? Or you have turned on “Hide circular widget”?
Yes, I had that option checked. I unchecked it but no help. 

I tried to get these logs but not getting any.

➜  ~ node --version
v22.2.0
![Screenshot 2024-06-03 at 14 52 11](https://github.com/intitni/CopilotForXcode/assets/162117878/b8f1cd7a-48ff-486b-a011-406

Launching service app keeps on showing on the app screen: 
![Screenshot 2024-06-03 at 14 52 53](https://github.com/intitni/CopilotForXcode/assets/162117878/37251fe4-54d0-4a3d-a24d-624d1a5db25c)
401680a39)

![Screenshot 2024-06-03 at 14 53 25](https://github.com/intitni/CopilotForXcode/assets/162117878/b2ab1699-27ad-4eb6-b036-32a6cfdf7eb7)

![Screenshot 2024-06-03 at 14 53 46](https://github.com/intitni/CopilotForXcode/assets/162117878/0762b74f-3c4f-4039-8378-8674a203afff)

**Comment by intitni** [comment]
> Thanks to your previous hints. I've experimented more with Node settings, and discovered that running node with `/usr/bin/env` always lead to no suggestions prompt issue few minutes after starting copilot and Xcode, while `/bin/bash/ -i -l` works reliably. I switched between these options many times and tried very thoroughly and can confirm the problem roots from the node selection setting.
> 
> <img width="645" alt="Screenshot 2024-06-01 at 07 29 56" src="https://github.com/intitni/CopilotForXcode/assets/1049512/c6ed7d2f-68fc-4e5f-a268-eb176e0ac75e">
> 
> 

Glad it worked. The key difference between these options is that different configuration files will be used. 

I am not sure about `/usr/bin/env`,`/bin/bash/ -i -l` will use your bashrc and the last one will use the one for your default shell. Maybe there are some settings generating conflicts to the node process or the language server.

**Comment by intitni** [comment]
@pawel-movelab If you don't see any log, I suspect that you are having a similar issue to that of arigatou1985. The language server is not launched properly. 

Do you mind setting up the debug server of the app by running 
`defaults write ~/Library/Group\ Containers/5YKZ4Y3DAW.group.com.intii.CopilotForXcode/Library/Preferences/5YKZ4Y3DAW.group.com.intii.CopilotForXcode.plist TestUtilityBaseURL "https://copilotforxcode-testutility.intii.com"`

Once you trigger a suggestion, I will be able to see the logs of it. I can read the prompt, too so please make sure don't do I on your real code.

You can unset it later with
`defaults delete ~/Library/Group\ Containers/5YKZ4Y3DAW.group.com.intii.CopilotForXcode/Library/Preferences/5YKZ4Y3DAW.group.com.intii.CopilotForXcode.plist TestUtilityBaseURL`

If I can't see the logs either, it's probably the issue I just mentioned. Please try different "Run node with" options, and take a look into your `~/bashrc` or `~/zshrc` or other similar files.

**Comment by pawel-movelab** [comment]
> @pawel-movelab If you don't see any log, I suspect that you are having a similar issue to that of arigatou1985. The language server is not launched properly.
> 
> Do you mind setting up the debug server of the app by running `defaults write ~/Library/Group\ Containers/5YKZ4Y3DAW.group.com.intii.CopilotForXcode/Library/Preferences/5YKZ4Y3DAW.group.com.intii.CopilotForXcode.plist TestUtilityBaseURL "https://copilotforxcode-testutility.intii.com"`
> 
> Once you trigger a suggestion, I will be able to see the logs of it. I can read the prompt, too so please make sure don't do it on your real code.
> 
> You can unset it later with `defaults delete ~/Library/Group\ Containers/5YKZ4Y3DAW.group.com.intii.CopilotForXcode/Library/Preferences/5YKZ4Y3DAW.group.com.intii.CopilotForXcode.plist TestUtilityBaseURL`
> 
> If I can't see the logs either, it's probably the issue I just mentioned. Please try different "Run node with" options, and take a look into your `~/bashrc` or `~/zshrc` or other similar files.

I just made few attempts to trigger it in empty repo I created. Can you see it?

**Comment by intitni** [comment]
@pawel-movelab I saw the logs, it looks like the language server does recognize the file. Please turn on enable Xcode Inspector debug menu in the advanced settings and show me the content in the menu. Also let me know if it works in a git enabled project.
<img width="1297" alt="Screenshot 2024-06-03 at 21 16 47" src="https://github.com/intitni/CopilotForXcode/assets/793147/1d9bd3e6-5afd-4934-897c-398b49632710">

**Comment by pawel-movelab** [comment]
![Screenshot 2024-06-03 at 15 21 43](https://github.com/intitni/CopilotForXcode/assets/162117878/71fddc53-c11f-478d-bc60-6389e937a9c2)

**Comment by pawel-movelab** [comment]
![Screenshot 2024-06-03 at 15 21 43](https://github.com/intitni/CopilotForXcode/assets/162117878/946762fc-b724-4e59-9ef1-d00c00c7a9b8)

**Comment by intitni** [comment]
@pawel-movelab Sorry I have no idea. Everything looks correct to me. If the language server can't find the file, it's very likely that the open file notification sent to the language server is failed or not fired. If it failed, you should see the logs.

I still don't understand why you can't see the logs. Do you mind trying the Console.app again but this time set the filter to only `category:GitHubCopilot`, open a new tab in Xcode, make some changes and see if there is any open or change requests?

If you still can't see them, all I can suggest is to build and run the app in Xcode. You need to run both the ExtensionService target and the CommunicationBridge target. You may want to look at `/Tool/Sources/GitHubCopilotService/GitHubCopilotExtension.swift:39` for the open file request and `/Tool/Sources/GitHubCopilotService/LanguageServer/GitHubCopilotService.swift:362` for the get suggestion request.

**Comment by pawel-movelab** [comment]
I am getting hits in Console app with the filter you suggested: 

Try getting suggestions again: Language server error: Server error: -32602 Document for URI could not be found: file:///user/file.swift, URIs of the known document are:  nil

**Comment by intitni** [comment]
@pawel-movelab I can get the same error if I disable the files and folders permission, do you want to check that?
<img width="483" alt="Screenshot 2024-06-03 at 21 44 45" src="https://github.com/intitni/CopilotForXcode/assets/793147/194aeb5d-2ce7-4ef6-b826-d17aa4716c25">

**Comment by pawel-movelab** [comment]
> @pawel-movelab I can get the same error if I disable the files and folders permission, do you want to check that? <img alt="Screenshot 2024-06-03 at 21 44 45" width="483" src="https://private-user-images.githubusercontent.com/793147/336096660-194aeb5d-2ce7-4ef6-b826-d17aa4716c25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjI2NDcsIm5iZiI6MTcxNzQyMjM0NywicGF0aCI6Ii83OTMxNDcvMzM2MDk2NjYwLTE5NGFlYjVkLTJjZTctNGVmNi1iODI2LWQxN2FhNDcxNmMyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxMzQ1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzdhNDgzNzA4Y2VlYzZjMzUxYjk3NDE0YTRjZGZkZjM1NWI2OTJlZGRmYTRlYTU0YWI4NWM4YzliNWU3OWUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZzHogWvMLFWIuvbnZ4xLaCCqmt5CTorNfBRUWjHln50">
> 
> System settings > Privacy and Security > Files and Folders

After enabling access to all locations and restarting both Xcode and Copilot for Xcode apps it started to work! Thank you! 🥳 

Btw I just noticed that tab aceepting suggestions in playground won't work.

**Comment by intitni** [comment]
@pawel-movelab Only in playground?

**Comment by pawel-movelab** [comment]
Yes, only there. In Xcode works normally

**Comment by intitni** [comment]
@pawel-movelab Can you accept the suggestions in other ways, for example the buttons?

**Comment by intitni** [comment]
@pawel-movelab That's super weird. Does it work if you create a swift file in the Sources folder in the playground and try them out? Can you upload the playground file and let me know which folder/path it is in?

**Comment by intitni** [comment]
@pawel-movelab Oh yeah, I forgot there are a lot of logs about tab to accept were added to the latest build. Please set the Console.app filter to category:Debug, let me know what you observed.

**Comment by pawel-movelab** [comment]
@intitni I tested again and after our yesterday fix it works as well in Playgrounds! Thanks a lot for your fast help and replies!
