### ISSUE TITLE
Copilot for Xcode GUI scrolling [BUG]

### ISSUE THREAD

**Issue by KieranConlon** [intitni/CopilotForXcode#52]
The current GUI app has a scrollable view for the entire window which causes content to scroll behind the app's Close/Minimise/Full-Screen buttons.  This is not usual behaviour for a macOS app.

To re-create the bug...
1. Resize the GUI height to be small enough for content to go beyond the bottom of the app window.
2. Scroll the view
3. Content at the top of the GUI goes behind the app Close/Minimise/Full-Screen buttons.

![image](https://user-images.githubusercontent.com/33759139/225386629-60e5b221-7572-48e0-a674-564bb0c12a4a.png)

**Comment by intitni** [comment]
Released in 0.8.6
