### ISSUE TITLE
[Enhancement]: 为什么Chat不能直接使用Copilot呢？

### ISSUE THREAD

**Issue by iamnanyi** [intitni/CopilotForXcode#523]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

I want a feature!

**Comment by intitni** [comment]
Please check #380 for details.

**Comment by Asweety** [comment]
我现在使用的XcodePilot 可以通过Copilot来使用Chat功能
