### ISSUE TITLE
[Bug]: Language server error

### ISSUE THREAD

**Issue by MaksimBezdrobnoi** [intitni/CopilotForXcode#527]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

After update, Copilot doesn't work
<img width="548" alt="image" src="https://github.com/intitni/CopilotForXcode/assets/85101110/1afe37ae-3aeb-4ea9-989b-34850cb66dc1">

### How to reproduce the bug.

1. Open Xcode
2. Try to use copilot 

### macOS version

14.5

### Xcode version

15.3

### Copilot for Xcode version

0.33.1

**Comment by intitni** [comment]
0.33.1 introduced a breaking change as stated in the change log.

> [!IMPORTANT]  
>**This version does not support the old versions of the language server**. 
>
> Though the language server will be upgraded automatically on launch, if you find that it's not working, please make sure to update the language server in the app and restart the service app. Some breaking changes are introduced, please let me know if it's still working correctly for you.

**Comment by MaksimBezdrobnoi** [comment]
Yes, you're right. Everything is OK after the manual update

**Comment by gpambrozio** [comment]
Getting this as well. When you say "update the language server in the app" or "manual update", what do you mean? I don't see any way to update the language server anywhere in the app. Thanks

**Comment by intitni** [comment]
@gpambrozio It’s in the GitHub Copilot settings. If there is no update available, that means it’s already been updated but the app is not using it yet, please restart the service app.
