### ISSUE TITLE
[Help Wanted]: I can't sign out from copilot account

### ISSUE THREAD

**Issue by jan-kmenta** [intitni/CopilotForXcode#530]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

Hi I need to sign out and sign in under another account (need change personal account to bussineess account).
I've tried go to _Service -> GitHub Copilot -> GitHub Copilot Language Server_ here is **Sign Out** button but it seem it does nothing. I've also tried reinstal app but after installing I'm still logged. How could I change copilot account?

**Comment by intitni** [comment]
Please try deleting ~/Library/Application Support/com.intii.CopilotForXcode/GitHub Copilot/support

**Comment by cbarnes22** [comment]
I have the same error but don't have that file. any tips?
\

**Comment by intitni** [comment]
@cbarnes22 please try removing the parent directory

**Comment by cbarnes22** [comment]
@intitni Apologies, I should have been clearer. I don't even have a file/folder under ~/Library/Application Support/ named com.intii.CopilotForXcode. Still having this issue but I don't even know where the application data is stored if I don't have that folder.

**Comment by intitni** [comment]
@cbarnes22 The configurations are inside that folder. If you are installing other forks of this project, the folder name may become different. If the fork is released by me, the folder with has the prefix "com.intii".

You can also double click on the node process in Activity Monitor to see what files have been accessed.

<img width="916" alt="Screenshot 2024-06-24 at 15 20 47" src="https://github.com/intitni/CopilotForXcode/assets/793147/4a549f2d-af3b-4004-ae6e-d664cc433c30">

**Comment by intitni** [comment]
Fixed in 0.33.5
