### ISSUE TITLE
[Bug]: real-time suggestion doesn't show properly

### ISSUE THREAD

**Issue by milanhorvatovic** [intitni/CopilotForXcode#539]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

The real-time suggestion provides only one suggestion, even the popup shows that there are more options to choose. Each suggestion has the same preview. 
<img width="586" alt="Screenshot 2024-06-17 at 23 55 35" src="https://github.com/intitni/CopilotForXcode/assets/6715938/a7f41e58-7bb8-43fe-86a3-ae8a831fc55d">
<img width="586" alt="Screenshot 2024-06-17 at 23 55 39" src="https://github.com/intitni/CopilotForXcode/assets/6715938/48e378f3-af7e-42d4-a521-b288ca93ada6">
It looks like accepting a suggestion applies the right version, but it's really annoying to won't be able to validate all options before applying it.

### How to reproduce the bug.

It just happened!

### Relevant log output

```shell
Output from Console application:

Subsystem: com.intii.CopilotForXcode
Category: Codeium
Error: The operation couldn’t be completed. (Swift.CancellationError error 1.)
```

### macOS version

14.5 (23F79)

### Xcode version

15.4 (15F31d)

### Copilot for Xcode version

0.33.3

**Comment by intitni** [comment]
Fixed in 0.33.4
