### ISSUE TITLE
Add button to service app menu to open Copilot for Xcode app [ENHANCEMENT]

### ISSUE THREAD

**Issue by KieranConlon** [intitni/CopilotForXcode#54]
Suggestion to simplify access to the Copilot for Xcode.app by adding a "Open Copilot for Xcode" option to the service app's menu bar.

Equivalent to running:
``` bash
open "/Applications/Copilot for Xcode.app"
```

Mock-up of new menu...
![image](https://user-images.githubusercontent.com/33759139/225387723-a320056d-ec5e-4a65-8322-6a8a02dc8150.png)

**Comment by SNQ-2001** [comment]
@intitni 
I would like to work on this Issue.

**Comment by intitni** [comment]
@SNQ-2001 That would be great. The menu is defined in AppDelegate of the ExtensionService target. Please try to derive the path to the host app from the `Bundle.main.xxxxPath`, do not hard code the path if possible.
