### ISSUE TITLE
[Enhancement]: Claude 3.5 Sonnet support

### ISSUE THREAD

**Issue by mdoukmak** [intitni/CopilotForXcode#545]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Claude 3.5 sonnet support
`claude-3-5-sonnet-20240620`

**Comment by skaplan** [comment]
I'm getting an error. Presumably because Anthropic now requires a version header:    `--header "anthropic-version: 2023-06-01" `

**Comment by intitni** [comment]
Released in 0.33.5
