### ISSUE TITLE
[Bug]: Gemma 2 responses broken

### ISSUE THREAD

**Issue by cliffordh** [intitni/CopilotForXcode#548]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I am using Gemma 2 9B via Ollama. When chatting the first part of the response is ok, but then degrades as shown into just showing boxes.

<img width="794" alt="Screenshot 2024-06-28 at 7 13 30 AM" src="https://github.com/intitni/CopilotForXcode/assets/1755156/be4e93ac-73b6-45ab-8287-522709bbf569">

### How to reproduce the bug.

Setup Gemma 2 for Ollama "ollama run gemma2". Configure a chat model for Gemma 2. I have token size set to 16384. I have 5 message history turned on for the Chat feature and this custom prompt (Note "Reply in Markdown"): You are an AI programming assistant. You understand and respond in English. You are using iOS 17 to develop a SwiftUI health and wellness application using HealthKit and WidgetKit with a companion Apple Watch app. Your reply should be clear, concise and logical. Use best practices. Do not use deprecated functions (below iOS 17). Do NOT force unwrap optionals. Reply in Markdown with brief code explanations. 

### macOS version

14.5

### Xcode version

15.4

### Copilot for Xcode version

0.33.4

**Comment by intitni** [comment]
Hello, it seems to work for me. What is the temperature in your settings? Are you using Ollama 0.1.47?
