### ISSUE TITLE
[Help Wanted]: Disable TAB for accept suggestions

### ISSUE THREAD

**Issue by foxfollow** [intitni/CopilotForXcode#556]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

Hi dear devs
Please could anyone help me to disable `Accept Suggestions`  on `Tab` but leave on `⌥}` or any binding I configure.
The problem is I want to use Xcode IDE to Code Completion default, but instead copilot gives me a big part of code that I do not need with errors.

For example I miss clicked with name of class I want to use and on previous version (or without copilot) I use tab to correct my syntax, but now copilot give me a code that is incorrect(because there no `UIImageiew`), please tell how to disable `Tab` but have an option to use `Accept Suggestions`  on `⌥} `, I really could find anything info that helped me.
<img width="1239" alt="Знімок екрана 2024-07-12 о 01 32 51" src="https://github.com/user-attachments/assets/01a883a8-41b9-40e8-a043-647969689f63">

**Comment by intitni** [comment]
The toggle is in the suggestion settings.
