### ISSUE TITLE
[Enhancement]: Rewrite text (or code)

### ISSUE THREAD

**Issue by cliffordh** [intitni/CopilotForXcode#559]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

I want a feature! I'd like a feature that lets me highlight text and with a right-click or keyboard shortcut, popup a window with AI suggested replacements. This could be helpful for writing text (copy) and broaden the usefulness of this code focused utility. This idea is inspired by the Microsoft Edge browser feature that allows you to right-click selected text and "Rewrite with Copilot".

For example: 

<img width="668" alt="image" src="https://github.com/user-attachments/assets/078564f1-bf5d-4a6a-9423-e0b6cb1e37c4">

<img width="864" alt="image" src="https://github.com/user-attachments/assets/c167f6af-3952-4e6d-884a-5b9011b82d47">

**Comment by intitni** [comment]
You can already rewrite selected content with the prompt to code feature. If you need it to rewrite immediately with custom prompts, you can set up a custom command in the host app, custom shortcut is supported, too.
