### ISSUE TITLE
[Bug]: 0.33.6 not available in the in-app-update

### ISSUE THREAD

**Issue by core-code** [intitni/CopilotForXcode#560]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

any reason we cannot update to the new version in the app?

https://raw.githubusercontent.com/intitni/CopilotForXcode/main/appcast.xml

it is stuck at 0.33.5

### How to reproduce the bug.

n/a

### Relevant log output

```shell
n/a
```

### macOS version

any

### Xcode version

any

### Copilot for Xcode version

0.33.5

**Comment by intitni** [comment]
The app is no longer using the appcast in the repo as described in the changelog of 0.33.5. If you are using the prebuilt version, you should get the update correctly.

**Comment by core-code** [comment]
thanks!
