### ISSUE TITLE
[Bug]: Key bindings no longer work on 0.33.7

### ISSUE THREAD

**Issue by YoavGro** [intitni/CopilotForXcode#564]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

A bug happened!

Updated to latest version 0.33.7 and key bindings are no longer working

### How to reproduce the bug.

It just happened!
Update to latest and try to keybind any action

### macOS version

14.3.1 (23D60)

### Xcode version

15.2

### Copilot for Xcode version

0.33.7

**Comment by intitni** [comment]
The key binding is mostly handled by Xcode. Please check if the menu is grayed out.

> Q: The Copilot menu grays out after updating Copilot for Xcode. Or the keybindings stop working.
> 
> A: If it only happens after updating Copilot for Xcode, It's an expected behavior, please restart Xcode to to let it reload the extension to finish the update. If it happens in other cases, please open an issue to let me know.
