### ISSUE TITLE
[Enhancement]: Be able to place the chat in a tab Xcode

### ISSUE THREAD

**Issue by HamzaModiFace** [intitni/CopilotForXcode#568]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

In the same way VSCode does it, it would be nice to be able to place the chat in a tab here and open it:

<img width="457" alt="image" src="https://github.com/user-attachments/assets/94373069-33a8-461e-9aa4-e41a51b726ef">

**Comment by intitni** [comment]
It's not possible.
