### ISSUE TITLE
[Bug]: The error when clicking the "extensions" button.

### ISSUE THREAD

**Issue by liuqqwwe** [intitni/CopilotForXcode#572]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I compiled the project from the source code myself, and when I click the "extensions" button, an error occurs and the "extensions Manager" window does not pop up. I cannot select the local model as the continuation model. I understand that this is a free feature, and it seems from the code that this window is located in the ProService module. Could this part also be included in the open-source code, or can the local code inference be integrated into this project?

The error when clicking the extensions button is:
Connection to extension service error: The operation couldn't be completed. (XPCShared.XPCRequestNotHandledError error 1.)

![20240902-200050](https://github.com/user-attachments/assets/f99eb38f-43c0-4e07-a5d4-ea78ee5f5551)

### How to reproduce the bug.

1. build project
2. move app to application doc
3. setup launch agent and  run service 
4. click “extensions” button， and  show error toast ：
Connection to extension service error: The operation couldn't be completed. (XPCShared.XPCRequestNotHandledError error 1.)

### macOS version

14.5

### Xcode version

15.4

### Copilot for Xcode version

0.33.8

**Comment by intitni** [comment]
The extension part is not open sourced.

**Comment by intitni** [comment]
The extension thing has nothing to do with local models. I am not sure what you mean by local code inference, though. 

If you wish to use the open source version with a custom suggestion service, you will need to implement a SuggestionFeatureProvider.

**Comment by liuqqwwe** [comment]
> The extension thing has nothing to do with local models. I am not sure what you mean by local code inference, though.扩展的事情与本地模型无关。不过，我不确定本地代码推断是什么意思。
> 
> If you wish to use the open source version with a custom suggestion service, you will need to implement a SuggestionFeatureProvider.如果您希望使用带有自定义建议服务的开源版本，则需要实现 SuggestionFeatureProvider。

I would like some advice on how to implement SuggestionFeatureProvider. After carefully reviewing the code, I have found there are two methods for code suggestions:

Using CustomSuggestionServiceForCopilotForXcode. The process of installing extensions involves code surrounded by #if canImport(ProService). This part of the code is missing, and if I try to generate suggestions directly in Workspace+SuggestionService.swift's generateSuggestions, the adoption fails, and the generated content cannot be inserted into the editor. I suspect that this functionality might be in the code surrounded by canImport(ProService).

Using services like GitHub Copilot and Codeium. They install a language_server file to start as a service, which should have the functionality to update the Xcode editor.

I am not very familiar with Swift, and this is what I have been able to deduce so far. I have not fully understood the reasonable way to implement SuggestionFeatureProvider. Could you please elaborate on your approach to implementing SuggestionFeatureProvider? Thank you very much.

**Comment by intitni** [comment]
What I mean is that you have to implement a type that conforms to `SuggestionFeatureProvider` and returns it in `SuggestionService.service`. Or you can reuse the `BuiltinExtensionSuggestionServiceProvider` and implement a built-in extension. You can use the `GitHubCopilotExtension` as an example.

For the actual implementation of the built-in extension, please simply copy and paste the code from CustomSuggestionServiceForCopilotForXcode. You may have to make some changes to fit it in the code.
