### ISSUE TITLE
[Bug]: Completion not working for my repo due to company policy, and an update to the API is required.

### ISSUE THREAD

**Issue by difujia** [intitni/CopilotForXcode#575]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

If we are using 1st party extensions, they must be updated to a newer version to allow Copilot completion to work. Here's a reference:
![image](https://github.com/user-attachments/assets/114328cb-03fe-4bc4-9dd6-957919a8c729)

### How to reproduce the bug.

It just happened!

**Comment by intitni** [comment]
It won't be release immediately. 

But the latest language server is compatible with the current code so you can simply download the `https://github.com/github/copilot.vim/tree/release/dist` and replace the folder `~/Library/Application\ Support/dev.com.intii.CopilotForXcode/GitHub\ Copilot/executable/copilot/dist`

**Comment by intitni** [comment]
Released in 0.34.0 beta 3

**Comment by intitni** [comment]
Released in 0.34.0
