### ISSUE TITLE
[Enhancement]: 是否有望支持deepseek的FIM 补全

### ISSUE THREAD

**Issue by ivoidcat** [intitni/CopilotForXcode#582]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

你好，我用这个扩展很久了，非常好用。感谢作者的付出！
最近一直在使用deepseek来代替chatgpt，因为接口很便宜，而且速度可以快，编码质量也很棒，我看他现在出了一个FIM 补全，不知能否加到本扩展中
https://platform.deepseek.com/api-docs/zh-cn/guides/fim_completion

**Comment by intitni** [comment]
建议把这个 pr 提到这个项目：

https://github.com/intitni/CustomSuggestionServiceForCopilotForXcode

看起来它的 API 和 FIM model - Mistral 的格式很像，你可以试一试能不能直接用

**Comment by ivoidcat** [comment]
> 建议把这个 issue 提到这个项目：
> 
> https://github.com/intitni/CustomSuggestionServiceForCopilotForXcode
> 
> 看起来它的 API 和 FIM model - Mistral 的格式很像，你可以试一试能不能直接用

好的大佬我试下

**Comment by intitni** [comment]
Moved to [https://github.com/intitni/CustomSuggestionServiceForCopilotForXcode/issues/15](another repo)
