### ISSUE TITLE
Floating Panel Position Issue <Bug??>

### ISSUE THREAD

**Issue by cr2s367067** [intitni/CopilotForXcode#59]
![Screenshot 2023-03-15 at 5 44 08 PM](https://user-images.githubusercontent.com/47702598/225944173-154a8e76-e72b-4525-b8e6-e5a882f60867.png)
![Screenshot 2023-03-17 at 11 12 37 PM](https://user-images.githubusercontent.com/47702598/225945153-05c9d3de-6420-4b2f-b1e3-fc173ae23421.png)

The suggestion panel view will clip by the screen by the code in full-screen view.
How can I reset the position of the panel?

**Comment by okanro** [comment]
I guess this occurs when display setting changes default to "More Space"

**Comment by cr2s367067** [comment]
> Maybe open a split editor, switch to it and move back? Or click anywhere that would change the focus area and come back.
![Uploading Screenshot 2023-03-18 at 9.39.27 A
![Screenshot 2023-03-18 at 9 39 19 AM](https://user-images.githubusercontent.com/47702598/226076375-80798520-7531-4548-9eb4-549bdc3f9b89.png)
M.png…]()


I was in the signal editor, and it just sticks at the left side of the screen. I try the split view, it will occur in the left view.
I try to remove the agent and reset it. The panel is still in a weird place on the screen.🥲

**Comment by cr2s367067** [comment]
> I guess this occurs when display setting changes default to "More Space"

I checked the setting is the default.

**Comment by intitni** [comment]
> > I guess this occurs when display setting changes default to "More Space"
> 
> 
> 
> I checked the setting is the default.

Please provide the steps to reproduce the bug.

**Comment by cr2s367067** [comment]
<img width="597" alt="Screenshot 2023-03-21 at 3 50 11 PM" src="https://user-images.githubusercontent.com/47702598/226545406
![Screenshot 2023-03-21 at 4 05 43 PM](https://user-images.githubusercontent.com/47702598/226548218-8acb6923-4903-4e4b-ad06-78730f2873aa.png)
-b0daf183-138b-44a3-accc-9f0a4dfc6d96.png">
@intitni I finally found the reason why the floating panel is always showing on the left of the screen.  Arrange Display will force the circle floating view to appear on the left of the external screen if I switch the external screen to the left like the pic below.
<img width="448" alt="Screenshot 2023-03-21 at 4 04 25 PM" src="https://user-images.githubusercontent.com/47702598/226547993-538e3a11-52a6-4497-b22c-d7fc3bdd0053.png">
The floating view will change to the right.
![Screenshot 2023-03-21 at 4 05 18 PM](https://user-images.githubusercontent.com/47702598/226548155-d48a8ff8-d185-4102-86fc-7179e6ef9a65.png)

**Comment by cr2s367067** [comment]
<img width="397" alt="Screenshot 2023-03-21 at 4 07 14 PM" src="https://user-images.githubusercontent.com/47702598/226548490-43e845aa-c041-4c09-a7bb-f25519691568.png">
![Screenshot 2023-03-21 at 4 07 28 PM](https://user-images.githubusercontent.com/47702598/226548538-491f2218-111f-4a42-bfae-57f1f3c4e89d.png)

@intitni I finally found the reason why the floating panel is always showing on the left of the screen. Arrange Display will force the circle floating view to appear on the left of the external screen if I switch the external screen to the left like the pic below. 
<img width="341" alt="Screenshot 2023-03-21 at 4 07 47 PM" src="https://user-images.githubusercontent.com/47702598/226548580-30c46d89-59a0-4b50-803d-e73cc84c9f80.png">
![Screenshot 2023-03-21 at 4 07 57 PM](https://user-images.githubusercontent.com/47702598/226548613-c89a8387-3681-4d28-8dbd-7134f8fbd7e4.png)
The floating view will appear on the right of the screen.

**Comment by intitni** [comment]
May have been fixed in 0.9.1. Please reopen if the bug still exists.

**Comment by Gittmitticity** [comment]
Uploading IMG_0388.MOV…

**Comment by intitni** [comment]
> Uploading IMG_0388.MOV…

Were you trying to upload a video indicating that the bug still exists?
