### ISSUE TITLE
[Enhancement]: Choose non default model in chat

### ISSUE THREAD

**Issue by peteroettl** [intitni/CopilotForXcode#595]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

I'm using Claude and OpenAI models and want sometimes to try to chat with the non-default chat model to see if the other model can provide better solutions.

Event though I can define two models for the chat, I don't see a way to change the model from the chat window.

**Comment by intitni** [comment]
You can right-click the tab title to change the model in the context menu.

**Comment by peteroettl** [comment]
ah great, in this case I see it as request to document this feature
