### ISSUE TITLE
[Enhancement]: Support for Claude 3.5 Sonnet 2024-10-22

### ISSUE THREAD

**Issue by peteroettl** [intitni/CopilotForXcode#596]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Allow users to add new models on their own when they are available, or
add support for Claude 3.5 Sonnet 2024-10-22

**Comment by intitni** [comment]
The model selection field is a text field, you can type whatever model name you want.

**Comment by intitni** [comment]
Starting from 0.34.3, we will use `-latest` variant in the list when possible.
