### ISSUE TITLE
Update Process in Readme OR way to update without redownloading image.

### ISSUE THREAD

**Issue by ICULikeMac** [intitni/CopilotForXcode#6]
Include the upgrade process in the README.md

i.e Do we need to remove all settings from Settings -> Privacy to relink the application to Xcode Extensions? 

Otherwise, a feature request for updating the app within the currently installed version would be amazing.

**Comment by intitni** [comment]
An update section is added to the README.md. The only extra step needed is to restart the XPC Service.

In-app update is not planned. But I will see if I can submit the app to Homebrew Cask later.

**Comment by ICULikeMac** [comment]
I have downloaded the latest version - restarted the computer and XPC service. The app states all is okay, but in XCode I keep getting the message "cannot communicate with a helper application". When I had this issue previously, I removed all versions of the app and then it started to talking to right one so when updating it seems to looking for another version of the app? Note: The XPC service is definitely running.

**Comment by intitni** [comment]
What do you mean by "removed all versions of the app"? Do you keep the old versions after updates? If so, my guess is that Xcode is using an Xcode extension from an old app version.

**Comment by ICULikeMac** [comment]
I had the xcode version installed + release + a beta version I believe? I removed them all a couple of versions ago and now I have just the release version, however, on updating to the latest version, I have the an issue of xcode reporting it cannot communicate with the helper application - it seems to be looking for the last installed version and not communicating with 0.5 version? I will reinstall and see how I go! Thanks.

**Comment by ICULikeMac** [comment]
Homebrew Added. Will Close.

Still cannot get the tool working in Xcode - Cannot find helper application - however will open separate issue.
