### ISSUE TITLE
[Bug]: Install Language Server - Unable to Install Language Server in Copilot for Xcode

### ISSUE THREAD

**Issue by glg73** [intitni/CopilotForXcode#603]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

Attempting to install the language server in Copilot for Xcode fails. The “Install” button remains grayed out and unresponsive, even after verifying that Node.js is installed and correctly configured. I have checked the FAQ and searched for similar issues but haven’t found a solution.

The Install button should allow me to install the language server after configuring Node.js and setting up Copilot for Xcode as described in the documentation.

<img width="1062" alt="Screenshot 2024-11-13 at 16 34 35" src="https://github.com/user-attachments/assets/cd24122c-8988-4c4c-a728-cdf63e104984">
<img width="903" alt="Screenshot 2024-11-13 at 16 39 10" src="https://github.com/user-attachments/assets/1c1a4e38-daeb-4364-86f6-b00a78f0e6bb">
<img width="1286" alt="Screenshot 2024-11-13 at 10 14 20" src="https://github.com/user-attachments/assets/ba402d15-dc9f-4f0a-af35-c35cadee9e91">

### How to reproduce the bug.

Steps to Reproduce the Bug
Open Copilot for Xcode.app.
Go to Service - GitHub Copilot.
Verify Node.js installation (Node.js version confirmed as v23.2.0 located at /usr/local/bin/node).
Attempt to click on the Install button to install the language server.
Observe that the Install button is grayed out and remains unclickable.

### Relevant log output

```shell
No crash report is available, but the Console shows:

"CFNetworkdownload_huf2sy.tmp couldn't be copied to "executable" because an item with the same name already exists" after downloaded "archive.zip" in /Users/glg/Library/Application Support/com.intii.CopilotForXcode/GitHub Copilot/executable/

or "
```

### macOS version

Version 13.7 (22H123)

### Xcode version

Version 15.2 (15C500b)

### Copilot for Xcode version

Version 0.34.3 (416)

**Comment by intitni** [comment]
Please delete the executable folder and try again. If it's still failing, you can also manually extract the `dist` folder from the archive and put it under `path/to/executable/copilot/dist`.

**Comment by glg73** [comment]
Manually extraction works! Peace and love!

**Comment by intitni** [comment]
If you want to use GitHub Copilot chat, you need to turn "Pretend IDE to be VSCode" on and restart the service app. Also make sure the provider is correct in "Feature > Chat".
