### ISSUE TITLE
[Bug]: Chat memory not working anymore

### ISSUE THREAD

**Issue by peteroettl** [intitni/CopilotForXcode#606]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I use Chat with chat model claude-3-5-sonnet-latest, a context window of 32770 and Memory set to "No Limit".

Since version 0.35.0 (426) it seems the chat has no memory of previous messages anymore.

### How to reproduce the bug.

After discussing a small change with two files as reference (input tokens used: 4337, output tokens used: 1008) I wanted to have receive a summary of the changes as a commit message which could not be provided.

Prompt: 

> write a commit message for the change we have discussed in this conversation

Response:

> I don't see any previous discussion about code changes in our conversation. This appears to be the first message in our chat. Without knowing what changes were made, I cannot write an appropriate commit message.
> 
> Could you please:
> 1. Share the changes that were made, or
> 2. Reference the previous discussion you're referring to
> 
> This will help me write a meaningful and accurate commit message following conventional commit message guidelines.

### macOS version

14.7 (23H124)

### Xcode version

Version 16.1 (16B40)

### Copilot for Xcode version

0.35.0 (426)

**Comment by intitni** [comment]
Uploading the fix for notarization!

**Comment by intitni** [comment]
Fixed in 0.35.1.
