### ISSUE TITLE
[Bug]: Accept on tab enabled even when xcode shortcuts not setup

### ISSUE THREAD

**Issue by GarethBlain** [intitni/CopilotForXcode#614]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

When I press TAB it accepts the current suggestions even though Accept suggestion isn't assigned a shortcut in xcode.

### How to reproduce the bug.

Install extension, type "try" on a new line and then press `TAB`... It will accept the suggested autocomplete which would be great if that was an option in the xcode shortcuts. BUT it is not.
I already have TAB assigned to something else... Now it's broken. I re-assigned the Accept CoPilot's suggestion in xcode's shortcuts to another key but it doesn't stop it using tab!

### macOS version

15.1.1

### Xcode version

16.1

### Copilot for Xcode version

0.29.0

**Comment by intitni** [comment]
You can turn it off in the settings.

<img width="578" alt="Screenshot 2024-12-13 at 00 37 31" src="https://github.com/user-attachments/assets/222a5e5f-e0f9-49d9-b6cf-acd70ece9902" />

**Comment by GarethBlain** [comment]
I’m not sure… it’s a “feature” not a bug because someone decided it wouldn’t follow the rules everyone else does is really valid.
Xcode has shortcuts and a shortcut config. You even added the option to use them. If you want that to be the default that’s great (and I get that it’s the default in VSCode) but just use the existing system everyone else knows and uses. Don’t make your own to run parallel and mess up our systems just add tab as the default when adding it to the shortcut list like it’s designed to be.
