### ISSUE TITLE
[Bug]: Multiple Xcode windows: Accepting code suggestions brings background windows to front

### ISSUE THREAD

**Issue by lemonBill** [intitni/CopilotForXcode#616]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Description
When using Copilot for Xcode (Plus License) with multiple windows open, accepting code suggestions (using Tab key, same as by accept button) unexpectedly brings background Xcode windows to the front, even when they are intentionally hidden behind other application windows. This behavior disrupts the workflow, especially when referencing documentation or other materials while coding.

### Steps to Reproduce
1. Open multiple Xcode windows (e.g., Window 1 and Window 2)
2. Place Window 1 in the foreground (active window)
3. Have Window 2 in the background, covered by windows from other applications
4. Start editing in Window 1
5. When Copilot suggests code, press Tab to accept the suggestion

### Expected Behavior
Only the active Xcode window (Window 1) should remain in focus. Background Xcode windows should maintain their current position in the window stack.

### Actual Behavior
When accepting a Copilot suggestion using Tab, background Xcode windows (Window 2) are automatically brought to the front, overlapping other application windows that were intentionally placed on top of them.

### Environment
- Copilot for Xcode version: 0.35.2
- Xcode version: 15.4
- macOS version: 14.5

### Impact
This behavior significantly impacts the development workflow when users need to reference documentation or other materials while coding, as it requires constant window rearrangement.

### Additional Context
This appears to be a window management issue specific to the Copilot for Xcode integration, as regular code editing operations do not trigger this behavior.

**Comment by intitni** [comment]
Released in 0.35.3
