### ISSUE TITLE
Server unavailable when Node is installed

### ISSUE THREAD

**Issue by inekipelov** [intitni/CopilotForXcode#62]
Calling `which node` return `/usr/local/bin/node`
But when I try use Copilot For Xcode, see error `Server unavailable, please make sure you have installed Node`

<img width="50%" alt="Screenshot 2023-03-20 at 13 50 25" src="https://user-images.githubusercontent.com/3010244/226331151-643f11d3-e03f-449c-ac46-7172104e93b9.png">

What wrong?

**Comment by intitni** [comment]
What's the node version?

**Comment by inekipelov** [comment]
> What's the Node version? Please run `node -v` to see if Node is actually installed.
> 
> I don't know which Node version is supported because the language server part is not maintained by me. I guess v16+ should be fine.

Amazing, thank you. I missed this moment. Installed `v12.18.2`. It should be a reason
