### ISSUE TITLE
Unavailable Node.js installed with nodenv(Anyenv)

### ISSUE THREAD

**Issue by hulk510** [intitni/CopilotForXcode#63]
My node is installed by nodenv(Anyenv), and install CopilotForXcode with brew cask.

`which node` return `/Users/username/.anyenv/envs/nodenv/shims/node`.
I write path to **Path to Node**, then show `Server unavailable, please make sure installed Node.`

<img width="500" alt="" src="https://user-images.githubusercontent.com/33943897/226504933-1ca77a6c-a9fc-46a3-82bb-fb69e1db4b3d.png">

refresh did not change error message.
so I tried to install Node with brew, rewrite **Path to Node** to `/opt/homebrew/Cellar/node/19.8.1/bin/node` is fixed.

<img width="500" alt="スクリーンショット 2023-03-21 12 36 54" src="https://user-images.githubusercontent.com/33943897/226512258-a7235512-088c-408a-87d1-9013bb377f5e.png">

## env
- node v19.8.1
- CopilotForXcode 0.8.6

## Expected behavior
it maybe my environment, but I want to be able to specify Node with nodenv as well.

**Comment by intitni** [comment]
Please check your /Users/username/.anyenv/envs/nodenv/shims/node version, and make sure it's v16+

**Comment by hulk510** [comment]
thanks😊

current node version is 19.8.1
<img width="122" alt="スクリーンショット 2023-03-21 15 14 12" src="https://user-images.githubusercontent.com/33943897/226530955-21fd2f53-4a84-442d-abb9-2c17df8eb2a9.png">

I've downgraded v16.18.1, but it doesn't seem to change. 🤔

**Comment by intitni** [comment]
Please try setting up the language server manually by calling 
`/Users/username/.anyenv/envs/nodenv/shims/node /Applications/Copilot\ for\ Xcode.app/Contents/Applications/CopilotForXcodeExtensionService.app/Contents/Resources/copilot/dist/agent.js --stdio`

**Comment by hulk510** [comment]
![スクリーンショット 2023-03-21 16 02 29](https://user-images.githubusercontent.com/33943897/226537821-8c107b11-e0b5-45fa-9afc-2f50e5f78602.png)

here is response
```
Content-Length: 232

{"jsonrpc":"2.0","method":"LogMessage","params":{"level":0,"message":"[DEBUG] [agent] [2023-03-21T07:02:22.483Z] Agent service starting","metadataStr":"[DEBUG] [agent] [2023-03-21T07:02:22.483Z]","extra":["Agent service starting"]}}
```

**Comment by intitni** [comment]
I have tried that if I use the path that points to a specific version of Node installed via nodenv, it will work. 

For example, `~/.nodenv/versions/19.8.1/bin/node`

The node inside `shims` is actually not a real node, if I understand it correctly, according to nodenv documentation:
> Shims are lightweight executables that simply pass your command along to nodenv. So with nodenv installed, when you run, say, npm, your operating system will do the following:
> - Search your PATH for an executable file named npm
> - Find the nodenv shim named npm at the beginning of your PATH
> - Run the shim named npm, which in turn passes the command along to nodenv

I will add it to FAQ in the next release.

**Comment by hulk510** [comment]
I see. thanks!

**Comment by el-hoshino** [comment]
I'm having the same problem and tried to set Path to Node to the specific path, but it didn't work


https://user-images.githubusercontent.com/3942121/226794972-0da5a718-0b63-4028-8b62-0ca1155930b4.mov

Am I missing something?

**Comment by intitni** [comment]
> I'm having the same problem and tried to set Path to Node to the specific path, but it didn't work
> 
> 
> Am I missing something?

Change ~ to /User/yourusername and restart the app

**Comment by talis-manick** [comment]
Facing a similar issue
<img width="870" alt="image" src="https://user-images.githubusercontent.com/113335152/227070571-619a8aa7-8af9-4812-b24a-1c67399c178b.png">
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/113335152/227070927-c667413a-f93c-4730-86b0-2c327fe2d1ee.png">

**Comment by intitni** [comment]
> Facing a similar issue
> 
> <img width="870" alt="image" src="https://user-images.githubusercontent.com/113335152/227070571-619a8aa7-8af9-4812-b24a-1c67399c178b.png">
> 
> <img width="1008" alt="image" src="https://user-images.githubusercontent.com/113335152/227070927-c667413a-f93c-4730-86b0-2c327fe2d1ee.png">
> 
> 
> 
> 

restart the app and the helper

**Comment by talis-manick** [comment]
> restart the app and the helper
The ssue persists after restarting the helper and also restarting system.

**Comment by adiRandom** [comment]
I tried restarting the system and switched from node 18 nvm to node 19 with brew. Still not working for me

**Comment by intitni** [comment]
Please show me the error message

> I tried restarting the system and switched from node 18 nvm to node 19 with brew. Still not working for me
> 
> <img alt="image" width="526" src="https://user-images.githubusercontent.com/38132701/227710178-8a5d304e-79ee-4b8a-83a3-0b94c58cf9a2.png">
> 
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/38132701/227710228-2e0410a3-a6a5-4aae-a408-6b4835855b17.png">

Please show me the error message

**Comment by adiRandom** [comment]
> Please show me the error message
> 
> > I tried restarting the system and switched from node 18 nvm to node 19 with brew. Still not working for me
> > <img alt="image" width="526" src="https://user-images.githubusercontent.com/38132701/227710178-8a5d304e-79ee-4b8a-83a3-0b94c58cf9a2.png">
> > <img alt="image" width="585" src="https://user-images.githubusercontent.com/38132701/227710228-2e0410a3-a6a5-4aae-a408-6b4835855b17.png">
> 
> Please show me the error message
Same as the others. Sorry for not including it 😅
<img width="452" alt="image" src="https://user-images.githubusercontent.com/38132701/227710742-5279800a-c035-433c-a6d3-306157396c05.png">

**Comment by intitni** [comment]
@adiRandom I have tried version 19.8.1 from brew, and it works for me. To find out the cause, you can open Console.app to observe the logs post by the process `CopilotForXcodeExtensionService` and subsystem `com.chimehq.JSONRPC`

**Comment by nukopy** [comment]
https://github.com/intitni/CopilotForXcode/issues/63#issuecomment-1477386420

> I have tried that if I use the path that points to a specific version of Node installed via nodenv, it will work.
> 
> For example, `Users/username/.nodenv/versions/19.8.1/bin/node`
> 
> The node inside `shims` is actually not a real node, if I understand it correctly, according to nodenv documentation:
> 
> > Shims are lightweight executables that simply pass your command along to nodenv. So with nodenv installed, when you run, say, npm, your operating system will do the following:
> > 
> > * Search your PATH for an executable file named npm
> > * Find the nodenv shim named npm at the beginning of your PATH
> > * Run the shim named npm, which in turn passes the command along to nodenv
> 
> I will add it to FAQ in the next release.

I'm user of anyenv. This solution works for me! Thanks!!

I could set with changing "Path to Node" `/Users/nukopy/.anyenv/envs/nodenv/shims/node` to `/Users/nukopy/.anyenv/envs/nodenv/versions/18.7.0/bin/node`.
