### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by intitni** [intitni/CopilotForXcode#65]
**Q: The extension doesn't show up in the `Editor` menu.**

> A: Please make sure `Copilot` is turned on in `System Settings.app > Privacy & Security > Extensions > Xcode Source Editor Extension`.

**Q: Host app shows `Server unavailable, please make sure you have installed Node`**

> A: Please ensure that the Path to Node correctly points to a valid Node executable. Avoid using `~` in place of `/Users/username`
>
> If you are using Node version `v16.13.x` or anything lower, consider updating to a newer version of Node.
> 
> If you're using `nodenv`, use the path that points to a specific version of Node, such as `/Users/username/.nodenv/versions/19.8.1/bin/node`.
> 
> **After making changes, be sure to restart both the host app and the helper app.**

**Q: The extension says it can't connect to the XPC service/helper.**

> A: If you have just updated the app from an old version, make sure you have restarted the XPC Service.
> 
> Please make sure you have set up Launch Agents, try running `launchctl list | grep com.intii` from the terminal, and see if `com.intii.CopilotForXcode.ExtensionService` exists. If not, check `~/Library/LaunchAgents` to see if `com.intii.CopilotForXcode.ExtensionService.plist` exists. If they don't, and the button in the app fails to create them, please try to do it by hand.
> 
> If you are installing multiple versions of the extension on your machine, it's also possible that Xcode is using the older version of the extension.

**Q: The extension complains that it has no access to the Accessibility API**

> A: Please check if the [Accessibility API permission](https://github.com/intitni/CopilotForXcode#granting-permissions-to-the-app) is setup correctly.

**Q: I turned on real-time suggestions, but nothing happens**

> A: Try typing something in the editor and wait for a little while, if you see an animation from the real-time suggestion indicator or the floating widget, that means the real-time suggestion is correctly triggered. 

**Q: I can't cancel real-time suggestions with mouse clicks, or pressing esc.**

> A: Please check if the [Accessibility API and Input Monitoring permission](https://github.com/intitni/CopilotForXcode#granting-permissions-to-the-app) is setup correctly.
    If you have followed the setup instructions as directed, please also consider granting Input Monitoring permissions to the extension app.

**Q: I have signed in my GitHub account, but the app doesn't generate any suggestions.**

> A: Please make sure the GitHub Copilot status is `OK`. If it's not, it's likely that your GitHub Copilot subscription is not valid. 

**Q: Will it work in future Xcode updates?**

> A: I don't know. This extension uses many tricks to do its job, and these tricks can break in the future.

**Comment by alexlee002** [comment]
Hey, Bro,  Sorry to trouble you.  Would you share me the implementation of  how to launch the `CopilotForXcodeExtensionService.app` while executing the editor command?

**Comment by intitni** [comment]
@alexlee002 The key is to use a launch agent to launch an XPC Service. For reference, you may examine this smaller project: https://github.com/intitni/XccurateFormatter. In its readme, there is a link available that explains how to configure the launch agent.

**Comment by alexlee002** [comment]
@intitni yes, I read that document last weekend, but I failed to do it in my demo... always something wrong

**Comment by alexlee002** [comment]
And another question,  The XPCService commonly without UI,  so , How the source editor extension launches the `CopilotForXcodeExtensionService.app`?   by calling `getService()`?  but I launch it in Terminal via `launchctl`,   the xpc service is launched, but I couldn't find the UI in menubar ...

**Comment by intitni** [comment]
Nobody says an app with UI can't be an XPC Service. So CopilotForXcodeExtensionService.app is the XPC Service and it will launch when getService is called.
2023年5月15日 +0800 20:24 Alex Lee ***@***.***>，写道：

**Comment by alexlee002** [comment]
> Nobody says an app with UI can't be an XPC Service. 
I'm using Xcode 14.3, If I create an App Target, and Add XPCService configuration into Info.plist,  But I Can create a build phase named 'Embed XPCService', and I can only add it to `Embed Foundation Extensions`, but it could work
