### ISSUE TITLE
Error message "Couldn't communicate with a helper application" when setting up Copilot for Xcode

### ISSUE THREAD

**Issue by ast3150** [intitni/CopilotForXcode#71]
I am encountering an error message when trying to set up Copilot for Xcode. Specifically, I receive the message "Couldn't communicate with a helper application" in Copilot for Xcode or whenever I attempt any action within the _Xcode -> Editor -> Copilot_ menu

I have tried using both Xcode 14.2 and 14.3, which I installed via Xcodes. I have also attempted to reinstall both Xcode and Copilot for Xcode multiple times, but the error message persists.

The Node path is setup correctly to `/opt/homebrew/bin/node`.

I'm using Copilot for Xcode 0.8.6 on the latest macOS 13.2.1

I am hoping to receive guidance on how to troubleshoot this issue and successfully set up Copilot for use in Xcode.

Any help or advice would be greatly appreciated. Thank you.

![Screenshot 2023-03-23 at 22 07 43](https://user-images.githubusercontent.com/3421529/227361774-7b452ba1-848a-4e39-a2ff-d3d30f5da182.png)
<img width="559" alt="Screenshot 2023-03-23 at 22 08 22" src="https://user-images.githubusercontent.com/3421529/227361886-c688007e-7742-4cb7-b9ac-585b56f06e19.png">

**Comment by intitni** [comment]
Did you try the steps in FAQ?

**Comment by ast3150** [comment]
Thanks, I had to create the plist manually. It would be helpful to have some more guidance about this in the FAQ, as I had to ask a friend for the proper .plist values so that it works. I can add a PR to improve the Readme.

**Comment by intitni** [comment]
I am moving the [FAQ to this issues](https://github.com/intitni/CopilotForXcode/issues/65), you can reply to it and I will update the FAQ.

Is the 'Setup Launch Agent' button not working for you?

**Comment by intitni** [comment]
Merged
