### ISSUE TITLE
The operation couldn't be completed. (LanguageServerProtocol.ServerError error 8.)

### ISSUE THREAD

**Issue by nicolopadovan** [intitni/CopilotForXcode#88]
Just updated to the latest version.
When I start typing with `Real Time Suggestions` on, I get the following error:

![Screenshot 2023-03-27 at 04 10 13](https://user-images.githubusercontent.com/89971888/227824039-b791145f-3ebe-42df-8576-19ca296cb57b.png)

**Comment by intitni** [comment]
The error is posted by the GitHub Copilot language server. If you encounter such an error, please try:

- Check you GitHub Copilot settings in the host app, make sure the status is OK.
- You can observe the logs posted by the language server using the Console.app. Set up the filter to the process `CopilotForXcodeExtensionService` and subsystem `com.chimehq.JSONRPC` to show only the logs from the language server. See if there is anything you can do.

**Comment by MichaelHuyp** [comment]
how to check GitHub Copilot settings in the host app, make sure the status is OK. @intitni

**Comment by intitni** [comment]
> how to check GitHub Copilot settings in the host app, make sure the status is OK. @intitni

You will find the status in GitHub Copilot account settings.

<img width="408" alt="Screenshot 2023-03-28 at 14 41 31" src="https://user-images.githubusercontent.com/793147/228150747-bcb88e4f-269f-45f4-b577-3015babe4e87.png">

**Comment by z234009184** [comment]
the same issue

**Comment by intitni** [comment]
> the same issue

Does the error persist? If not, just ignore it.

**Comment by nicolopadovan** [comment]
> > the same issue
> 
> Does the error persist? If not, just ignore it.

Appears related to 1. Github Copilot status (as you already provided a solution to); 2. Connection issues: whenever connection is absent or unavailable, this error appears. Probably it would be better to handle the issue in a different way, specifying what it’s related to at least (connection, account status etc).

**Comment by z234009184** [comment]
> > the same issue
> 
> Does the error persist? If not, just ignore it.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/12725906/228570415-49cf3e20-6942-4a3f-9543-ae552578980c.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/12725906/228570487-7bb5d9e9-60c5-41f3-9ddb-36b6a330a781.png">

Sign in succeed，but show Status Not Auth

**Comment by nicolopadovan** [comment]
> > > the same issue
> > 
> > 
> > Does the error persist? If not, just ignore it.
> 
> <img alt="image" width="636" src="https://user-images.githubusercontent.com/12725906/228570415-49cf3e20-6942-4a3f-9543-ae552578980c.png">
> 
> <img alt="image" width="900" src="https://user-images.githubusercontent.com/12725906/228570487-7bb5d9e9-60c5-41f3-9ddb-36b6a330a781.png">
> 
> Sign in succeed，but show Status Not Auth

Try hitting “Refresh” (obviously)
Check if you connected the right github account (must have an active copilot subscription)

**Comment by xiaoerlong** [comment]
![image](https://user-images.githubusercontent.com/14815745/228732806-20ea82a3-5241-4317-a3ec-ef242f187f65.png)
Try hitting “Refresh”
Butt he problem still exists

**Comment by intitni** [comment]
> ![image](https://user-images.githubusercontent.com/14815745/228732806-20ea82a3-5241-4317-a3ec-ef242f187f65.png)
> 
> Try hitting “Refresh”
> 
> Butt he problem still exists

Do you have an active GiHub Copilot subscription?

**Comment by xiaoerlong** [comment]
> > ![image](https://user-images.githubusercontent.com/14815745/228732806-20ea82a3-5241-4317-a3ec-ef242f187f65.png)
> > Try hitting “Refresh”
> > Butt he problem still exists
> 
> Do you have an active GiHub Copilot subscription?

It's my problem, i didn't active GiHub Copilot subscription

**Comment by mikeRozen** [comment]
I have the same issue I have an active GitHub account and get the error every time I try to sign in

**Comment by mikeRozen** [comment]
Sorry, updating to latest node resolved  the issue
