### ISSUE TITLE
Chat feature (which is awesome!) only shows one line of text for typing

### ISSUE THREAD

**Issue by maxmiranda** [intitni/CopilotForXcode#89]
![image](https://user-images.githubusercontent.com/24932260/227843147-25d402e3-0b73-487a-bb4a-d89176b3a9c6.png)

![image](https://user-images.githubusercontent.com/24932260/227843169-10e6e550-53de-4a86-a9b3-e3916c6d9eda.png)

**Comment by intitni** [comment]
I looks like you are using macOS Monterey. ~~The multiline thing for `TextField` in SwiftUI in not available before Ventura, so no luck.~~ The image clear history button seems to be not available in Monterey. too. Apple...

I can change the icon but I may not work on the multiline text... Or wait. Looks like there is an `TextEditor` in SwiftUI, may give it a try, too

**Comment by intitni** [comment]
Released in 0.10.0
