### ISSUE TITLE
对oc语言的支持如何？

### ISSUE THREAD

**Issue by dustturtle** [intitni/CopilotForXcode#90]
RT~ 目前我们主要还是oc开发

**Comment by intitni** [comment]
这取决于 GitHub Copilot 和 ChatGPT，GitHub Copilot 有免费试用期，可以开通了试试

**Comment by dustturtle** [comment]
插件本身是支持的吧？

**Comment by intitni** [comment]
是的，不如说插件不关心你用的是什么语言，你要把它用于 JSON、XML 都可以

**Comment by Garenge** [comment]
不支持
