### ISSUE TITLE
ChatPanel is hidden when trying to perform Japanese conversion in ChatPanel.

### ISSUE THREAD

**Issue by SNQ-2001** [intitni/CopilotForXcode#92]
https://user-images.githubusercontent.com/84154073/227979564-6bdac6b1-1874-4159-ba17-917972b22ad3.mov

**Comment by intitni** [comment]
I tried the Romaji input method and couldn't reproduce this. I don't think the extension can block Xcode because they are different processes. 

Does it happen all the time? If you, or anyone, knows how to reproduce it, please let me know. Would be great if someone can fix it.

**Comment by SNQ-2001** [comment]
I think the ChatPanel is disappearing when the standard predictive conversion window appears

Maybe this is the cause

**Comment by intitni** [comment]
The chat panel disappear when both it and Xcode loses focus, it's more likely to be a consequence.

**Comment by intitni** [comment]
Maybe related to #95

**Comment by SNQ-2001** [comment]
@intitni 

I also encountered this problem yesterday.
I was able to solve it by restarting CopilotForXcode.

I did a little research,
intitnis was right, there was no connection to the predictive conversion window.

The same problem occurred when I hid the predictive conversion window.

😭

**Comment by SNQ-2001** [comment]
@intitni 

I have found a pattern that works fine.
Works fine for black Xcode used when debugging Xcode Editor Extension
However, it does not work correctly for blue Xcode

If we can find the difference between the two, we may be closer to a solution.

blue Xcode:

https://user-images.githubusercontent.com/84154073/228170930-8f11e4fe-65f7-4318-8461-230f7c165160.mov

black Xcode:

https://user-images.githubusercontent.com/84154073/228171107-cd39a9fb-4507-4ec3-be70-19f0a6eee7a3.mov

**Comment by intitni** [comment]
Please try release 0.10.0 to see if it's fixed.

**Comment by SNQ-2001** [comment]
@intitni 

I apologize for the delay in confirmation.
The bug has been resolved!

**Comment by intitni** [comment]
@SNQ-2001 ( • ̀ω•́ )b
