### ISSUE TITLE
When requesting "Explain" I get an OpenAI error message: "You didn't provide an API key"

### ISSUE THREAD

**Issue by robreuss** [intitni/CopilotForXcode#94]
When I request "Explain" for suggestions I get this error message in the widget:

"You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys."

I saw in the install notes that I needed to have an OpenAI API Key and created one but it was never requested during the install process and I can find nowhere in the app or Xcode to enter it.

**Comment by freepicheep** [comment]
Open the Copilot For Xcode application. Under Accounts, click on OpenAI and you will enter your API key there.

**Comment by robreuss** [comment]
Thanks, worked.
