### ISSUE TITLE
Unable to type text in GPT chat

### ISSUE THREAD

**Issue by freepicheep** [intitni/CopilotForXcode#95]
The window for entering text when I choose to chat with current selection does not allow me to enter and text. Strangely, I can past text into the window, but I get the Mac error sound when I try selecting it and typing. 

<img width="1512" alt="error" src="https://user-images.githubusercontent.com/78331877/228100923-22f68a35-1100-4e7e-954b-28c7fe2401d5.png">

**Comment by intitni** [comment]
I am using a trick to switch its activation policy to `.accessory` when the chat box is displayed so that users can type in the textfield. But looks like it's not very reliable. I will try to tweak it in the next release. For now you can quit the helper app from the menubar, and call a random command to restart it, maybe it will allow you to type this time.

**Comment by freepicheep** [comment]
That fixed it for now. Thanks!

**Comment by shanecowherd** [comment]
+1

**Comment by z234009184** [comment]
the same issue

**Comment by chlebta** [comment]
Same issue

**Comment by intitni** [comment]
Please try release 0.10.0 to see if it's fixed.

**Comment by chlebta** [comment]
@intitni Yes now I can type but explain is broken I get this 

`This model's maximum context length is 4097 tokens. However, you requested 4163 tokens (67 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.`

**Comment by intitni** [comment]
> @intitni Yes now I can type but explain is broken I get this
> 
> `This model's maximum context length is 4097 tokens. However, you requested 4163 tokens (67 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.` from where he get this value: `4096 in the completion`?

The responses from ChatGPT are included in the token count. It's possible that the bot is attempting to provide an excessively lengthy explanation. To resolve this, consider reducing the maximum token limit to half of the maximum in settings. We'll address any issues with token limits at a later time.
